// See README.txt for information and build instructions.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/MessageType.proto

package MessageType

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ErrorInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrCode *int64 `protobuf:"varint,1,opt,name=err_code,json=errCode,def=2147483648" json:"err_code,omitempty"`
	ErrMsg  []byte `protobuf:"bytes,2,opt,name=err_msg,json=errMsg" json:"err_msg,omitempty"` // optional RichTextDef.RichTextBlock err_msg_rich = 3;
}

// Default values for ErrorInfo fields.
const (
	Default_ErrorInfo_ErrCode = int64(2147483648)
)

func (x *ErrorInfo) Reset() {
	*x = ErrorInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MessageType_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ErrorInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorInfo) ProtoMessage() {}

func (x *ErrorInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_MessageType_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorInfo.ProtoReflect.Descriptor instead.
func (*ErrorInfo) Descriptor() ([]byte, []int) {
	return file_common_MessageType_proto_rawDescGZIP(), []int{0}
}

func (x *ErrorInfo) GetErrCode() int64 {
	if x != nil && x.ErrCode != nil {
		return *x.ErrCode
	}
	return Default_ErrorInfo_ErrCode
}

func (x *ErrorInfo) GetErrMsg() []byte {
	if x != nil {
		return x.ErrMsg
	}
	return nil
}

type IdInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Content []byte      `protobuf:"bytes,1,opt,name=content" json:"content,omitempty"`
	Extra   []*RichInfo `protobuf:"bytes,2,rep,name=extra" json:"extra,omitempty"`
}

func (x *IdInfo) Reset() {
	*x = IdInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MessageType_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdInfo) ProtoMessage() {}

func (x *IdInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_MessageType_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdInfo.ProtoReflect.Descriptor instead.
func (*IdInfo) Descriptor() ([]byte, []int) {
	return file_common_MessageType_proto_rawDescGZIP(), []int{1}
}

func (x *IdInfo) GetContent() []byte {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *IdInfo) GetExtra() []*RichInfo {
	if x != nil {
		return x.Extra
	}
	return nil
}

type RichInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Begin    *int32 `protobuf:"varint,1,req,name=begin" json:"begin,omitempty"`
	End      *int32 `protobuf:"varint,2,req,name=end" json:"end,omitempty"`
	Tag      *int32 `protobuf:"varint,3,opt,name=tag" json:"tag,omitempty"`
	TagId    *int32 `protobuf:"varint,4,opt,name=tag_id,json=tagId" json:"tag_id,omitempty"`
	TagExtra []byte `protobuf:"bytes,5,opt,name=tag_extra,json=tagExtra" json:"tag_extra,omitempty"`
}

func (x *RichInfo) Reset() {
	*x = RichInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MessageType_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RichInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RichInfo) ProtoMessage() {}

func (x *RichInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_MessageType_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RichInfo.ProtoReflect.Descriptor instead.
func (*RichInfo) Descriptor() ([]byte, []int) {
	return file_common_MessageType_proto_rawDescGZIP(), []int{2}
}

func (x *RichInfo) GetBegin() int32 {
	if x != nil && x.Begin != nil {
		return *x.Begin
	}
	return 0
}

func (x *RichInfo) GetEnd() int32 {
	if x != nil && x.End != nil {
		return *x.End
	}
	return 0
}

func (x *RichInfo) GetTag() int32 {
	if x != nil && x.Tag != nil {
		return *x.Tag
	}
	return 0
}

func (x *RichInfo) GetTagId() int32 {
	if x != nil && x.TagId != nil {
		return *x.TagId
	}
	return 0
}

func (x *RichInfo) GetTagExtra() []byte {
	if x != nil {
		return x.TagExtra
	}
	return nil
}

type TipsMsgId struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TipsType   *int32 `protobuf:"varint,1,req,name=tipsType" json:"tipsType,omitempty"`
	PlaceId    *int64 `protobuf:"varint,2,opt,name=placeId" json:"placeId,omitempty"`
	TipContent []byte `protobuf:"bytes,3,opt,name=tipContent" json:"tipContent,omitempty"`
}

func (x *TipsMsgId) Reset() {
	*x = TipsMsgId{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MessageType_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TipsMsgId) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TipsMsgId) ProtoMessage() {}

func (x *TipsMsgId) ProtoReflect() protoreflect.Message {
	mi := &file_common_MessageType_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TipsMsgId.ProtoReflect.Descriptor instead.
func (*TipsMsgId) Descriptor() ([]byte, []int) {
	return file_common_MessageType_proto_rawDescGZIP(), []int{3}
}

func (x *TipsMsgId) GetTipsType() int32 {
	if x != nil && x.TipsType != nil {
		return *x.TipsType
	}
	return 0
}

func (x *TipsMsgId) GetPlaceId() int64 {
	if x != nil && x.PlaceId != nil {
		return *x.PlaceId
	}
	return 0
}

func (x *TipsMsgId) GetTipContent() []byte {
	if x != nil {
		return x.TipContent
	}
	return nil
}

var File_common_MessageType_proto protoreflect.FileDescriptor

var file_common_MessageType_proto_rawDesc = []byte{
	0x0a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0b, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x22, 0x4b, 0x0a, 0x09, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x0a, 0x32, 0x31, 0x34, 0x37, 0x34, 0x38, 0x33, 0x36,
	0x34, 0x38, 0x52, 0x07, 0x65, 0x72, 0x72, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x65,
	0x72, 0x72, 0x5f, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x06, 0x65, 0x72,
	0x72, 0x4d, 0x73, 0x67, 0x22, 0x4f, 0x0a, 0x06, 0x49, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x18,
	0x0a, 0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52,
	0x07, 0x63, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74, 0x12, 0x2b, 0x0a, 0x05, 0x65, 0x78, 0x74, 0x72,
	0x61, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x52, 0x69, 0x63, 0x68, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05,
	0x65, 0x78, 0x74, 0x72, 0x61, 0x22, 0x78, 0x0a, 0x08, 0x52, 0x69, 0x63, 0x68, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x14, 0x0a, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05,
	0x52, 0x05, 0x62, 0x65, 0x67, 0x69, 0x6e, 0x12, 0x10, 0x0a, 0x03, 0x65, 0x6e, 0x64, 0x18, 0x02,
	0x20, 0x02, 0x28, 0x05, 0x52, 0x03, 0x65, 0x6e, 0x64, 0x12, 0x10, 0x0a, 0x03, 0x74, 0x61, 0x67,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x74, 0x61, 0x67, 0x12, 0x15, 0x0a, 0x06, 0x74,
	0x61, 0x67, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x61, 0x67,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x61, 0x67, 0x5f, 0x65, 0x78, 0x74, 0x72, 0x61, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x08, 0x74, 0x61, 0x67, 0x45, 0x78, 0x74, 0x72, 0x61, 0x22,
	0x61, 0x0a, 0x09, 0x54, 0x69, 0x70, 0x73, 0x4d, 0x73, 0x67, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08,
	0x74, 0x69, 0x70, 0x73, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x05, 0x52, 0x08,
	0x74, 0x69, 0x70, 0x73, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x6c, 0x61, 0x63,
	0x65, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6c, 0x61, 0x63, 0x65,
	0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x74, 0x69, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65, 0x6e, 0x74,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x74, 0x69, 0x70, 0x43, 0x6f, 0x6e, 0x74, 0x65,
	0x6e, 0x74, 0x42, 0x39, 0x5a, 0x26, 0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0xaa, 0x02, 0x0e, 0x50,
	0x62, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65,
}

var (
	file_common_MessageType_proto_rawDescOnce sync.Once
	file_common_MessageType_proto_rawDescData = file_common_MessageType_proto_rawDesc
)

func file_common_MessageType_proto_rawDescGZIP() []byte {
	file_common_MessageType_proto_rawDescOnce.Do(func() {
		file_common_MessageType_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_MessageType_proto_rawDescData)
	})
	return file_common_MessageType_proto_rawDescData
}

var file_common_MessageType_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_MessageType_proto_goTypes = []interface{}{
	(*ErrorInfo)(nil), // 0: MessageType.ErrorInfo
	(*IdInfo)(nil),    // 1: MessageType.IdInfo
	(*RichInfo)(nil),  // 2: MessageType.RichInfo
	(*TipsMsgId)(nil), // 3: MessageType.TipsMsgId
}
var file_common_MessageType_proto_depIdxs = []int32{
	2, // 0: MessageType.IdInfo.extra:type_name -> MessageType.RichInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_MessageType_proto_init() }
func file_common_MessageType_proto_init() {
	if File_common_MessageType_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_MessageType_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ErrorInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_MessageType_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_MessageType_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RichInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_MessageType_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TipsMsgId); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_MessageType_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_MessageType_proto_goTypes,
		DependencyIndexes: file_common_MessageType_proto_depIdxs,
		MessageInfos:      file_common_MessageType_proto_msgTypes,
	}.Build()
	File_common_MessageType_proto = out.File
	file_common_MessageType_proto_rawDesc = nil
	file_common_MessageType_proto_goTypes = nil
	file_common_MessageType_proto_depIdxs = nil
}
