// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/UserAttributeChg.proto

package UserAttributeChg

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AttributeChgInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttributeType *int32  `protobuf:"varint,1,opt,name=attribute_type,json=attributeType" json:"attribute_type,omitempty"` ///  属性类型 BaseStruct.h  struct STRU_USER_ATTRIBUTE_CHG_INFO  enum
	ChgType       *int32  `protobuf:"varint,2,opt,name=chg_type,json=chgType" json:"chg_type,omitempty"`                   ///  变动理由类型(交易类型)
	ChgReason     *string `protobuf:"bytes,3,opt,name=chg_reason,json=chgReason" json:"chg_reason,omitempty"`              ///  变动理由说明(客户端上传的请求的session,透传给客户端)
	CurData       *int64  `protobuf:"varint,4,opt,name=cur_data,json=curData" json:"cur_data,omitempty"`                   ///  当前值 (变化后的值)
	ChgData       *int32  `protobuf:"varint,5,opt,name=chg_data,json=chgData" json:"chg_data,omitempty"`                   ///  变化值（本次变化的变化值）
	Session       *int64  `protobuf:"varint,6,opt,name=session" json:"session,omitempty"`                                  ///  变化序号(自增，同一个用户可能不连续, 0重置数值)
	BuildingGuid  *string `protobuf:"bytes,7,opt,name=building_guid,json=buildingGuid" json:"building_guid,omitempty"`     ///  建筑ID
	SubType       *int32  `protobuf:"varint,8,opt,name=sub_type,json=subType" json:"sub_type,omitempty"`                   ///  变动理由子类型(交易类型)
}

func (x *AttributeChgInfo) Reset() {
	*x = AttributeChgInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserAttributeChg_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AttributeChgInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AttributeChgInfo) ProtoMessage() {}

func (x *AttributeChgInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserAttributeChg_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AttributeChgInfo.ProtoReflect.Descriptor instead.
func (*AttributeChgInfo) Descriptor() ([]byte, []int) {
	return file_common_UserAttributeChg_proto_rawDescGZIP(), []int{0}
}

func (x *AttributeChgInfo) GetAttributeType() int32 {
	if x != nil && x.AttributeType != nil {
		return *x.AttributeType
	}
	return 0
}

func (x *AttributeChgInfo) GetChgType() int32 {
	if x != nil && x.ChgType != nil {
		return *x.ChgType
	}
	return 0
}

func (x *AttributeChgInfo) GetChgReason() string {
	if x != nil && x.ChgReason != nil {
		return *x.ChgReason
	}
	return ""
}

func (x *AttributeChgInfo) GetCurData() int64 {
	if x != nil && x.CurData != nil {
		return *x.CurData
	}
	return 0
}

func (x *AttributeChgInfo) GetChgData() int32 {
	if x != nil && x.ChgData != nil {
		return *x.ChgData
	}
	return 0
}

func (x *AttributeChgInfo) GetSession() int64 {
	if x != nil && x.Session != nil {
		return *x.Session
	}
	return 0
}

func (x *AttributeChgInfo) GetBuildingGuid() string {
	if x != nil && x.BuildingGuid != nil {
		return *x.BuildingGuid
	}
	return ""
}

func (x *AttributeChgInfo) GetSubType() int32 {
	if x != nil && x.SubType != nil {
		return *x.SubType
	}
	return 0
}

//## 4
// 10424	UN_TCP_PACK_CLI_NEW_USER_ATTRIBUTE_CHG_ID	新用户属性变化包
type UserAttributeChgID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ChgInfo []*AttributeChgInfo `protobuf:"bytes,1,rep,name=chg_info,json=chgInfo" json:"chg_info,omitempty"`
}

func (x *UserAttributeChgID) Reset() {
	*x = UserAttributeChgID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserAttributeChg_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAttributeChgID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAttributeChgID) ProtoMessage() {}

func (x *UserAttributeChgID) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserAttributeChg_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAttributeChgID.ProtoReflect.Descriptor instead.
func (*UserAttributeChgID) Descriptor() ([]byte, []int) {
	return file_common_UserAttributeChg_proto_rawDescGZIP(), []int{1}
}

func (x *UserAttributeChgID) GetChgInfo() []*AttributeChgInfo {
	if x != nil {
		return x.ChgInfo
	}
	return nil
}

var File_common_UserAttributeChg_proto protoreflect.FileDescriptor

var file_common_UserAttributeChg_proto_rawDesc = []byte{
	0x0a, 0x1d, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74,
	0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x68, 0x67, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x10, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x68,
	0x67, 0x22, 0x83, 0x02, 0x0a, 0x10, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43,
	0x68, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x25, 0x0a, 0x0e, 0x61, 0x74, 0x74, 0x72, 0x69, 0x62,
	0x75, 0x74, 0x65, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0d,
	0x61, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x19, 0x0a,
	0x08, 0x63, 0x68, 0x67, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x63, 0x68, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x63, 0x68, 0x67, 0x5f,
	0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x63, 0x68,
	0x67, 0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x75, 0x72, 0x5f, 0x64,
	0x61, 0x74, 0x61, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x63, 0x75, 0x72, 0x44, 0x61,
	0x74, 0x61, 0x12, 0x19, 0x0a, 0x08, 0x63, 0x68, 0x67, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x63, 0x68, 0x67, 0x44, 0x61, 0x74, 0x61, 0x12, 0x18, 0x0a,
	0x07, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x62, 0x75, 0x69, 0x6c, 0x64,
	0x69, 0x6e, 0x67, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x62, 0x75, 0x69, 0x6c, 0x64, 0x69, 0x6e, 0x67, 0x47, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08,
	0x73, 0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x08, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07,
	0x73, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x22, 0x53, 0x0a, 0x12, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x68, 0x67, 0x49, 0x44, 0x12, 0x3d, 0x0a,
	0x08, 0x63, 0x68, 0x67, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x22, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43,
	0x68, 0x67, 0x2e, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x68, 0x67, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x63, 0x68, 0x67, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x43, 0x5a, 0x2b,
	0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x41,
	0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x68, 0x67, 0xaa, 0x02, 0x13, 0x50, 0x62,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x74, 0x74, 0x72, 0x69, 0x62, 0x75, 0x74, 0x65, 0x43, 0x68,
	0x67,
}

var (
	file_common_UserAttributeChg_proto_rawDescOnce sync.Once
	file_common_UserAttributeChg_proto_rawDescData = file_common_UserAttributeChg_proto_rawDesc
)

func file_common_UserAttributeChg_proto_rawDescGZIP() []byte {
	file_common_UserAttributeChg_proto_rawDescOnce.Do(func() {
		file_common_UserAttributeChg_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_UserAttributeChg_proto_rawDescData)
	})
	return file_common_UserAttributeChg_proto_rawDescData
}

var file_common_UserAttributeChg_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_UserAttributeChg_proto_goTypes = []interface{}{
	(*AttributeChgInfo)(nil),   // 0: UserAttributeChg.AttributeChgInfo
	(*UserAttributeChgID)(nil), // 1: UserAttributeChg.UserAttributeChgID
}
var file_common_UserAttributeChg_proto_depIdxs = []int32{
	0, // 0: UserAttributeChg.UserAttributeChgID.chg_info:type_name -> UserAttributeChg.AttributeChgInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_UserAttributeChg_proto_init() }
func file_common_UserAttributeChg_proto_init() {
	if File_common_UserAttributeChg_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_UserAttributeChg_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AttributeChgInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_UserAttributeChg_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAttributeChgID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_UserAttributeChg_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_UserAttributeChg_proto_goTypes,
		DependencyIndexes: file_common_UserAttributeChg_proto_depIdxs,
		MessageInfos:      file_common_UserAttributeChg_proto_msgTypes,
	}.Build()
	File_common_UserAttributeChg_proto = out.File
	file_common_UserAttributeChg_proto_rawDesc = nil
	file_common_UserAttributeChg_proto_goTypes = nil
	file_common_UserAttributeChg_proto_depIdxs = nil
}
