// Code generated by protoc-gen-go.
// source: paipai_world/common/UserAttributeChg.proto
// DO NOT EDIT!

/*
Package UserAttributeChg is a generated protocol buffer package.

It is generated from these files:

	paipai_world/common/UserAttributeChg.proto

It has these top-level messages:

	AttributeChgInfo
	UserAttributeChgID
*/
package UserAttributeChg

import proto "gitlab.ifreetalk.com/maze-plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AttributeChgInfo struct {
	AttributeType    *int32  `protobuf:"varint,1,opt,name=attribute_type,json=attributeType" json:"attribute_type,omitempty"`
	ChgType          *int32  `protobuf:"varint,2,opt,name=chg_type,json=chgType" json:"chg_type,omitempty"`
	ChgReason        *string `protobuf:"bytes,3,opt,name=chg_reason,json=chgReason" json:"chg_reason,omitempty"`
	CurData          *int64  `protobuf:"varint,4,opt,name=cur_data,json=curData" json:"cur_data,omitempty"`
	ChgData          *int32  `protobuf:"varint,5,opt,name=chg_data,json=chgData" json:"chg_data,omitempty"`
	Session          *int64  `protobuf:"varint,6,opt,name=session" json:"session,omitempty"`
	BuildingGuid     *string `protobuf:"bytes,7,opt,name=building_guid,json=buildingGuid" json:"building_guid,omitempty"`
	SubType          *int32  `protobuf:"varint,8,opt,name=sub_type,json=subType" json:"sub_type,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *AttributeChgInfo) Reset()                    { *m = AttributeChgInfo{} }
func (m *AttributeChgInfo) String() string            { return proto.CompactTextString(m) }
func (*AttributeChgInfo) ProtoMessage()               {}
func (*AttributeChgInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AttributeChgInfo) GetAttributeType() int32 {
	if m != nil && m.AttributeType != nil {
		return *m.AttributeType
	}
	return 0
}

func (m *AttributeChgInfo) GetChgType() int32 {
	if m != nil && m.ChgType != nil {
		return *m.ChgType
	}
	return 0
}

func (m *AttributeChgInfo) GetChgReason() string {
	if m != nil && m.ChgReason != nil {
		return *m.ChgReason
	}
	return ""
}

func (m *AttributeChgInfo) GetCurData() int64 {
	if m != nil && m.CurData != nil {
		return *m.CurData
	}
	return 0
}

func (m *AttributeChgInfo) GetChgData() int32 {
	if m != nil && m.ChgData != nil {
		return *m.ChgData
	}
	return 0
}

func (m *AttributeChgInfo) GetSession() int64 {
	if m != nil && m.Session != nil {
		return *m.Session
	}
	return 0
}

func (m *AttributeChgInfo) GetBuildingGuid() string {
	if m != nil && m.BuildingGuid != nil {
		return *m.BuildingGuid
	}
	return ""
}

func (m *AttributeChgInfo) GetSubType() int32 {
	if m != nil && m.SubType != nil {
		return *m.SubType
	}
	return 0
}

// ## 4
// 10424	UN_TCP_PACK_CLI_NEW_USER_ATTRIBUTE_CHG_ID	新用户属性变化包
type UserAttributeChgID struct {
	ChgInfo          []*AttributeChgInfo `protobuf:"bytes,1,rep,name=chg_info,json=chgInfo" json:"chg_info,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *UserAttributeChgID) Reset()                    { *m = UserAttributeChgID{} }
func (m *UserAttributeChgID) String() string            { return proto.CompactTextString(m) }
func (*UserAttributeChgID) ProtoMessage()               {}
func (*UserAttributeChgID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserAttributeChgID) GetChgInfo() []*AttributeChgInfo {
	if m != nil {
		return m.ChgInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*AttributeChgInfo)(nil), "UserAttributeChg.AttributeChgInfo")
	proto.RegisterType((*UserAttributeChgID)(nil), "UserAttributeChg.UserAttributeChgID")
}

func init() { proto.RegisterFile("paipai_world/common/UserAttributeChg.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 267 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x90, 0xcf, 0x4b, 0xc3, 0x30,
	0x1c, 0xc5, 0xc9, 0xea, 0xec, 0x16, 0x9d, 0x8c, 0x9c, 0xe2, 0x41, 0x28, 0x15, 0xa1, 0x78, 0xd8,
	0xc0, 0xbb, 0x07, 0x71, 0x20, 0xbb, 0x56, 0x3d, 0x97, 0x34, 0xc9, 0xd2, 0xc0, 0x96, 0x84, 0xfc,
	0x40, 0x76, 0xf6, 0x1f, 0x97, 0x26, 0xb6, 0x48, 0xbd, 0x25, 0x9f, 0xf7, 0xfd, 0xbe, 0xef, 0xe3,
	0xc1, 0x47, 0x43, 0xa4, 0x21, 0xb2, 0xf9, 0xd2, 0xf6, 0xc8, 0xb6, 0x54, 0x9f, 0x4e, 0x5a, 0x6d,
	0x3f, 0x1d, 0xb7, 0x2f, 0xde, 0x5b, 0xd9, 0x06, 0xcf, 0x5f, 0x3b, 0xb1, 0x31, 0x56, 0x7b, 0x8d,
	0xd6, 0x53, 0x5e, 0x7e, 0xcf, 0xe0, 0xfa, 0x2f, 0xd8, 0xab, 0x83, 0x46, 0x0f, 0xf0, 0x86, 0x0c,
	0xac, 0xf1, 0x67, 0xc3, 0x31, 0x28, 0x40, 0x35, 0xaf, 0x57, 0x23, 0xfd, 0x38, 0x1b, 0x8e, 0x6e,
	0xe1, 0x82, 0x76, 0x22, 0x0d, 0xcc, 0xe2, 0x40, 0x4e, 0x3b, 0x11, 0xa5, 0x3b, 0x08, 0x7b, 0xc9,
	0x72, 0xe2, 0xb4, 0xc2, 0x59, 0x01, 0xaa, 0x65, 0xbd, 0xa4, 0x9d, 0xa8, 0x23, 0x88, 0x9b, 0xc1,
	0x36, 0x8c, 0x78, 0x82, 0x2f, 0x0a, 0x50, 0x65, 0x75, 0x4e, 0x83, 0xdd, 0x11, 0x4f, 0x06, 0xd3,
	0x28, 0xcd, 0x47, 0xd3, 0x28, 0x61, 0x98, 0x3b, 0xee, 0x9c, 0xd4, 0x0a, 0x5f, 0xa6, 0xa5, 0xdf,
	0x2f, 0xba, 0x87, 0xab, 0x36, 0xc8, 0x23, 0x93, 0x4a, 0x34, 0x22, 0x48, 0x86, 0xf3, 0x78, 0xf1,
	0x7a, 0x80, 0x6f, 0x41, 0xb2, 0xde, 0xd9, 0x85, 0x36, 0xc5, 0x5d, 0x24, 0x67, 0x17, 0xda, 0x3e,
	0x6e, 0xf9, 0x0e, 0xd1, 0xb4, 0x99, 0xfd, 0x0e, 0x3d, 0xa7, 0x28, 0x52, 0x1d, 0x34, 0x06, 0x45,
	0x56, 0x5d, 0x3d, 0x95, 0x9b, 0x7f, 0xc5, 0x4e, 0xcb, 0x8b, 0x71, 0xfb, 0xc7, 0x4f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x59, 0x93, 0x42, 0x7e, 0x99, 0x01, 0x00, 0x00,
}
