version: '3.8'

services:
  app:
    build: .
    container_name: maze-server
    ports:
      - "5997:5997"
      - "5998:5998"
      - "5999:5999"
    depends_on:
      - mysql
      - redis
    env_file:
      - .env
    network_mode: "host"

  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mysql
      MYSQL_DATABASE: maze
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
