// Code generated by protoc-gen-go.
// source: paipai_world/common/MazeEquipMix.proto
// DO NOT EDIT!

/*
Package MazeEquipMix is a generated protocol buffer package.

It is generated from these files:

	paipai_world/common/MazeEquipMix.proto

It has these top-level messages:

	MazeEquipMixCostRQ
	MazeEquipMixCostRS
	MazeEquipMixRQ
	MazeEquipMixRS
*/
package MazeEquipMix

import proto "gitlab.ifreetalk.com/plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"
import MessageType "gitlab.ifreetalk.com/plate/protodef/MessageType"
import Common "gitlab.ifreetalk.com/plate/protodef/Common"
import MazeCommon "gitlab.ifreetalk.com/plate/protodef/MazeCommon"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ## 16265
// 迷宫装备合成消耗请求包
type MazeEquipMixCostRQ struct {
	Header           *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *MazeEquipMixCostRQ) Reset()                    { *m = MazeEquipMixCostRQ{} }
func (m *MazeEquipMixCostRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeEquipMixCostRQ) ProtoMessage()               {}
func (*MazeEquipMixCostRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MazeEquipMixCostRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// ## 16266
// 迷宫装备合成消耗回包
type MazeEquipMixCostRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header           *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Cost             []*MazeCommon.MazeItem `protobuf:"bytes,3,rep,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeEquipMixCostRS) Reset()                    { *m = MazeEquipMixCostRS{} }
func (m *MazeEquipMixCostRS) String() string            { return proto.CompactTextString(m) }
func (*MazeEquipMixCostRS) ProtoMessage()               {}
func (*MazeEquipMixCostRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MazeEquipMixCostRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *MazeEquipMixCostRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeEquipMixCostRS) GetCost() []*MazeCommon.MazeItem {
	if m != nil {
		return m.Cost
	}
	return nil
}

// ## 16267
// 迷宫装备合成请求包
type MazeEquipMixRQ struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Cost             []*MazeCommon.MazeItem `protobuf:"bytes,2,rep,name=cost" json:"cost,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeEquipMixRQ) Reset()                    { *m = MazeEquipMixRQ{} }
func (m *MazeEquipMixRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeEquipMixRQ) ProtoMessage()               {}
func (*MazeEquipMixRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MazeEquipMixRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeEquipMixRQ) GetCost() []*MazeCommon.MazeItem {
	if m != nil {
		return m.Cost
	}
	return nil
}

// ## 16268
// 迷宫装备合成回包
type MazeEquipMixRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header           *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Equip            []*MazeCommon.MazeItem `protobuf:"bytes,3,rep,name=equip" json:"equip,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeEquipMixRS) Reset()                    { *m = MazeEquipMixRS{} }
func (m *MazeEquipMixRS) String() string            { return proto.CompactTextString(m) }
func (*MazeEquipMixRS) ProtoMessage()               {}
func (*MazeEquipMixRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MazeEquipMixRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *MazeEquipMixRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeEquipMixRS) GetEquip() []*MazeCommon.MazeItem {
	if m != nil {
		return m.Equip
	}
	return nil
}

func init() {
	proto.RegisterType((*MazeEquipMixCostRQ)(nil), "MazeEquipMix.MazeEquipMixCostRQ")
	proto.RegisterType((*MazeEquipMixCostRS)(nil), "MazeEquipMix.MazeEquipMixCostRS")
	proto.RegisterType((*MazeEquipMixRQ)(nil), "MazeEquipMix.MazeEquipMixRQ")
	proto.RegisterType((*MazeEquipMixRS)(nil), "MazeEquipMix.MazeEquipMixRS")
}

func init() { proto.RegisterFile("paipai_world/common/MazeEquipMix.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 246 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2b, 0x48, 0xcc, 0x2c,
	0x48, 0xcc, 0x8c, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3,
	0xf7, 0x4d, 0xac, 0x4a, 0x75, 0x2d, 0x2c, 0xcd, 0x2c, 0xf0, 0xcd, 0xac, 0xd0, 0x2b, 0x28, 0xca,
	0x2f, 0xc9, 0x17, 0xe2, 0x41, 0x16, 0x93, 0x12, 0xf4, 0x4d, 0x2d, 0x2e, 0x4e, 0x4c, 0x4f, 0x0d,
	0xa9, 0x2c, 0x48, 0x85, 0x28, 0x90, 0x52, 0xc0, 0x66, 0x90, 0x33, 0x98, 0x82, 0xaa, 0x50, 0xc1,
	0x65, 0x15, 0xb2, 0x2a, 0x25, 0x27, 0x2e, 0x21, 0x64, 0xab, 0x9c, 0xf3, 0x8b, 0x4b, 0x82, 0x02,
	0x85, 0x74, 0xb8, 0xd8, 0x32, 0x52, 0x13, 0x53, 0x52, 0x8b, 0x24, 0x18, 0x15, 0x18, 0x35, 0xb8,
	0x8d, 0x44, 0xf4, 0xa0, 0x9a, 0x02, 0x12, 0x93, 0xb3, 0x53, 0x4b, 0x3c, 0xc0, 0x72, 0x41, 0x50,
	0x35, 0x4a, 0xf3, 0x19, 0xb1, 0x18, 0x12, 0x2c, 0x64, 0xc8, 0xc5, 0x91, 0x5a, 0x54, 0x14, 0x9f,
	0x99, 0x97, 0x96, 0x0f, 0x35, 0x46, 0x4c, 0x0f, 0xd9, 0x23, 0xae, 0x45, 0x45, 0xf9, 0x45, 0x9e,
	0x79, 0x69, 0xf9, 0x41, 0xec, 0xa9, 0x45, 0x60, 0x06, 0x92, 0xbd, 0x4c, 0x84, 0xed, 0x15, 0xd2,
	0xe0, 0x62, 0x49, 0xce, 0x2f, 0x2e, 0x91, 0x60, 0x56, 0x60, 0x06, 0xab, 0x45, 0xf2, 0x1c, 0x88,
	0xe9, 0x59, 0x92, 0x9a, 0x1b, 0x04, 0x56, 0xa1, 0x94, 0xc1, 0xc5, 0x87, 0xec, 0x40, 0x52, 0x7d,
	0x08, 0xb7, 0x89, 0x89, 0xa0, 0x4d, 0x73, 0x19, 0xd1, 0xac, 0xa2, 0x43, 0x38, 0x68, 0x71, 0xb1,
	0xa6, 0x82, 0xac, 0xc3, 0x1b, 0x10, 0x10, 0x25, 0x80, 0x00, 0x00, 0x00, 0xff, 0xff, 0xbe, 0x7d,
	0x2b, 0xb7, 0x81, 0x02, 0x00, 0x00,
}
