// Code generated by protoc-gen-go.
// source: paipai_world/common/AlterUserInfo.proto
// DO NOT EDIT!

/*
Package AlterUserInfo is a generated protocol buffer package.

It is generated from these files:
	paipai_world/common/AlterUserInfo.proto

It has these top-level messages:
	UserInfo
	QueryUserInfoRQ
	QueryUserInfoRS
	AlterUserInfoRQ
	AlterUserInfoRS
*/
package AlterUserInfo

import proto "gitlab.ifreetalk.com/plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"
import MessageType "gitlab.ifreetalk.com/plate/protodef/MessageType"
import Common "gitlab.ifreetalk.com/plate/protodef/Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserInfo struct {
	UserId           *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	NickName         *string `protobuf:"bytes,2,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Sex              *int32  `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	IconToken        *int32  `protobuf:"varint,4,opt,name=icon_token,json=iconToken" json:"icon_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserInfo) Reset()                    { *m = UserInfo{} }
func (m *UserInfo) String() string            { return proto.CompactTextString(m) }
func (*UserInfo) ProtoMessage()               {}
func (*UserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserInfo) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserInfo) GetNickName() string {
	if m != nil && m.NickName != nil {
		return *m.NickName
	}
	return ""
}

func (m *UserInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *UserInfo) GetIconToken() int32 {
	if m != nil && m.IconToken != nil {
		return *m.IconToken
	}
	return 0
}

// ## 10481 UN_TCP_PACK_CLI_QUERY_USER_INFO_RQ
// 查询用户资料请求包
type QueryUserInfoRQ struct {
	Header           *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           []uint64             `protobuf:"varint,2,rep,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *QueryUserInfoRQ) Reset()                    { *m = QueryUserInfoRQ{} }
func (m *QueryUserInfoRQ) String() string            { return proto.CompactTextString(m) }
func (*QueryUserInfoRQ) ProtoMessage()               {}
func (*QueryUserInfoRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *QueryUserInfoRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryUserInfoRQ) GetUserId() []uint64 {
	if m != nil {
		return m.UserId
	}
	return nil
}

// ## 10482 UN_TCP_PACK_CLI_QUERY_USER_INFO_RS
// 查询用户资料应答包
type QueryUserInfoRS struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserInfo         []*UserInfo            `protobuf:"bytes,3,rep,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *QueryUserInfoRS) Reset()                    { *m = QueryUserInfoRS{} }
func (m *QueryUserInfoRS) String() string            { return proto.CompactTextString(m) }
func (*QueryUserInfoRS) ProtoMessage()               {}
func (*QueryUserInfoRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *QueryUserInfoRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *QueryUserInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *QueryUserInfoRS) GetUserInfo() []*UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

// ## 10483 UN_TCP_PACK_CLI_ALTER_USER_INFO_RQ
// 修改用户资料请求包
type AlterUserInfoRQ struct {
	Header           *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	AlterInfo        *UserInfo            `protobuf:"bytes,2,opt,name=alter_info,json=alterInfo" json:"alter_info,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *AlterUserInfoRQ) Reset()                    { *m = AlterUserInfoRQ{} }
func (m *AlterUserInfoRQ) String() string            { return proto.CompactTextString(m) }
func (*AlterUserInfoRQ) ProtoMessage()               {}
func (*AlterUserInfoRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *AlterUserInfoRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AlterUserInfoRQ) GetAlterInfo() *UserInfo {
	if m != nil {
		return m.AlterInfo
	}
	return nil
}

// ## 10484 UN_TCP_PACK_CLI_ALTER_USER_INFO_RS
// 修改用户资料应答包
type AlterUserInfoRS struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserInfo         *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *AlterUserInfoRS) Reset()                    { *m = AlterUserInfoRS{} }
func (m *AlterUserInfoRS) String() string            { return proto.CompactTextString(m) }
func (*AlterUserInfoRS) ProtoMessage()               {}
func (*AlterUserInfoRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *AlterUserInfoRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *AlterUserInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *AlterUserInfoRS) GetUserInfo() *UserInfo {
	if m != nil {
		return m.UserInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*UserInfo)(nil), "AlterUserInfo.UserInfo")
	proto.RegisterType((*QueryUserInfoRQ)(nil), "AlterUserInfo.QueryUserInfoRQ")
	proto.RegisterType((*QueryUserInfoRS)(nil), "AlterUserInfo.QueryUserInfoRS")
	proto.RegisterType((*AlterUserInfoRQ)(nil), "AlterUserInfo.AlterUserInfoRQ")
	proto.RegisterType((*AlterUserInfoRS)(nil), "AlterUserInfo.AlterUserInfoRS")
}

func init() { proto.RegisterFile("paipai_world/common/AlterUserInfo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x14, 0x24, 0x4d, 0x6d, 0x93, 0x57, 0xa4, 0x1a, 0xc4, 0x86, 0x8a, 0x10, 0x72, 0x31, 0x07, 0x49,
	0xb1, 0x88, 0x77, 0x11, 0xc1, 0x1e, 0x14, 0x1b, 0x2b, 0x78, 0x0b, 0x4b, 0xf2, 0xaa, 0xa1, 0xcd,
	0x6e, 0x7c, 0x49, 0xa9, 0xfd, 0x23, 0x3f, 0x53, 0x76, 0xd3, 0x6a, 0x22, 0x0a, 0xf6, 0xe2, 0x29,
	0x2f, 0xf3, 0x66, 0x67, 0x66, 0x67, 0xe1, 0x24, 0x63, 0x49, 0xc6, 0x92, 0x70, 0x29, 0x68, 0x1e,
	0x0f, 0x22, 0x91, 0xa6, 0x82, 0x0f, 0x2e, 0xe7, 0x05, 0xd2, 0x63, 0x8e, 0x34, 0xe2, 0x53, 0xe1,
	0x67, 0x24, 0x0a, 0x61, 0xed, 0xd6, 0xc0, 0xfe, 0xfe, 0x2d, 0xe6, 0x39, 0x7b, 0xc6, 0xc9, 0x2a,
	0xc3, 0x92, 0xd1, 0x77, 0x7e, 0x92, 0xba, 0x52, 0x9f, 0x92, 0xe1, 0xbe, 0x82, 0xb1, 0x11, 0xb0,
	0x7a, 0xd0, 0x5e, 0xe4, 0x48, 0x61, 0x12, 0xdb, 0x9a, 0xa3, 0x79, 0xcd, 0xa0, 0x25, 0x7f, 0x47,
	0xb1, 0x75, 0x04, 0x26, 0x4f, 0xa2, 0x59, 0xc8, 0x59, 0x8a, 0x76, 0xc3, 0xd1, 0x3c, 0x33, 0x30,
	0x24, 0x70, 0xc7, 0x52, 0xb4, 0xf6, 0x40, 0xcf, 0xf1, 0xcd, 0xd6, 0x1d, 0xcd, 0xdb, 0x09, 0xe4,
	0x68, 0x1d, 0x03, 0x24, 0x91, 0xe0, 0x61, 0x21, 0x66, 0xc8, 0xed, 0xa6, 0x5a, 0x98, 0x12, 0x99,
	0x48, 0xc0, 0x7d, 0x82, 0xee, 0x78, 0x81, 0xb4, 0xda, 0xf8, 0x06, 0x63, 0xeb, 0x14, 0x5a, 0x2f,
	0xc8, 0x62, 0x24, 0x65, 0xdc, 0x19, 0x1e, 0xf8, 0xeb, 0x90, 0xf7, 0x2c, 0x9a, 0x61, 0x71, 0xa3,
	0x76, 0xc1, 0x9a, 0x53, 0xcd, 0xd9, 0x70, 0xf4, 0xaf, 0x9c, 0xee, 0xbb, 0xf6, 0x5d, 0xfa, 0x61,
	0x4b, 0xe9, 0x33, 0x30, 0x90, 0x28, 0x4c, 0xf8, 0x54, 0xa8, 0x8b, 0x76, 0x86, 0x87, 0x7e, 0xb5,
	0xd6, 0x6b, 0x22, 0x51, 0x2a, 0xb7, 0x91, 0xca, 0xd6, 0xce, 0xc1, 0x2c, 0xd3, 0xc8, 0x33, 0xba,
	0xa3, 0x7b, 0x9d, 0x61, 0xcf, 0xaf, 0x3f, 0xd7, 0x67, 0x1c, 0x63, 0xb1, 0x9e, 0xdc, 0x25, 0x74,
	0x6b, 0x9c, 0xad, 0x4b, 0xb8, 0x00, 0x60, 0x52, 0xa0, 0x9a, 0xf5, 0x57, 0x5f, 0x53, 0x51, 0x95,
	0xb1, 0xec, 0xa8, 0xee, 0xfc, 0xff, 0x1d, 0x69, 0x7f, 0xea, 0xe8, 0x23, 0x00, 0x00, 0xff, 0xff,
	0x89, 0x6e, 0x27, 0x2c, 0x09, 0x03, 0x00, 0x00,
}
