// Code generated by protoc-gen-go.
// source: paipai_world/server/MazeCommonValueSvr.proto
// DO NOT EDIT!

/*
Package MazeCommonValueSvr is a generated protocol buffer package.

It is generated from these files:
	paipai_world/server/MazeCommonValueSvr.proto

It has these top-level messages:
	MazeCommonValueQueryRQ
	MazeCommonValueQueryRS
	MazeCommonValueAddRQ
	MazeCommonValueAddRS
	MazeCommonValueSubRQ
	MazeCommonValueSubRS
	MazeCommonValueSetRQ
	MazeCommonValueSetRS
*/
package MazeCommonValueSvr

import proto "gitlab.ifreetalk.com/maze-plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"
import MazeCommon "gitlab.ifreetalk.com/maze-plate/protodef/MazeCommon"
import Common "gitlab.ifreetalk.com/maze-plate/protodef/Common"
import MessageType "gitlab.ifreetalk.com/maze-plate/protodef/MessageType"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ## 100018	UN_RPC_PACK_MAZE_COMMON_VALUE_QUERY_RQ
// 迷宫通用数值查询请求包
type MazeCommonValueQueryRQ struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	QueryItems       []*MazeCommon.MazeItem `protobuf:"bytes,3,rep,name=query_items,json=queryItems" json:"query_items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueQueryRQ) Reset()                    { *m = MazeCommonValueQueryRQ{} }
func (m *MazeCommonValueQueryRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueQueryRQ) ProtoMessage()               {}
func (*MazeCommonValueQueryRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MazeCommonValueQueryRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueQueryRQ) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueQueryRQ) GetQueryItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.QueryItems
	}
	return nil
}

// ## 100019	UN_RPC_PACK_MAZE_COMMON_VALUE_QUERY_RS
// 迷宫通用数值查询响应包
type MazeCommonValueQueryRS struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserId           *uint64                `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Items            []*MazeCommon.MazeItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueQueryRS) Reset()                    { *m = MazeCommonValueQueryRS{} }
func (m *MazeCommonValueQueryRS) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueQueryRS) ProtoMessage()               {}
func (*MazeCommonValueQueryRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MazeCommonValueQueryRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueQueryRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *MazeCommonValueQueryRS) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueQueryRS) GetItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// ## 100020	UN_RPC_PACK_MAZE_COMMON_VALUE_ADD_RQ
// 迷宫通用数值添加请求包
type MazeCommonValueAddRQ struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	AddItems         []*MazeCommon.MazeItem `protobuf:"bytes,3,rep,name=add_items,json=addItems" json:"add_items,omitempty"`
	OpType           *int32                 `protobuf:"varint,4,opt,name=op_type,json=opType" json:"op_type,omitempty"`
	TradeNumber      *uint64                `protobuf:"varint,5,opt,name=trade_number,json=tradeNumber" json:"trade_number,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueAddRQ) Reset()                    { *m = MazeCommonValueAddRQ{} }
func (m *MazeCommonValueAddRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueAddRQ) ProtoMessage()               {}
func (*MazeCommonValueAddRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MazeCommonValueAddRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueAddRQ) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueAddRQ) GetAddItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.AddItems
	}
	return nil
}

func (m *MazeCommonValueAddRQ) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *MazeCommonValueAddRQ) GetTradeNumber() uint64 {
	if m != nil && m.TradeNumber != nil {
		return *m.TradeNumber
	}
	return 0
}

// ## 100021	UN_RPC_PACK_MAZE_COMMON_VALUE_ADD_RS
// 迷宫通用数值添加响应包
type MazeCommonValueAddRS struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserId           *uint64                `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Items            []*MazeCommon.MazeItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueAddRS) Reset()                    { *m = MazeCommonValueAddRS{} }
func (m *MazeCommonValueAddRS) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueAddRS) ProtoMessage()               {}
func (*MazeCommonValueAddRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MazeCommonValueAddRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueAddRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *MazeCommonValueAddRS) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueAddRS) GetItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// ## 100022	UN_RPC_PACK_MAZE_COMMON_VALUE_SUB_RQ
// 迷宫通用数值扣除请求包
type MazeCommonValueSubRQ struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SubItems         []*MazeCommon.MazeItem `protobuf:"bytes,3,rep,name=sub_items,json=subItems" json:"sub_items,omitempty"`
	OpType           *int32                 `protobuf:"varint,4,opt,name=op_type,json=opType" json:"op_type,omitempty"`
	TradeNumber      *uint64                `protobuf:"varint,5,opt,name=trade_number,json=tradeNumber" json:"trade_number,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueSubRQ) Reset()                    { *m = MazeCommonValueSubRQ{} }
func (m *MazeCommonValueSubRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueSubRQ) ProtoMessage()               {}
func (*MazeCommonValueSubRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *MazeCommonValueSubRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueSubRQ) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueSubRQ) GetSubItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.SubItems
	}
	return nil
}

func (m *MazeCommonValueSubRQ) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *MazeCommonValueSubRQ) GetTradeNumber() uint64 {
	if m != nil && m.TradeNumber != nil {
		return *m.TradeNumber
	}
	return 0
}

// ## 100023	UN_RPC_PACK_MAZE_COMMON_VALUE_SUB_RS
// 迷宫通用数值扣除响应包
type MazeCommonValueSubRS struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserId           *uint64                `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Items            []*MazeCommon.MazeItem `protobuf:"bytes,4,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueSubRS) Reset()                    { *m = MazeCommonValueSubRS{} }
func (m *MazeCommonValueSubRS) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueSubRS) ProtoMessage()               {}
func (*MazeCommonValueSubRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *MazeCommonValueSubRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueSubRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *MazeCommonValueSubRS) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueSubRS) GetItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// ## 100024	UN_RPC_PACK_MAZE_COMMON_VALUE_SET_RQ
// 迷宫通用数值设置请求包
type MazeCommonValueSetRQ struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId           *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	SetItems         []*MazeCommon.MazeItem `protobuf:"bytes,3,rep,name=set_items,json=setItems" json:"set_items,omitempty"`
	OpType           *int32                 `protobuf:"varint,4,opt,name=op_type,json=opType" json:"op_type,omitempty"`
	TradeNumber      *uint64                `protobuf:"varint,5,opt,name=trade_number,json=tradeNumber" json:"trade_number,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueSetRQ) Reset()                    { *m = MazeCommonValueSetRQ{} }
func (m *MazeCommonValueSetRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueSetRQ) ProtoMessage()               {}
func (*MazeCommonValueSetRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *MazeCommonValueSetRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueSetRQ) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *MazeCommonValueSetRQ) GetSetItems() []*MazeCommon.MazeItem {
	if m != nil {
		return m.SetItems
	}
	return nil
}

func (m *MazeCommonValueSetRQ) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *MazeCommonValueSetRQ) GetTradeNumber() uint64 {
	if m != nil && m.TradeNumber != nil {
		return *m.TradeNumber
	}
	return 0
}

// ## 100025	UN_RPC_PACK_MAZE_COMMON_VALUE_SET_RS
// 迷宫通用数值设置响应包
type MazeCommonValueSetRS struct {
	Header           *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeCommonValueSetRS) Reset()                    { *m = MazeCommonValueSetRS{} }
func (m *MazeCommonValueSetRS) String() string            { return proto.CompactTextString(m) }
func (*MazeCommonValueSetRS) ProtoMessage()               {}
func (*MazeCommonValueSetRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *MazeCommonValueSetRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeCommonValueSetRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*MazeCommonValueQueryRQ)(nil), "MazeCommonValueSvr.MazeCommonValueQueryRQ")
	proto.RegisterType((*MazeCommonValueQueryRS)(nil), "MazeCommonValueSvr.MazeCommonValueQueryRS")
	proto.RegisterType((*MazeCommonValueAddRQ)(nil), "MazeCommonValueSvr.MazeCommonValueAddRQ")
	proto.RegisterType((*MazeCommonValueAddRS)(nil), "MazeCommonValueSvr.MazeCommonValueAddRS")
	proto.RegisterType((*MazeCommonValueSubRQ)(nil), "MazeCommonValueSvr.MazeCommonValueSubRQ")
	proto.RegisterType((*MazeCommonValueSubRS)(nil), "MazeCommonValueSvr.MazeCommonValueSubRS")
	proto.RegisterType((*MazeCommonValueSetRQ)(nil), "MazeCommonValueSvr.MazeCommonValueSetRQ")
	proto.RegisterType((*MazeCommonValueSetRS)(nil), "MazeCommonValueSvr.MazeCommonValueSetRS")
}

func init() { proto.RegisterFile("paipai_world/server/MazeCommonValueSvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 382 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x91, 0xcf, 0x4e, 0xea, 0x40,
	0x14, 0xc6, 0xd3, 0xcb, 0xdf, 0x3b, 0xbd, 0x9b, 0xdb, 0x10, 0x6c, 0x58, 0xd5, 0xc6, 0x05, 0x31,
	0x04, 0x02, 0x89, 0x0f, 0x60, 0x8c, 0x89, 0x2c, 0x30, 0x52, 0x8c, 0xdb, 0x66, 0xca, 0x1c, 0xb4,
	0x91, 0x76, 0xea, 0x99, 0x29, 0x04, 0x1f, 0xc4, 0xa7, 0x31, 0x3e, 0x81, 0x0f, 0x65, 0x66, 0xca,
	0xa2, 0x20, 0x1a, 0x8c, 0xb0, 0x60, 0x77, 0x7a, 0xce, 0xe9, 0x37, 0xe7, 0xfb, 0x7e, 0xa4, 0x95,
	0xd0, 0x30, 0xa1, 0xa1, 0x3f, 0xe7, 0x38, 0x65, 0x1d, 0x01, 0x38, 0x03, 0xec, 0x0c, 0xe8, 0x33,
	0x5c, 0xf0, 0x28, 0xe2, 0xf1, 0x1d, 0x9d, 0xa6, 0x30, 0x9a, 0x61, 0x3b, 0x41, 0x2e, 0xb9, 0x65,
	0x7d, 0x9e, 0x34, 0x4e, 0x56, 0x14, 0xc6, 0x7a, 0x98, 0x53, 0xc8, 0xfe, 0x6c, 0x38, 0x9b, 0xb6,
	0x56, 0x36, 0xfe, 0x0f, 0x40, 0x08, 0x7a, 0x0f, 0xb7, 0x8b, 0x04, 0xb2, 0x96, 0xfb, 0x62, 0x90,
	0xfa, 0xda, 0x8b, 0xc3, 0x14, 0x70, 0xe1, 0x0d, 0xad, 0x16, 0x29, 0x3f, 0x00, 0x65, 0x80, 0xb6,
	0xe1, 0x18, 0x4d, 0xb3, 0x57, 0x6b, 0x2f, 0xc5, 0x6e, 0xe8, 0xf8, 0x11, 0xe4, 0x95, 0x9e, 0x79,
	0xcb, 0x1d, 0xeb, 0x88, 0x54, 0x52, 0x01, 0xe8, 0x87, 0xcc, 0xfe, 0xe3, 0x18, 0xcd, 0xa2, 0x57,
	0x56, 0x9f, 0x7d, 0x66, 0x9d, 0x11, 0xf3, 0x49, 0x29, 0xfa, 0xa1, 0x84, 0x48, 0xd8, 0x05, 0xa7,
	0xa0, 0xb5, 0x72, 0xe7, 0xab, 0xb2, 0x2f, 0x21, 0xf2, 0x88, 0x5e, 0x54, 0xa5, 0x70, 0xdf, 0xbe,
	0x3a, 0x6c, 0xf4, 0xc3, 0xc3, 0xba, 0xa4, 0x0a, 0x88, 0x7e, 0x18, 0x4f, 0xb8, 0xbe, 0xcc, 0xec,
	0xd5, 0xdb, 0xf9, 0x1c, 0x2e, 0x11, 0x39, 0xf6, 0xe3, 0x09, 0xf7, 0x2a, 0x80, 0xba, 0xc8, 0x7b,
	0x29, 0xac, 0x78, 0x39, 0x25, 0xa5, 0xcc, 0x45, 0xf1, 0x1b, 0x17, 0xd9, 0x8a, 0xfb, 0x6e, 0x90,
	0xda, 0x9a, 0x81, 0x73, 0xc6, 0x76, 0x97, 0x6b, 0x97, 0xfc, 0xa5, 0x8c, 0x6d, 0x91, 0x6a, 0x95,
	0x32, 0xa6, 0x33, 0x55, 0x5a, 0x3c, 0xf1, 0xe5, 0x22, 0x01, 0xbb, 0xe8, 0x18, 0xcd, 0x92, 0x57,
	0xe6, 0x89, 0xca, 0xc0, 0x3a, 0x26, 0xff, 0x24, 0x52, 0x06, 0x7e, 0x9c, 0x46, 0x01, 0xa0, 0x5d,
	0xd2, 0x2f, 0x99, 0xba, 0x77, 0xad, 0x5b, 0xee, 0xeb, 0x66, 0x3b, 0x07, 0x4c, 0x63, 0x94, 0x06,
	0x3b, 0xa5, 0x21, 0xd2, 0x60, 0x1b, 0x1a, 0x22, 0x0d, 0xf6, 0x42, 0x43, 0xd9, 0x39, 0x64, 0x1a,
	0x20, 0x77, 0x4b, 0x03, 0xe4, 0x56, 0x34, 0x40, 0xfe, 0x9e, 0xc6, 0x7c, 0xa3, 0x9b, 0xfd, 0xc3,
	0xf8, 0x08, 0x00, 0x00, 0xff, 0xff, 0x1e, 0x14, 0x90, 0x46, 0x5b, 0x06, 0x00, 0x00,
}
