// 人偶属性预览

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: server/MazeAttrCalcSvr.proto

package MazeAttrCalcSvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	MessageType "maze_game_server/pb/common/MessageType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PreviewAttr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrId  *int32 `protobuf:"varint,1,opt,name=attr_id,json=attrId" json:"attr_id,omitempty"`    //属性Id
	AttrVal *int64 `protobuf:"varint,2,opt,name=attr_val,json=attrVal" json:"attr_val,omitempty"` //属性值
}

func (x *PreviewAttr) Reset() {
	*x = PreviewAttr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewAttr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewAttr) ProtoMessage() {}

func (x *PreviewAttr) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewAttr.ProtoReflect.Descriptor instead.
func (*PreviewAttr) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{0}
}

func (x *PreviewAttr) GetAttrId() int32 {
	if x != nil && x.AttrId != nil {
		return *x.AttrId
	}
	return 0
}

func (x *PreviewAttr) GetAttrVal() int64 {
	if x != nil && x.AttrVal != nil {
		return *x.AttrVal
	}
	return 0
}

type PreviewParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviewId    *int64         `protobuf:"varint,1,opt,name=preview_id,json=previewId" json:"preview_id,omitempty"`         // 预览Id
	ReplaceAttrs []*PreviewAttr `protobuf:"bytes,2,rep,name=replace_attrs,json=replaceAttrs" json:"replace_attrs,omitempty"` // 替换的属性
}

func (x *PreviewParam) Reset() {
	*x = PreviewParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewParam) ProtoMessage() {}

func (x *PreviewParam) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewParam.ProtoReflect.Descriptor instead.
func (*PreviewParam) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{1}
}

func (x *PreviewParam) GetPreviewId() int64 {
	if x != nil && x.PreviewId != nil {
		return *x.PreviewId
	}
	return 0
}

func (x *PreviewParam) GetReplaceAttrs() []*PreviewAttr {
	if x != nil {
		return x.ReplaceAttrs
	}
	return nil
}

type PreviewResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviewId *int64         `protobuf:"varint,1,opt,name=preview_id,json=previewId" json:"preview_id,omitempty"` // 预览Id
	Result    []*PreviewAttr `protobuf:"bytes,2,rep,name=result" json:"result,omitempty"`                         // 预览结果
}

func (x *PreviewResult) Reset() {
	*x = PreviewResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PreviewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewResult) ProtoMessage() {}

func (x *PreviewResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewResult.ProtoReflect.Descriptor instead.
func (*PreviewResult) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{2}
}

func (x *PreviewResult) GetPreviewId() int64 {
	if x != nil && x.PreviewId != nil {
		return *x.PreviewId
	}
	return 0
}

func (x *PreviewResult) GetResult() []*PreviewAttr {
	if x != nil {
		return x.Result
	}
	return nil
}

type PairPreviewParam struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviewId     *int64         `protobuf:"varint,1,opt,name=preview_id,json=previewId" json:"preview_id,omitempty"`            // 预览Id
	ReplaceAttrs1 []*PreviewAttr `protobuf:"bytes,2,rep,name=replace_attrs1,json=replaceAttrs1" json:"replace_attrs1,omitempty"` // 替换的属性1
	ReplaceAttrs2 []*PreviewAttr `protobuf:"bytes,3,rep,name=replace_attrs2,json=replaceAttrs2" json:"replace_attrs2,omitempty"` // 替换的属性2
}

func (x *PairPreviewParam) Reset() {
	*x = PairPreviewParam{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairPreviewParam) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairPreviewParam) ProtoMessage() {}

func (x *PairPreviewParam) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairPreviewParam.ProtoReflect.Descriptor instead.
func (*PairPreviewParam) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{3}
}

func (x *PairPreviewParam) GetPreviewId() int64 {
	if x != nil && x.PreviewId != nil {
		return *x.PreviewId
	}
	return 0
}

func (x *PairPreviewParam) GetReplaceAttrs1() []*PreviewAttr {
	if x != nil {
		return x.ReplaceAttrs1
	}
	return nil
}

func (x *PairPreviewParam) GetReplaceAttrs2() []*PreviewAttr {
	if x != nil {
		return x.ReplaceAttrs2
	}
	return nil
}

type PairPreviewResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PreviewId *int64         `protobuf:"varint,1,opt,name=preview_id,json=previewId" json:"preview_id,omitempty"` // 预览Id
	Result1   []*PreviewAttr `protobuf:"bytes,2,rep,name=result1" json:"result1,omitempty"`                       // 预览结果1
	Result2   []*PreviewAttr `protobuf:"bytes,3,rep,name=result2" json:"result2,omitempty"`                       // 预览结果2
}

func (x *PairPreviewResult) Reset() {
	*x = PairPreviewResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PairPreviewResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PairPreviewResult) ProtoMessage() {}

func (x *PairPreviewResult) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PairPreviewResult.ProtoReflect.Descriptor instead.
func (*PairPreviewResult) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{4}
}

func (x *PairPreviewResult) GetPreviewId() int64 {
	if x != nil && x.PreviewId != nil {
		return *x.PreviewId
	}
	return 0
}

func (x *PairPreviewResult) GetResult1() []*PreviewAttr {
	if x != nil {
		return x.Result1
	}
	return nil
}

func (x *PairPreviewResult) GetResult2() []*PreviewAttr {
	if x != nil {
		return x.Result2
	}
	return nil
}

//## 100000	UN_RPC_PACK_MAZE_ATTR_PREVIEW_RQ	迷宫属性预览请求
type MazeAttrPreviewRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        *uint64         `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`                     // 用户id
	AttrSrc       *int32          `protobuf:"varint,2,opt,name=AttrSrc" json:"AttrSrc,omitempty"`                                 // 属性来源
	CareAttrs     []int32         `protobuf:"varint,3,rep,name=CareAttrs" json:"CareAttrs,omitempty"`                             // 关心的属性
	PreviewParams []*PreviewParam `protobuf:"bytes,4,rep,name=preview_params,json=previewParams" json:"preview_params,omitempty"` // 预览数据
}

func (x *MazeAttrPreviewRQ) Reset() {
	*x = MazeAttrPreviewRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeAttrPreviewRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeAttrPreviewRQ) ProtoMessage() {}

func (x *MazeAttrPreviewRQ) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeAttrPreviewRQ.ProtoReflect.Descriptor instead.
func (*MazeAttrPreviewRQ) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{5}
}

func (x *MazeAttrPreviewRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *MazeAttrPreviewRQ) GetAttrSrc() int32 {
	if x != nil && x.AttrSrc != nil {
		return *x.AttrSrc
	}
	return 0
}

func (x *MazeAttrPreviewRQ) GetCareAttrs() []int32 {
	if x != nil {
		return x.CareAttrs
	}
	return nil
}

func (x *MazeAttrPreviewRQ) GetPreviewParams() []*PreviewParam {
	if x != nil {
		return x.PreviewParams
	}
	return nil
}

//## 100001	UN_RPC_PACK_MAZE_ATTR_PREVIEW_RS	迷宫属性预览应答
type MazeAttrPreviewRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo       *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`                   // 错误信息
	PreviewResult []*PreviewResult       `protobuf:"bytes,2,rep,name=preview_result,json=previewResult" json:"preview_result,omitempty"` // 预览结果
}

func (x *MazeAttrPreviewRS) Reset() {
	*x = MazeAttrPreviewRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeAttrPreviewRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeAttrPreviewRS) ProtoMessage() {}

func (x *MazeAttrPreviewRS) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeAttrPreviewRS.ProtoReflect.Descriptor instead.
func (*MazeAttrPreviewRS) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{6}
}

func (x *MazeAttrPreviewRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *MazeAttrPreviewRS) GetPreviewResult() []*PreviewResult {
	if x != nil {
		return x.PreviewResult
	}
	return nil
}

//## 100002	UN_RPC_PACK_MAZE_ATTR_PAIR_PREVIEW_RQ	迷宫属性成对预览请求
type MazeAttrPairPreviewRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId        *uint64             `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`                     // 用户id
	AttrSrc       *int32              `protobuf:"varint,2,opt,name=AttrSrc" json:"AttrSrc,omitempty"`                                 // 属性来源
	CareAttrs     []int32             `protobuf:"varint,3,rep,name=CareAttrs" json:"CareAttrs,omitempty"`                             // 关心的属性
	PreviewParams []*PairPreviewParam `protobuf:"bytes,4,rep,name=preview_params,json=previewParams" json:"preview_params,omitempty"` // 预览数据
}

func (x *MazeAttrPairPreviewRQ) Reset() {
	*x = MazeAttrPairPreviewRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeAttrPairPreviewRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeAttrPairPreviewRQ) ProtoMessage() {}

func (x *MazeAttrPairPreviewRQ) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeAttrPairPreviewRQ.ProtoReflect.Descriptor instead.
func (*MazeAttrPairPreviewRQ) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{7}
}

func (x *MazeAttrPairPreviewRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *MazeAttrPairPreviewRQ) GetAttrSrc() int32 {
	if x != nil && x.AttrSrc != nil {
		return *x.AttrSrc
	}
	return 0
}

func (x *MazeAttrPairPreviewRQ) GetCareAttrs() []int32 {
	if x != nil {
		return x.CareAttrs
	}
	return nil
}

func (x *MazeAttrPairPreviewRQ) GetPreviewParams() []*PairPreviewParam {
	if x != nil {
		return x.PreviewParams
	}
	return nil
}

//## 100003	UN_RPC_PACK_MAZE_ATTR_PAIR_PREVIEW_RS	迷宫属性成对预览应答
type MazeAttrPairPreviewRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo       *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`                   // 错误信息
	PreviewResult []*PairPreviewResult   `protobuf:"bytes,2,rep,name=preview_result,json=previewResult" json:"preview_result,omitempty"` // 预览结果
}

func (x *MazeAttrPairPreviewRS) Reset() {
	*x = MazeAttrPairPreviewRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeAttrPairPreviewRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeAttrPairPreviewRS) ProtoMessage() {}

func (x *MazeAttrPairPreviewRS) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeAttrCalcSvr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeAttrPairPreviewRS.ProtoReflect.Descriptor instead.
func (*MazeAttrPairPreviewRS) Descriptor() ([]byte, []int) {
	return file_server_MazeAttrCalcSvr_proto_rawDescGZIP(), []int{8}
}

func (x *MazeAttrPairPreviewRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *MazeAttrPairPreviewRS) GetPreviewResult() []*PairPreviewResult {
	if x != nil {
		return x.PreviewResult
	}
	return nil
}

var File_server_MazeAttrCalcSvr_proto protoreflect.FileDescriptor

var file_server_MazeAttrCalcSvr_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f,
	0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x1a,
	0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x41, 0x0a, 0x0b, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x41, 0x74, 0x74, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74, 0x74, 0x72, 0x49,
	0x64, 0x12, 0x19, 0x0a, 0x08, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x07, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61, 0x6c, 0x22, 0x70, 0x0a, 0x0c,
	0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1d, 0x0a, 0x0a,
	0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x64, 0x12, 0x41, 0x0a, 0x0d, 0x72,
	0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c,
	0x63, 0x53, 0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x41, 0x74, 0x74, 0x72,
	0x52, 0x0c, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x22, 0x64,
	0x0a, 0x0d, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12,
	0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x64, 0x12, 0x34,
	0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72,
	0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x41, 0x74, 0x74, 0x72, 0x52, 0x06, 0x72, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0xbb, 0x01, 0x0a, 0x10, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65,
	0x76, 0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70,
	0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x64, 0x12, 0x43, 0x0a, 0x0e, 0x72, 0x65, 0x70, 0x6c,
	0x61, 0x63, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x31, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53,
	0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x41, 0x74, 0x74, 0x72, 0x52, 0x0d,
	0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x31, 0x12, 0x43, 0x0a,
	0x0e, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x32, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x41,
	0x74, 0x74, 0x72, 0x52, 0x0d, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x73, 0x32, 0x22, 0xa2, 0x01, 0x0a, 0x11, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x70, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x49, 0x64, 0x12, 0x36, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x31, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41,
	0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69,
	0x65, 0x77, 0x41, 0x74, 0x74, 0x72, 0x52, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x31, 0x12,
	0x36, 0x0a, 0x07, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x1c, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53,
	0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x41, 0x74, 0x74, 0x72, 0x52, 0x07,
	0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x32, 0x22, 0xaa, 0x01, 0x0a, 0x11, 0x4d, 0x61, 0x7a, 0x65,
	0x41, 0x74, 0x74, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x51, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x74, 0x74, 0x72, 0x53, 0x72,
	0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x74, 0x74, 0x72, 0x53, 0x72, 0x63,
	0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x05, 0x52, 0x09, 0x43, 0x61, 0x72, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x44,
	0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d, 0x73,
	0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77,
	0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x61,
	0x72, 0x61, 0x6d, 0x73, 0x22, 0x8d, 0x01, 0x0a, 0x11, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x45, 0x0a,
	0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72,
	0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x2e, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65,
	0x73, 0x75, 0x6c, 0x74, 0x22, 0xb2, 0x01, 0x0a, 0x15, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74,
	0x72, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x51, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x74, 0x74, 0x72, 0x53,
	0x72, 0x63, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x41, 0x74, 0x74, 0x72, 0x53, 0x72,
	0x63, 0x12, 0x1c, 0x0a, 0x09, 0x43, 0x61, 0x72, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x18, 0x03,
	0x20, 0x03, 0x28, 0x05, 0x52, 0x09, 0x43, 0x61, 0x72, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12,
	0x48, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x5f, 0x70, 0x61, 0x72, 0x61, 0x6d,
	0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x21, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74,
	0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0x2e, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72,
	0x65, 0x76, 0x69, 0x65, 0x77, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76,
	0x69, 0x65, 0x77, 0x50, 0x61, 0x72, 0x61, 0x6d, 0x73, 0x22, 0x95, 0x01, 0x0a, 0x15, 0x4d, 0x61,
	0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x49, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65,
	0x77, 0x5f, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x22,
	0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72,
	0x2e, 0x50, 0x61, 0x69, 0x72, 0x50, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x75,
	0x6c, 0x74, 0x52, 0x0d, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x42, 0x41, 0x5a, 0x2a, 0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73,
	0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f,
	0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x76, 0x72, 0xaa,
	0x02, 0x12, 0x50, 0x62, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x74, 0x74, 0x72, 0x43, 0x61, 0x6c,
	0x63, 0x53, 0x76, 0x72,
}

var (
	file_server_MazeAttrCalcSvr_proto_rawDescOnce sync.Once
	file_server_MazeAttrCalcSvr_proto_rawDescData = file_server_MazeAttrCalcSvr_proto_rawDesc
)

func file_server_MazeAttrCalcSvr_proto_rawDescGZIP() []byte {
	file_server_MazeAttrCalcSvr_proto_rawDescOnce.Do(func() {
		file_server_MazeAttrCalcSvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_MazeAttrCalcSvr_proto_rawDescData)
	})
	return file_server_MazeAttrCalcSvr_proto_rawDescData
}

var file_server_MazeAttrCalcSvr_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_server_MazeAttrCalcSvr_proto_goTypes = []interface{}{
	(*PreviewAttr)(nil),           // 0: MazeAttrCalcSvr.PreviewAttr
	(*PreviewParam)(nil),          // 1: MazeAttrCalcSvr.PreviewParam
	(*PreviewResult)(nil),         // 2: MazeAttrCalcSvr.PreviewResult
	(*PairPreviewParam)(nil),      // 3: MazeAttrCalcSvr.PairPreviewParam
	(*PairPreviewResult)(nil),     // 4: MazeAttrCalcSvr.PairPreviewResult
	(*MazeAttrPreviewRQ)(nil),     // 5: MazeAttrCalcSvr.MazeAttrPreviewRQ
	(*MazeAttrPreviewRS)(nil),     // 6: MazeAttrCalcSvr.MazeAttrPreviewRS
	(*MazeAttrPairPreviewRQ)(nil), // 7: MazeAttrCalcSvr.MazeAttrPairPreviewRQ
	(*MazeAttrPairPreviewRS)(nil), // 8: MazeAttrCalcSvr.MazeAttrPairPreviewRS
	(*MessageType.ErrorInfo)(nil), // 9: MessageType.ErrorInfo
}
var file_server_MazeAttrCalcSvr_proto_depIdxs = []int32{
	0,  // 0: MazeAttrCalcSvr.PreviewParam.replace_attrs:type_name -> MazeAttrCalcSvr.PreviewAttr
	0,  // 1: MazeAttrCalcSvr.PreviewResult.result:type_name -> MazeAttrCalcSvr.PreviewAttr
	0,  // 2: MazeAttrCalcSvr.PairPreviewParam.replace_attrs1:type_name -> MazeAttrCalcSvr.PreviewAttr
	0,  // 3: MazeAttrCalcSvr.PairPreviewParam.replace_attrs2:type_name -> MazeAttrCalcSvr.PreviewAttr
	0,  // 4: MazeAttrCalcSvr.PairPreviewResult.result1:type_name -> MazeAttrCalcSvr.PreviewAttr
	0,  // 5: MazeAttrCalcSvr.PairPreviewResult.result2:type_name -> MazeAttrCalcSvr.PreviewAttr
	1,  // 6: MazeAttrCalcSvr.MazeAttrPreviewRQ.preview_params:type_name -> MazeAttrCalcSvr.PreviewParam
	9,  // 7: MazeAttrCalcSvr.MazeAttrPreviewRS.err_info:type_name -> MessageType.ErrorInfo
	2,  // 8: MazeAttrCalcSvr.MazeAttrPreviewRS.preview_result:type_name -> MazeAttrCalcSvr.PreviewResult
	3,  // 9: MazeAttrCalcSvr.MazeAttrPairPreviewRQ.preview_params:type_name -> MazeAttrCalcSvr.PairPreviewParam
	9,  // 10: MazeAttrCalcSvr.MazeAttrPairPreviewRS.err_info:type_name -> MessageType.ErrorInfo
	4,  // 11: MazeAttrCalcSvr.MazeAttrPairPreviewRS.preview_result:type_name -> MazeAttrCalcSvr.PairPreviewResult
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_server_MazeAttrCalcSvr_proto_init() }
func file_server_MazeAttrCalcSvr_proto_init() {
	if File_server_MazeAttrCalcSvr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_MazeAttrCalcSvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewAttr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PreviewResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairPreviewParam); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PairPreviewResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeAttrPreviewRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeAttrPreviewRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeAttrPairPreviewRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeAttrCalcSvr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeAttrPairPreviewRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_MazeAttrCalcSvr_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_MazeAttrCalcSvr_proto_goTypes,
		DependencyIndexes: file_server_MazeAttrCalcSvr_proto_depIdxs,
		MessageInfos:      file_server_MazeAttrCalcSvr_proto_msgTypes,
	}.Build()
	File_server_MazeAttrCalcSvr_proto = out.File
	file_server_MazeAttrCalcSvr_proto_rawDesc = nil
	file_server_MazeAttrCalcSvr_proto_goTypes = nil
	file_server_MazeAttrCalcSvr_proto_depIdxs = nil
}
