# 储存服务需要使用的配置信息
[log] # 日志配置
log_type=zap # 不写默认用ex
with_caller=true # 是否显行号
log_name=maze_sweep_server # 文件名
log_level=all # 打印此级别及以上级别的日志
max_size=300 # 文件存储上限
max_backups=100 # 最大文件数
use_new_rule=true # true 使用时间分隔日志 false 按照以前文件大小分隔日志
minute=30 # 1-60分钟，使用时间分隔日志的单位
MaxAge=7 # 过期时间天

[service] # 服务配置
need_fc_special_svr_id=true
address=5997
address_prot=2 # tcp端口
address_2=5998
address_prot_2=4 # rpc端口
address_3=5999
address_prot_3=8 # http端口