// Code generated by protoc-gen-go.
// source: paipai_world/server/MazeTempBuffSvr.proto
// DO NOT EDIT!

/*
Package MazeTempBuffSvr is a generated protocol buffer package.

It is generated from these files:
	paipai_world/server/MazeTempBuffSvr.proto

It has these top-level messages:
	BuffSequence
	TotalBuffInfo
	SelectedBuffInfo
	TempBuffInfo
*/
package MazeTempBuffSvr

import proto "gitlab.ifreetalk.com/plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// buff序列
type BuffSequence struct {
	Id               *int32  `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`
	Index            *int32  `protobuf:"varint,2,opt,name=index" json:"index,omitempty"`
	RefreshCount     *int32  `protobuf:"varint,3,opt,name=refresh_count,json=refreshCount" json:"refresh_count,omitempty"`
	SelectBuffList   []int32 `protobuf:"varint,4,rep,name=select_buff_list,json=selectBuffList" json:"select_buff_list,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BuffSequence) Reset()                    { *m = BuffSequence{} }
func (m *BuffSequence) String() string            { return proto.CompactTextString(m) }
func (*BuffSequence) ProtoMessage()               {}
func (*BuffSequence) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *BuffSequence) GetId() int32 {
	if m != nil && m.Id != nil {
		return *m.Id
	}
	return 0
}

func (m *BuffSequence) GetIndex() int32 {
	if m != nil && m.Index != nil {
		return *m.Index
	}
	return 0
}

func (m *BuffSequence) GetRefreshCount() int32 {
	if m != nil && m.RefreshCount != nil {
		return *m.RefreshCount
	}
	return 0
}

func (m *BuffSequence) GetSelectBuffList() []int32 {
	if m != nil {
		return m.SelectBuffList
	}
	return nil
}

type TotalBuffInfo struct {
	BuffId           *int32 `protobuf:"varint,1,opt,name=buff_id,json=buffId" json:"buff_id,omitempty"`
	BuffValue        *int64 `protobuf:"varint,2,opt,name=buff_value,json=buffValue" json:"buff_value,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *TotalBuffInfo) Reset()                    { *m = TotalBuffInfo{} }
func (m *TotalBuffInfo) String() string            { return proto.CompactTextString(m) }
func (*TotalBuffInfo) ProtoMessage()               {}
func (*TotalBuffInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *TotalBuffInfo) GetBuffId() int32 {
	if m != nil && m.BuffId != nil {
		return *m.BuffId
	}
	return 0
}

func (m *TotalBuffInfo) GetBuffValue() int64 {
	if m != nil && m.BuffValue != nil {
		return *m.BuffValue
	}
	return 0
}

// 已选择的buff信息
type SelectedBuffInfo struct {
	BuffId           *int32 `protobuf:"varint,1,opt,name=buff_id,json=buffId" json:"buff_id,omitempty"`
	Level            *int32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SelectedBuffInfo) Reset()                    { *m = SelectedBuffInfo{} }
func (m *SelectedBuffInfo) String() string            { return proto.CompactTextString(m) }
func (*SelectedBuffInfo) ProtoMessage()               {}
func (*SelectedBuffInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *SelectedBuffInfo) GetBuffId() int32 {
	if m != nil && m.BuffId != nil {
		return *m.BuffId
	}
	return 0
}

func (m *SelectedBuffInfo) GetLevel() int32 {
	if m != nil && m.Level != nil {
		return *m.Level
	}
	return 0
}

type TempBuffInfo struct {
	BuffSequence     *BuffSequence       `protobuf:"bytes,1,opt,name=buff_sequence,json=buffSequence" json:"buff_sequence,omitempty"`
	TotalBuff        []*TotalBuffInfo    `protobuf:"bytes,2,rep,name=total_buff,json=totalBuff" json:"total_buff,omitempty"`
	SelectedBuff     []*SelectedBuffInfo `protobuf:"bytes,3,rep,name=selected_buff,json=selectedBuff" json:"selected_buff,omitempty"`
	XXX_unrecognized []byte              `json:"-"`
}

func (m *TempBuffInfo) Reset()                    { *m = TempBuffInfo{} }
func (m *TempBuffInfo) String() string            { return proto.CompactTextString(m) }
func (*TempBuffInfo) ProtoMessage()               {}
func (*TempBuffInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *TempBuffInfo) GetBuffSequence() *BuffSequence {
	if m != nil {
		return m.BuffSequence
	}
	return nil
}

func (m *TempBuffInfo) GetTotalBuff() []*TotalBuffInfo {
	if m != nil {
		return m.TotalBuff
	}
	return nil
}

func (m *TempBuffInfo) GetSelectedBuff() []*SelectedBuffInfo {
	if m != nil {
		return m.SelectedBuff
	}
	return nil
}

func init() {
	proto.RegisterType((*BuffSequence)(nil), "MazeTempBuffSvr.BuffSequence")
	proto.RegisterType((*TotalBuffInfo)(nil), "MazeTempBuffSvr.TotalBuffInfo")
	proto.RegisterType((*SelectedBuffInfo)(nil), "MazeTempBuffSvr.SelectedBuffInfo")
	proto.RegisterType((*TempBuffInfo)(nil), "MazeTempBuffSvr.TempBuffInfo")
}

func init() { proto.RegisterFile("paipai_world/server/MazeTempBuffSvr.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 318 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x84, 0x90, 0x41, 0x4b, 0xfb, 0x40,
	0x10, 0xc5, 0x49, 0xf2, 0xcf, 0x5f, 0x3a, 0x4d, 0x6a, 0x59, 0x0a, 0xe6, 0x52, 0xa9, 0xf1, 0x12,
	0x2f, 0x2d, 0xf4, 0xee, 0xc1, 0x0a, 0x4a, 0x41, 0x2f, 0x69, 0xf1, 0x1a, 0xd2, 0x66, 0x82, 0x0b,
	0x6b, 0x36, 0xee, 0x6e, 0xa2, 0x78, 0xf5, 0x53, 0xfa, 0x6d, 0x64, 0xa7, 0xad, 0xd4, 0xf6, 0xe0,
	0x6d, 0xdf, 0x6f, 0x98, 0xb7, 0xf3, 0x1e, 0x5c, 0xd5, 0x39, 0xaf, 0x73, 0x9e, 0xbd, 0x49, 0x25,
	0x8a, 0x89, 0x46, 0xd5, 0xa2, 0x9a, 0x3c, 0xe6, 0x1f, 0xb8, 0xc4, 0x97, 0x7a, 0xd6, 0x94, 0xe5,
	0xa2, 0x55, 0xe3, 0x5a, 0x49, 0x23, 0xd9, 0xe9, 0x01, 0x8e, 0x3f, 0x1d, 0x08, 0xe8, 0x8d, 0xaf,
	0x0d, 0x56, 0x6b, 0x64, 0x3d, 0x70, 0x79, 0x11, 0x39, 0x23, 0x27, 0xf1, 0x53, 0x97, 0x17, 0x6c,
	0x00, 0x3e, 0xaf, 0x0a, 0x7c, 0x8f, 0x5c, 0x42, 0x1b, 0xc1, 0x2e, 0x21, 0x54, 0x58, 0x2a, 0xd4,
	0xcf, 0xd9, 0x5a, 0x36, 0x95, 0x89, 0x3c, 0x9a, 0x06, 0x5b, 0x78, 0x6b, 0x19, 0x4b, 0xa0, 0xaf,
	0x51, 0xe0, 0xda, 0x64, 0xab, 0xa6, 0x2c, 0x33, 0xc1, 0xb5, 0x89, 0xfe, 0x8d, 0xbc, 0xc4, 0x4f,
	0x7b, 0x1b, 0x6e, 0x3f, 0x7e, 0xe0, 0xda, 0xc4, 0xf7, 0x10, 0x2e, 0xa5, 0xc9, 0x85, 0x05, 0xf3,
	0xaa, 0x94, 0xec, 0x0c, 0x4e, 0x68, 0xe7, 0xe7, 0x94, 0xff, 0x56, 0xce, 0x0b, 0x36, 0x04, 0xa0,
	0x41, 0x9b, 0x8b, 0x06, 0xe9, 0x26, 0x2f, 0xed, 0x58, 0xf2, 0x64, 0x41, 0x7c, 0x03, 0xfd, 0x05,
	0x59, 0x63, 0xf1, 0xb7, 0xd7, 0x00, 0x7c, 0x81, 0x2d, 0x8a, 0x5d, 0x34, 0x12, 0xf1, 0x97, 0x03,
	0xc1, 0xae, 0x21, 0xda, 0x9f, 0x41, 0x48, 0xfb, 0x7a, 0x5b, 0x11, 0xb9, 0x74, 0xa7, 0xc3, 0xf1,
	0x61, 0xc5, 0xfb, 0x3d, 0xa6, 0xc1, 0x6a, 0xbf, 0xd5, 0x6b, 0x00, 0x63, 0x03, 0x52, 0x13, 0x91,
	0x3b, 0xf2, 0x92, 0xee, 0xf4, 0xfc, 0xc8, 0xe0, 0x57, 0x07, 0x69, 0xc7, 0xec, 0x24, 0xbb, 0x83,
	0x50, 0x6f, 0x63, 0x6d, 0x1c, 0x3c, 0x72, 0xb8, 0x38, 0x72, 0x38, 0x0c, 0x9f, 0x06, 0x7a, 0x8f,
	0x7c, 0x07, 0x00, 0x00, 0xff, 0xff, 0x2d, 0x81, 0x7d, 0xf7, 0x2a, 0x02, 0x00, 0x00,
}
