mysql_list:
  - name: BizCfg
    user: root
    db: maze
    password: mysql
    sharding_type: 0
    sharding_count: 1
  - name: maze_main_server.mysql
    user: root
    db: maze
    password: mysql
    sharding_type: 0
    sharding_count: 1
