BizCfg:
  addr: "mysql:3306"
  db_user: "root"
  pwd: "mysql"
  db_name: "maze"
  table_name: "test"
Redis:
  addr: "redis:6379"
  pwd: "Redis_Pwd"
Mysql:
  addr: "mysql:3306"
  db_user: "root"
  pwd: "mysql"
  db_name: "maze"
  table_name: "test"
