service:
  - name: BizCfg
    addr: "127.0.0.1:3306"
    tags:
      db_name: maze
      db_user: root
      password: "123456"
      sharding_type: 0
      count: 1
  - name: Redis # the route name of the service.
    addr: "127.0.0.1:6379"
    tags:
      password: ""
  - name: Mysql
    addr: "127.0.0.1:3306"
    tags:
      db_name: maze
      db_user: root
      password: "123456"
      sharding_type: 0
      count: 1
  - name: maze-main-server-dev.gm
    addr: "127.0.0.1:3306"
    tags:
      db_name: maze
  - name: maze_main_server.redis # the route name of the service.
    addr: "127.0.0.1:6379"
    tags:
      password: ""
  - name: user.section.redis
    add: "127.0.0.1:6379"
  - name: maze-game.redis
    add: "127.0.0.1:6379"
  - name: maze_main_server_flow.kafka
    addr: "127.0.0.1:9092"

