// Code generated by protoc-gen-go.
// source: paipai_world/common/LogonPropertyTrigger.proto
// DO NOT EDIT!

/*
Package LogonPropertyTrigger is a generated protocol buffer package.

It is generated from these files:

	paipai_world/common/LogonPropertyTrigger.proto

It has these top-level messages:

	LogonPropertyTriggerRQ
	LogonPropertyTriggerRS
*/
package LogonPropertyTrigger

import proto "gitlab.ifreetalk.com/maze-plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"
import MessageType "gitlab.ifreetalk.com/maze-plate/protodef/MessageType"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ## 1
type LogonPropertyTriggerRQ struct {
	UserId           *uint64 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *LogonPropertyTriggerRQ) Reset()                    { *m = LogonPropertyTriggerRQ{} }
func (m *LogonPropertyTriggerRQ) String() string            { return proto.CompactTextString(m) }
func (*LogonPropertyTriggerRQ) ProtoMessage()               {}
func (*LogonPropertyTriggerRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *LogonPropertyTriggerRQ) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

// ## 2
type LogonPropertyTriggerRS struct {
	UserId           *uint64                `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *LogonPropertyTriggerRS) Reset()                    { *m = LogonPropertyTriggerRS{} }
func (m *LogonPropertyTriggerRS) String() string            { return proto.CompactTextString(m) }
func (*LogonPropertyTriggerRS) ProtoMessage()               {}
func (*LogonPropertyTriggerRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *LogonPropertyTriggerRS) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *LogonPropertyTriggerRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func init() {
	proto.RegisterType((*LogonPropertyTriggerRQ)(nil), "LogonPropertyTrigger.LogonPropertyTriggerRQ")
	proto.RegisterType((*LogonPropertyTriggerRS)(nil), "LogonPropertyTrigger.LogonPropertyTriggerRS")
}

func init() { proto.RegisterFile("paipai_world/common/LogonPropertyTrigger.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 168 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xd2, 0x2b, 0x48, 0xcc, 0x2c,
	0x48, 0xcc, 0x8c, 0x2f, 0xcf, 0x2f, 0xca, 0x49, 0xd1, 0x4f, 0xce, 0xcf, 0xcd, 0xcd, 0xcf, 0xd3,
	0xf7, 0xc9, 0x4f, 0xcf, 0xcf, 0x0b, 0x28, 0xca, 0x2f, 0x48, 0x2d, 0x2a, 0xa9, 0x0c, 0x29, 0xca,
	0x4c, 0x4f, 0x4f, 0x2d, 0xd2, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x12, 0xc1, 0x26, 0x27, 0x25,
	0xe8, 0x9b, 0x5a, 0x5c, 0x9c, 0x98, 0x9e, 0x1a, 0x52, 0x59, 0x90, 0x0a, 0x51, 0xa8, 0x64, 0xc8,
	0x25, 0x86, 0x4d, 0x69, 0x50, 0xa0, 0x90, 0x38, 0x17, 0x7b, 0x69, 0x71, 0x6a, 0x51, 0x7c, 0x66,
	0x8a, 0x04, 0xa3, 0x02, 0x93, 0x06, 0x4b, 0x10, 0x1b, 0x88, 0xeb, 0x99, 0xa2, 0x94, 0x82, 0x43,
	0x4b, 0x30, 0x4e, 0x2d, 0x42, 0x86, 0x5c, 0x1c, 0xa9, 0x45, 0x45, 0xf1, 0x99, 0x79, 0x69, 0xf9,
	0x12, 0x4c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x62, 0x7a, 0xc8, 0x6e, 0x71, 0x2d, 0x2a, 0xca, 0x2f,
	0xf2, 0xcc, 0x4b, 0xcb, 0x0f, 0x62, 0x4f, 0x2d, 0x02, 0x33, 0x00, 0x01, 0x00, 0x00, 0xff, 0xff,
	0x11, 0x4e, 0x1d, 0x26, 0xf2, 0x00, 0x00, 0x00,
}
