[log]
log_type=zap # 不写默认用ex
with_caller=true # 是否显行号
log_level=debug # zap 没有 all,不推荐。最低等级是 debug
max_size=300
max_backups=100
# true 使用时间分隔日志 false 按照以前文件大小分隔日志
use_new_rule=true
# 1-60分钟 使用时间分隔日志的单位
minute=30

[service]
address=5997
address_prot=2
address_2=5998
address_prot_2=4
address_3=5999
address_prot_3=8
need_fc_special_svr_id=true