// Code generated by protoc-gen-go.
// source: paipai_world/common/MazeBag.proto
// DO NOT EDIT!

/*
Package MazeBag is a generated protocol buffer package.

It is generated from these files:
	paipai_world/common/MazeBag.proto

It has these top-level messages:
	MazeBagListRQ
	MazeBagListRS
	MazeBagChgID
	MazeBagItem
	ResetMazeBagRQ
	ResetMazeBagRS
*/
package MazeBag

import proto "gitlab.ifreetalk.com/plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"
import MessageType "gitlab.ifreetalk.com/plate/protodef/MessageType"
import Common "gitlab.ifreetalk.com/plate/protodef/Common"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// ## 10400
// 获取背包列表请求
type MazeBagListRQ struct {
	Header           *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *MazeBagListRQ) Reset()                    { *m = MazeBagListRQ{} }
func (m *MazeBagListRQ) String() string            { return proto.CompactTextString(m) }
func (*MazeBagListRQ) ProtoMessage()               {}
func (*MazeBagListRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MazeBagListRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// ## 10401
// 获取背包列表回复
type MazeBagListRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header           *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Items            []*MazeBagItem         `protobuf:"bytes,3,rep,name=items" json:"items,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *MazeBagListRS) Reset()                    { *m = MazeBagListRS{} }
func (m *MazeBagListRS) String() string            { return proto.CompactTextString(m) }
func (*MazeBagListRS) ProtoMessage()               {}
func (*MazeBagListRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MazeBagListRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *MazeBagListRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func (m *MazeBagListRS) GetItems() []*MazeBagItem {
	if m != nil {
		return m.Items
	}
	return nil
}

// ## 10404
// 迷宫背包物品变化ID包
type MazeBagChgID struct {
	Items            []*MazeBagItem `protobuf:"bytes,1,rep,name=items" json:"items,omitempty"`
	Token            *int64         `protobuf:"varint,2,opt,name=token" json:"token,omitempty"`
	Source           *int32         `protobuf:"varint,3,opt,name=source" json:"source,omitempty"`
	XXX_unrecognized []byte         `json:"-"`
}

func (m *MazeBagChgID) Reset()                    { *m = MazeBagChgID{} }
func (m *MazeBagChgID) String() string            { return proto.CompactTextString(m) }
func (*MazeBagChgID) ProtoMessage()               {}
func (*MazeBagChgID) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *MazeBagChgID) GetItems() []*MazeBagItem {
	if m != nil {
		return m.Items
	}
	return nil
}

func (m *MazeBagChgID) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *MazeBagChgID) GetSource() int32 {
	if m != nil && m.Source != nil {
		return *m.Source
	}
	return 0
}

// 背包道具信息
type MazeBagItem struct {
	ItemId           *int32 `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`
	Count            *int64 `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`
	Quality          *int32 `protobuf:"varint,3,opt,name=quality" json:"quality,omitempty"`
	OrderType        *int32 `protobuf:"varint,4,opt,name=order_type,json=orderType" json:"order_type,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *MazeBagItem) Reset()                    { *m = MazeBagItem{} }
func (m *MazeBagItem) String() string            { return proto.CompactTextString(m) }
func (*MazeBagItem) ProtoMessage()               {}
func (*MazeBagItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *MazeBagItem) GetItemId() int32 {
	if m != nil && m.ItemId != nil {
		return *m.ItemId
	}
	return 0
}

func (m *MazeBagItem) GetCount() int64 {
	if m != nil && m.Count != nil {
		return *m.Count
	}
	return 0
}

func (m *MazeBagItem) GetQuality() int32 {
	if m != nil && m.Quality != nil {
		return *m.Quality
	}
	return 0
}

func (m *MazeBagItem) GetOrderType() int32 {
	if m != nil && m.OrderType != nil {
		return *m.OrderType
	}
	return 0
}

// ## 10402
// 重置迷宫背包请求
type ResetMazeBagRQ struct {
	Header           *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte               `json:"-"`
}

func (m *ResetMazeBagRQ) Reset()                    { *m = ResetMazeBagRQ{} }
func (m *ResetMazeBagRQ) String() string            { return proto.CompactTextString(m) }
func (*ResetMazeBagRQ) ProtoMessage()               {}
func (*ResetMazeBagRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ResetMazeBagRQ) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

// ## 10403
// 重置迷宫背包回复
type ResetMazeBagRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header           *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *ResetMazeBagRS) Reset()                    { *m = ResetMazeBagRS{} }
func (m *ResetMazeBagRS) String() string            { return proto.CompactTextString(m) }
func (*ResetMazeBagRS) ProtoMessage()               {}
func (*ResetMazeBagRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ResetMazeBagRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *ResetMazeBagRS) GetHeader() *Common.PacketHeader {
	if m != nil {
		return m.Header
	}
	return nil
}

func init() {
	proto.RegisterType((*MazeBagListRQ)(nil), "MazeBag.MazeBagListRQ")
	proto.RegisterType((*MazeBagListRS)(nil), "MazeBag.MazeBagListRS")
	proto.RegisterType((*MazeBagChgID)(nil), "MazeBag.MazeBagChgID")
	proto.RegisterType((*MazeBagItem)(nil), "MazeBag.MazeBagItem")
	proto.RegisterType((*ResetMazeBagRQ)(nil), "MazeBag.ResetMazeBagRQ")
	proto.RegisterType((*ResetMazeBagRS)(nil), "MazeBag.ResetMazeBagRS")
}

func init() { proto.RegisterFile("paipai_world/common/MazeBag.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 328 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x51, 0xc1, 0x4a, 0xc3, 0x40,
	0x10, 0x25, 0xc6, 0x34, 0x3a, 0x55, 0xc1, 0xa5, 0xd4, 0x50, 0x10, 0x62, 0x4e, 0x45, 0xa4, 0x45,
	0xef, 0x7a, 0xb0, 0x0a, 0x06, 0x2c, 0xe8, 0xea, 0x3d, 0x2c, 0xc9, 0xb4, 0x5d, 0xda, 0x64, 0xd3,
	0xdd, 0x0d, 0x52, 0xbf, 0xc5, 0x8f, 0x95, 0x6c, 0xb6, 0x58, 0x45, 0x28, 0x1e, 0x3c, 0xed, 0xbe,
	0x99, 0xf7, 0xde, 0x0c, 0x6f, 0xe0, 0xac, 0x64, 0xbc, 0x64, 0x3c, 0x79, 0x13, 0x72, 0x91, 0x0d,
	0x53, 0x91, 0xe7, 0xa2, 0x18, 0x8e, 0xd9, 0x3b, 0xde, 0xb2, 0xe9, 0xa0, 0x94, 0x42, 0x0b, 0xe2,
	0x5b, 0xd8, 0x3b, 0x1e, 0xa3, 0x52, 0x6c, 0x8a, 0xaf, 0xab, 0x12, 0x9b, 0x5e, 0x2f, 0xfc, 0x4d,
	0x3e, 0x32, 0x4f, 0xc3, 0x88, 0xae, 0xe1, 0xd0, 0xea, 0x1f, 0xb9, 0xd2, 0xf4, 0x99, 0x5c, 0x40,
	0x6b, 0x86, 0x2c, 0x43, 0x19, 0x38, 0xa1, 0xd3, 0x6f, 0x5f, 0x75, 0x06, 0x96, 0xff, 0xc4, 0xd2,
	0x39, 0xea, 0x07, 0xd3, 0xa3, 0x96, 0x13, 0x7d, 0x38, 0xdf, 0xf5, 0x2f, 0xe4, 0x12, 0xf6, 0x50,
	0xca, 0x84, 0x17, 0x13, 0x61, 0x1d, 0xba, 0x83, 0xcd, 0xc5, 0xee, 0xa5, 0x14, 0x32, 0x2e, 0x26,
	0x82, 0xfa, 0x28, 0xcd, 0x67, 0x63, 0xe4, 0xce, 0xf6, 0x91, 0xe4, 0x1c, 0x3c, 0xae, 0x31, 0x57,
	0x81, 0x1b, 0xba, 0x86, 0xbc, 0x8e, 0xc3, 0xbe, 0xb1, 0xc6, 0x9c, 0x36, 0x94, 0x68, 0x06, 0x07,
	0xb6, 0x3a, 0x9a, 0x4d, 0xe3, 0xbb, 0x2f, 0xad, 0xb3, 0x55, 0x4b, 0x3a, 0xe0, 0x69, 0x31, 0xc7,
	0xc2, 0x2c, 0xe5, 0xd2, 0x06, 0x90, 0x2e, 0xb4, 0x94, 0xa8, 0x64, 0x8a, 0x81, 0x1b, 0x3a, 0x7d,
	0x8f, 0x5a, 0x14, 0x55, 0xd0, 0xde, 0xf0, 0x20, 0x27, 0xe0, 0xd7, 0x2e, 0x09, 0xcf, 0x4c, 0x08,
	0x1e, 0x6d, 0xd5, 0x30, 0xce, 0x6a, 0xd7, 0x54, 0x54, 0x85, 0x5e, 0xbb, 0x1a, 0x40, 0x02, 0xf0,
	0x97, 0x15, 0x5b, 0x70, 0xbd, 0xb2, 0xb6, 0x6b, 0x48, 0x4e, 0x01, 0x84, 0xcc, 0x50, 0x26, 0x7a,
	0x55, 0x62, 0xb0, 0x6b, 0x9a, 0xfb, 0xa6, 0x52, 0xa7, 0x19, 0xdd, 0xc0, 0x11, 0x45, 0x85, 0xda,
	0xce, 0xfe, 0xf3, 0xfd, 0x96, 0x3f, 0xf4, 0xff, 0x7f, 0xbf, 0xcf, 0x00, 0x00, 0x00, 0xff, 0xff,
	0x74, 0x0a, 0x54, 0x0b, 0xd3, 0x02, 0x00, 0x00,
}
