// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/Friend.proto

package Friend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	Common "maze_game_server/pb/common/Common"
	MessageType "maze_game_server/pb/common/MessageType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//## 10552
//添加好友请求包
type AddFriendRequestRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId *uint64              `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 发送给的用户id
}

func (x *AddFriendRequestRQ) Reset() {
	*x = AddFriendRequestRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendRequestRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequestRQ) ProtoMessage() {}

func (x *AddFriendRequestRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequestRQ.ProtoReflect.Descriptor instead.
func (*AddFriendRequestRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{0}
}

func (x *AddFriendRequestRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AddFriendRequestRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10553
//添加好友响应包
type AddFriendRequestRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header  *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	UserId  *uint64                `protobuf:"varint,3,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 发送给的用户id
}

func (x *AddFriendRequestRS) Reset() {
	*x = AddFriendRequestRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendRequestRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequestRS) ProtoMessage() {}

func (x *AddFriendRequestRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequestRS.ProtoReflect.Descriptor instead.
func (*AddFriendRequestRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{1}
}

func (x *AddFriendRequestRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *AddFriendRequestRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AddFriendRequestRS) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10554
//好友请求ID包
type AddFriendRequestID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId *uint64 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId" json:"from_user_id,omitempty"` /// 申请的用户id
}

func (x *AddFriendRequestID) Reset() {
	*x = AddFriendRequestID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddFriendRequestID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddFriendRequestID) ProtoMessage() {}

func (x *AddFriendRequestID) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddFriendRequestID.ProtoReflect.Descriptor instead.
func (*AddFriendRequestID) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{2}
}

func (x *AddFriendRequestID) GetFromUserId() uint64 {
	if x != nil && x.FromUserId != nil {
		return *x.FromUserId
	}
	return 0
}

//## 10555
//同意好友申请请求包
type AcceptFriendRequestRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId *uint64              `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 申请的用户id
}

func (x *AcceptFriendRequestRQ) Reset() {
	*x = AcceptFriendRequestRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptFriendRequestRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRQ) ProtoMessage() {}

func (x *AcceptFriendRequestRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRQ.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{3}
}

func (x *AcceptFriendRequestRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AcceptFriendRequestRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10556
//同意好友申请响应包
type AcceptFriendRequestRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header  *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
}

func (x *AcceptFriendRequestRS) Reset() {
	*x = AcceptFriendRequestRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptFriendRequestRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestRS) ProtoMessage() {}

func (x *AcceptFriendRequestRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestRS.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{4}
}

func (x *AcceptFriendRequestRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *AcceptFriendRequestRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//## 10557
//同意好友请求ID包
type AcceptFriendRequestID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"` /// 同意的用户id
}

func (x *AcceptFriendRequestID) Reset() {
	*x = AcceptFriendRequestID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AcceptFriendRequestID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AcceptFriendRequestID) ProtoMessage() {}

func (x *AcceptFriendRequestID) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AcceptFriendRequestID.ProtoReflect.Descriptor instead.
func (*AcceptFriendRequestID) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{5}
}

func (x *AcceptFriendRequestID) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10558
//拒绝好友申请请求包
type RejectFriendRequestRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId *uint64              `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 申请的用户id
}

func (x *RejectFriendRequestRQ) Reset() {
	*x = RejectFriendRequestRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectFriendRequestRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendRequestRQ) ProtoMessage() {}

func (x *RejectFriendRequestRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendRequestRQ.ProtoReflect.Descriptor instead.
func (*RejectFriendRequestRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{6}
}

func (x *RejectFriendRequestRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RejectFriendRequestRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10559
//拒绝好友申请响应包
type RejectFriendRequestRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header  *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
}

func (x *RejectFriendRequestRS) Reset() {
	*x = RejectFriendRequestRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RejectFriendRequestRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RejectFriendRequestRS) ProtoMessage() {}

func (x *RejectFriendRequestRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RejectFriendRequestRS.ProtoReflect.Descriptor instead.
func (*RejectFriendRequestRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{7}
}

func (x *RejectFriendRequestRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *RejectFriendRequestRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//## 10560
//好友列表请求包
type FriendListRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Page     *int32               `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`                         // 页
	PageSize *int32               `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"` // 页大小
}

func (x *FriendListRQ) Reset() {
	*x = FriendListRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRQ) ProtoMessage() {}

func (x *FriendListRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRQ.ProtoReflect.Descriptor instead.
func (*FriendListRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{8}
}

func (x *FriendListRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FriendListRQ) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *FriendListRQ) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

type FriendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`    // 好友id
	AddTime *int64  `protobuf:"varint,2,opt,name=add_time,json=addTime" json:"add_time,omitempty"` // 添加时间
}

func (x *FriendInfo) Reset() {
	*x = FriendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendInfo) ProtoMessage() {}

func (x *FriendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendInfo.ProtoReflect.Descriptor instead.
func (*FriendInfo) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{9}
}

func (x *FriendInfo) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *FriendInfo) GetAddTime() int64 {
	if x != nil && x.AddTime != nil {
		return *x.AddTime
	}
	return 0
}

//## 10561
//好友列表响应包
type FriendListRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo    *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header     *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Page       *int32                 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`                              // 页
	PageSize   *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`      // 页大小
	FriendList []*FriendInfo          `protobuf:"bytes,5,rep,name=friend_list,json=friendList" json:"friend_list,omitempty"` // 好友列表
}

func (x *FriendListRS) Reset() {
	*x = FriendListRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FriendListRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FriendListRS) ProtoMessage() {}

func (x *FriendListRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FriendListRS.ProtoReflect.Descriptor instead.
func (*FriendListRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{10}
}

func (x *FriendListRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *FriendListRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *FriendListRS) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *FriendListRS) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *FriendListRS) GetFriendList() []*FriendInfo {
	if x != nil {
		return x.FriendList
	}
	return nil
}

//## 10562
//删除好友请求包
type RemoveFriendRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId *uint64              `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 好友id
}

func (x *RemoveFriendRQ) Reset() {
	*x = RemoveFriendRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFriendRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRQ) ProtoMessage() {}

func (x *RemoveFriendRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRQ.ProtoReflect.Descriptor instead.
func (*RemoveFriendRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{11}
}

func (x *RemoveFriendRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RemoveFriendRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10563
//删除好友响应包
type RemoveFriendRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header  *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
}

func (x *RemoveFriendRS) Reset() {
	*x = RemoveFriendRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveFriendRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveFriendRS) ProtoMessage() {}

func (x *RemoveFriendRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveFriendRS.ProtoReflect.Descriptor instead.
func (*RemoveFriendRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{12}
}

func (x *RemoveFriendRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *RemoveFriendRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//## 10564
//添加黑名单请求包
type AddBlacklistRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId *uint64              `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 要拉黑的用户id
}

func (x *AddBlacklistRQ) Reset() {
	*x = AddBlacklistRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBlacklistRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistRQ) ProtoMessage() {}

func (x *AddBlacklistRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistRQ.ProtoReflect.Descriptor instead.
func (*AddBlacklistRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{13}
}

func (x *AddBlacklistRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AddBlacklistRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10565
//添加黑名单响应包
type AddBlacklistRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header  *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
}

func (x *AddBlacklistRS) Reset() {
	*x = AddBlacklistRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddBlacklistRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddBlacklistRS) ProtoMessage() {}

func (x *AddBlacklistRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddBlacklistRS.ProtoReflect.Descriptor instead.
func (*AddBlacklistRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{14}
}

func (x *AddBlacklistRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *AddBlacklistRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//## 10566
//删除黑名单请求包
type RemoveBlacklistRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId *uint64              `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"` // 要取消拉黑的用户id
}

func (x *RemoveBlacklistRQ) Reset() {
	*x = RemoveBlacklistRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBlacklistRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistRQ) ProtoMessage() {}

func (x *RemoveBlacklistRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistRQ.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{15}
}

func (x *RemoveBlacklistRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *RemoveBlacklistRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 10567
//删除黑名单响应包
type RemoveBlacklistRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header  *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
}

func (x *RemoveBlacklistRS) Reset() {
	*x = RemoveBlacklistRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *RemoveBlacklistRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveBlacklistRS) ProtoMessage() {}

func (x *RemoveBlacklistRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveBlacklistRS.ProtoReflect.Descriptor instead.
func (*RemoveBlacklistRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveBlacklistRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *RemoveBlacklistRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//## 10568
//已发送好友请求列表请求包
type SendFriendRequestListRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Page     *int32               `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`                         // 页
	PageSize *int32               `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"` // 页大小
}

func (x *SendFriendRequestListRQ) Reset() {
	*x = SendFriendRequestListRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendRequestListRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestListRQ) ProtoMessage() {}

func (x *SendFriendRequestListRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestListRQ.ProtoReflect.Descriptor instead.
func (*SendFriendRequestListRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{17}
}

func (x *SendFriendRequestListRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SendFriendRequestListRQ) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *SendFriendRequestListRQ) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

// 发送的信息
type SendInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ToUserId *uint64 `protobuf:"varint,1,opt,name=to_user_id,json=toUserId" json:"to_user_id,omitempty"` // 发送给谁的
	SendTime *int64  `protobuf:"varint,2,opt,name=send_time,json=sendTime" json:"send_time,omitempty"`   // 发送时间
	Status   *int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`                       // 状态
}

func (x *SendInfo) Reset() {
	*x = SendInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendInfo) ProtoMessage() {}

func (x *SendInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendInfo.ProtoReflect.Descriptor instead.
func (*SendInfo) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{18}
}

func (x *SendInfo) GetToUserId() uint64 {
	if x != nil && x.ToUserId != nil {
		return *x.ToUserId
	}
	return 0
}

func (x *SendInfo) GetSendTime() int64 {
	if x != nil && x.SendTime != nil {
		return *x.SendTime
	}
	return 0
}

func (x *SendInfo) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

//## 10569
//已发送好友请求列表响应包
type SendFriendRequestListRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo  *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header   *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Page     *int32                 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`                         // 页
	PageSize *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"` // 页大小
	SendList []*SendInfo            `protobuf:"bytes,5,rep,name=send_list,json=sendList" json:"send_list,omitempty"`  // 发送的列表
}

func (x *SendFriendRequestListRS) Reset() {
	*x = SendFriendRequestListRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SendFriendRequestListRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendFriendRequestListRS) ProtoMessage() {}

func (x *SendFriendRequestListRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendFriendRequestListRS.ProtoReflect.Descriptor instead.
func (*SendFriendRequestListRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{19}
}

func (x *SendFriendRequestListRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *SendFriendRequestListRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *SendFriendRequestListRS) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *SendFriendRequestListRS) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *SendFriendRequestListRS) GetSendList() []*SendInfo {
	if x != nil {
		return x.SendList
	}
	return nil
}

//## 10570
//收到好友请求列表请求包
type ReceiveFriendRequestListRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Page     *int32               `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`                         // 页
	PageSize *int32               `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"` // 页大小
}

func (x *ReceiveFriendRequestListRQ) Reset() {
	*x = ReceiveFriendRequestListRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveFriendRequestListRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveFriendRequestListRQ) ProtoMessage() {}

func (x *ReceiveFriendRequestListRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveFriendRequestListRQ.ProtoReflect.Descriptor instead.
func (*ReceiveFriendRequestListRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{20}
}

func (x *ReceiveFriendRequestListRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReceiveFriendRequestListRQ) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ReceiveFriendRequestListRQ) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

// 收到的信息
type ReceiveInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromUserId  *uint64 `protobuf:"varint,1,opt,name=from_user_id,json=fromUserId" json:"from_user_id,omitempty"`  // 谁发送的
	ReceiveTime *int64  `protobuf:"varint,2,opt,name=receive_time,json=receiveTime" json:"receive_time,omitempty"` // 收到的时间
	Status      *int32  `protobuf:"varint,3,opt,name=status" json:"status,omitempty"`                              // 状态
}

func (x *ReceiveInfo) Reset() {
	*x = ReceiveInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveInfo) ProtoMessage() {}

func (x *ReceiveInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveInfo.ProtoReflect.Descriptor instead.
func (*ReceiveInfo) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{21}
}

func (x *ReceiveInfo) GetFromUserId() uint64 {
	if x != nil && x.FromUserId != nil {
		return *x.FromUserId
	}
	return 0
}

func (x *ReceiveInfo) GetReceiveTime() int64 {
	if x != nil && x.ReceiveTime != nil {
		return *x.ReceiveTime
	}
	return 0
}

func (x *ReceiveInfo) GetStatus() int32 {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return 0
}

//## 10571
//收到好友请求列表响应包
type ReceiveFriendRequestListRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo     *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header      *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Page        *int32                 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`                                 // 页
	PageSize    *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`         // 页大小
	ReceiveList []*ReceiveInfo         `protobuf:"bytes,5,rep,name=receive_list,json=receiveList" json:"receive_list,omitempty"` // 收到的列表
}

func (x *ReceiveFriendRequestListRS) Reset() {
	*x = ReceiveFriendRequestListRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiveFriendRequestListRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiveFriendRequestListRS) ProtoMessage() {}

func (x *ReceiveFriendRequestListRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiveFriendRequestListRS.ProtoReflect.Descriptor instead.
func (*ReceiveFriendRequestListRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{22}
}

func (x *ReceiveFriendRequestListRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *ReceiveFriendRequestListRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReceiveFriendRequestListRS) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *ReceiveFriendRequestListRS) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *ReceiveFriendRequestListRS) GetReceiveList() []*ReceiveInfo {
	if x != nil {
		return x.ReceiveList
	}
	return nil
}

//## 10572
// 黑名单请求包
type BlacklistRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	Page     *int32               `protobuf:"varint,2,opt,name=page" json:"page,omitempty"`                         // 页
	PageSize *int32               `protobuf:"varint,3,opt,name=page_size,json=pageSize" json:"page_size,omitempty"` // 页大小
}

func (x *BlacklistRQ) Reset() {
	*x = BlacklistRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRQ) ProtoMessage() {}

func (x *BlacklistRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRQ.ProtoReflect.Descriptor instead.
func (*BlacklistRQ) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{23}
}

func (x *BlacklistRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BlacklistRQ) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *BlacklistRQ) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

// 拉黑用户信息
type BlackUserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`    // 拉黑的用户id
	AddTime *int64  `protobuf:"varint,2,opt,name=add_time,json=addTime" json:"add_time,omitempty"` // 加入的时间
}

func (x *BlackUserInfo) Reset() {
	*x = BlackUserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlackUserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlackUserInfo) ProtoMessage() {}

func (x *BlackUserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlackUserInfo.ProtoReflect.Descriptor instead.
func (*BlackUserInfo) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{24}
}

func (x *BlackUserInfo) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *BlackUserInfo) GetAddTime() int64 {
	if x != nil && x.AddTime != nil {
		return *x.AddTime
	}
	return 0
}

//## 10573
// 黑名单响应包
type BlacklistRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo       *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	Header        *Common.PacketHeader   `protobuf:"bytes,2,opt,name=header" json:"header,omitempty"`
	Page          *int32                 `protobuf:"varint,3,opt,name=page" json:"page,omitempty"`                                         // 页
	PageSize      *int32                 `protobuf:"varint,4,opt,name=page_size,json=pageSize" json:"page_size,omitempty"`                 // 页大小
	BlackUserList []*BlackUserInfo       `protobuf:"bytes,5,rep,name=black_user_list,json=blackUserList" json:"black_user_list,omitempty"` // 拉黑列表
}

func (x *BlacklistRS) Reset() {
	*x = BlacklistRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Friend_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BlacklistRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlacklistRS) ProtoMessage() {}

func (x *BlacklistRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Friend_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlacklistRS.ProtoReflect.Descriptor instead.
func (*BlacklistRS) Descriptor() ([]byte, []int) {
	return file_common_Friend_proto_rawDescGZIP(), []int{25}
}

func (x *BlacklistRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *BlacklistRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *BlacklistRS) GetPage() int32 {
	if x != nil && x.Page != nil {
		return *x.Page
	}
	return 0
}

func (x *BlacklistRS) GetPageSize() int32 {
	if x != nil && x.PageSize != nil {
		return *x.PageSize
	}
	return 0
}

func (x *BlacklistRS) GetBlackUserList() []*BlackUserInfo {
	if x != nil {
		return x.BlackUserList
	}
	return nil
}

var File_common_Friend_proto protoreflect.FileDescriptor

var file_common_Friend_proto_rawDesc = []byte{
	0x0a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x4d, 0x61, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x1a, 0x18,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
	0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x5b, 0x0a,
	0x12, 0x41, 0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63,
	0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x8e, 0x01, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52,
	0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70,
	0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61,
	0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x36, 0x0a, 0x12, 0x41,
	0x64, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x49,
	0x44, 0x12, 0x20, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x5e, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65,
	0x72, 0x49, 0x64, 0x22, 0x78, 0x0a, 0x15, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x30, 0x0a,
	0x15, 0x41, 0x63, 0x63, 0x65, 0x70, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x49, 0x44, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x5e, 0x0a, 0x15, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22,
	0x78, 0x0a, 0x15, 0x52, 0x65, 0x6a, 0x65, 0x63, 0x74, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73,
	0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x6d, 0x0a, 0x0c, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d,
	0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70,
	0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08,
	0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x40, 0x0a, 0x0a, 0x46, 0x72, 0x69, 0x65,
	0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xd6, 0x01, 0x0a, 0x0c, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65,
	0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c,
	0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65,
	0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x34, 0x0a,
	0x0b, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x13, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x2e, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0a, 0x66, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x4c,
	0x69, 0x73, 0x74, 0x22, 0x57, 0x0a, 0x0e, 0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69,
	0x65, 0x6e, 0x64, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x0e,
	0x52, 0x65, 0x6d, 0x6f, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x53, 0x12, 0x31,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22,
	0x57, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52,
	0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x71, 0x0a, 0x0e, 0x41, 0x64, 0x64, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x5a, 0x0a, 0x11, 0x52,
	0x65, 0x6d, 0x6f, 0x76, 0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x51,
	0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x74, 0x0a, 0x11, 0x52, 0x65, 0x6d, 0x6f, 0x76,
	0x65, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0x78, 0x0a,
	0x17, 0x53, 0x65, 0x6e, 0x64, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64,
	0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06,
	0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61,
	0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70,
	0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x5d, 0x0a, 0x08, 0x53, 0x65, 0x6e, 0x64, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x0a, 0x74, 0x6f, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74, 0x6f, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xdb, 0x01, 0x0a, 0x17, 0x53, 0x65, 0x6e, 0x64, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79,
	0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50,
	0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f,
	0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x50, 0x61,
	0x79, 0x2e, 0x53, 0x65, 0x6e, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64,
	0x4c, 0x69, 0x73, 0x74, 0x22, 0x7b, 0x0a, 0x1a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x46,
	0x72, 0x69, 0x65, 0x6e, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74,
	0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b,
	0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a,
	0x65, 0x22, 0x6a, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x20, 0x0a, 0x0c, 0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0a, 0x66, 0x72, 0x6f, 0x6d, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x21, 0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x74, 0x69,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x22, 0xe7, 0x01,
	0x0a, 0x1a, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08,
	0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72,
	0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a,
	0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x37,
	0x0a, 0x0c, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x05,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x2e, 0x52,
	0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x6c, 0x0a, 0x0b, 0x42, 0x6c, 0x61, 0x63, 0x6b,
	0x6c, 0x69, 0x73, 0x74, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65,
	0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67,
	0x65, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x43, 0x0a, 0x0d, 0x42, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x73,
	0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x19, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x07, 0x61, 0x64, 0x64, 0x54, 0x69, 0x6d, 0x65, 0x22, 0xdf, 0x01, 0x0a, 0x0b, 0x42,
	0x6c, 0x61, 0x63, 0x6b, 0x6c, 0x69, 0x73, 0x74, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72,
	0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2c, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12,
	0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73, 0x69, 0x7a, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x3e, 0x0a, 0x0f,
	0x62, 0x6c, 0x61, 0x63, 0x6b, 0x5f, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x05, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x50, 0x61, 0x79, 0x2e,
	0x42, 0x6c, 0x61, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0d, 0x62,
	0x6c, 0x61, 0x63, 0x6b, 0x55, 0x73, 0x65, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x2f, 0x5a, 0x21,
	0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x46, 0x72, 0x69, 0x65, 0x6e,
	0x64, 0xaa, 0x02, 0x09, 0x50, 0x62, 0x2e, 0x46, 0x72, 0x69, 0x65, 0x6e, 0x64,
}

var (
	file_common_Friend_proto_rawDescOnce sync.Once
	file_common_Friend_proto_rawDescData = file_common_Friend_proto_rawDesc
)

func file_common_Friend_proto_rawDescGZIP() []byte {
	file_common_Friend_proto_rawDescOnce.Do(func() {
		file_common_Friend_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_Friend_proto_rawDescData)
	})
	return file_common_Friend_proto_rawDescData
}

var file_common_Friend_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_common_Friend_proto_goTypes = []interface{}{
	(*AddFriendRequestRQ)(nil),         // 0: MazePay.AddFriendRequestRQ
	(*AddFriendRequestRS)(nil),         // 1: MazePay.AddFriendRequestRS
	(*AddFriendRequestID)(nil),         // 2: MazePay.AddFriendRequestID
	(*AcceptFriendRequestRQ)(nil),      // 3: MazePay.AcceptFriendRequestRQ
	(*AcceptFriendRequestRS)(nil),      // 4: MazePay.AcceptFriendRequestRS
	(*AcceptFriendRequestID)(nil),      // 5: MazePay.AcceptFriendRequestID
	(*RejectFriendRequestRQ)(nil),      // 6: MazePay.RejectFriendRequestRQ
	(*RejectFriendRequestRS)(nil),      // 7: MazePay.RejectFriendRequestRS
	(*FriendListRQ)(nil),               // 8: MazePay.FriendListRQ
	(*FriendInfo)(nil),                 // 9: MazePay.FriendInfo
	(*FriendListRS)(nil),               // 10: MazePay.FriendListRS
	(*RemoveFriendRQ)(nil),             // 11: MazePay.RemoveFriendRQ
	(*RemoveFriendRS)(nil),             // 12: MazePay.RemoveFriendRS
	(*AddBlacklistRQ)(nil),             // 13: MazePay.AddBlacklistRQ
	(*AddBlacklistRS)(nil),             // 14: MazePay.AddBlacklistRS
	(*RemoveBlacklistRQ)(nil),          // 15: MazePay.RemoveBlacklistRQ
	(*RemoveBlacklistRS)(nil),          // 16: MazePay.RemoveBlacklistRS
	(*SendFriendRequestListRQ)(nil),    // 17: MazePay.SendFriendRequestListRQ
	(*SendInfo)(nil),                   // 18: MazePay.SendInfo
	(*SendFriendRequestListRS)(nil),    // 19: MazePay.SendFriendRequestListRS
	(*ReceiveFriendRequestListRQ)(nil), // 20: MazePay.ReceiveFriendRequestListRQ
	(*ReceiveInfo)(nil),                // 21: MazePay.ReceiveInfo
	(*ReceiveFriendRequestListRS)(nil), // 22: MazePay.ReceiveFriendRequestListRS
	(*BlacklistRQ)(nil),                // 23: MazePay.BlacklistRQ
	(*BlackUserInfo)(nil),              // 24: MazePay.BlackUserInfo
	(*BlacklistRS)(nil),                // 25: MazePay.BlacklistRS
	(*Common.PacketHeader)(nil),        // 26: Common.PacketHeader
	(*MessageType.ErrorInfo)(nil),      // 27: MessageType.ErrorInfo
}
var file_common_Friend_proto_depIdxs = []int32{
	26, // 0: MazePay.AddFriendRequestRQ.header:type_name -> Common.PacketHeader
	27, // 1: MazePay.AddFriendRequestRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 2: MazePay.AddFriendRequestRS.header:type_name -> Common.PacketHeader
	26, // 3: MazePay.AcceptFriendRequestRQ.header:type_name -> Common.PacketHeader
	27, // 4: MazePay.AcceptFriendRequestRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 5: MazePay.AcceptFriendRequestRS.header:type_name -> Common.PacketHeader
	26, // 6: MazePay.RejectFriendRequestRQ.header:type_name -> Common.PacketHeader
	27, // 7: MazePay.RejectFriendRequestRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 8: MazePay.RejectFriendRequestRS.header:type_name -> Common.PacketHeader
	26, // 9: MazePay.FriendListRQ.header:type_name -> Common.PacketHeader
	27, // 10: MazePay.FriendListRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 11: MazePay.FriendListRS.header:type_name -> Common.PacketHeader
	9,  // 12: MazePay.FriendListRS.friend_list:type_name -> MazePay.FriendInfo
	26, // 13: MazePay.RemoveFriendRQ.header:type_name -> Common.PacketHeader
	27, // 14: MazePay.RemoveFriendRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 15: MazePay.RemoveFriendRS.header:type_name -> Common.PacketHeader
	26, // 16: MazePay.AddBlacklistRQ.header:type_name -> Common.PacketHeader
	27, // 17: MazePay.AddBlacklistRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 18: MazePay.AddBlacklistRS.header:type_name -> Common.PacketHeader
	26, // 19: MazePay.RemoveBlacklistRQ.header:type_name -> Common.PacketHeader
	27, // 20: MazePay.RemoveBlacklistRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 21: MazePay.RemoveBlacklistRS.header:type_name -> Common.PacketHeader
	26, // 22: MazePay.SendFriendRequestListRQ.header:type_name -> Common.PacketHeader
	27, // 23: MazePay.SendFriendRequestListRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 24: MazePay.SendFriendRequestListRS.header:type_name -> Common.PacketHeader
	18, // 25: MazePay.SendFriendRequestListRS.send_list:type_name -> MazePay.SendInfo
	26, // 26: MazePay.ReceiveFriendRequestListRQ.header:type_name -> Common.PacketHeader
	27, // 27: MazePay.ReceiveFriendRequestListRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 28: MazePay.ReceiveFriendRequestListRS.header:type_name -> Common.PacketHeader
	21, // 29: MazePay.ReceiveFriendRequestListRS.receive_list:type_name -> MazePay.ReceiveInfo
	26, // 30: MazePay.BlacklistRQ.header:type_name -> Common.PacketHeader
	27, // 31: MazePay.BlacklistRS.err_info:type_name -> MessageType.ErrorInfo
	26, // 32: MazePay.BlacklistRS.header:type_name -> Common.PacketHeader
	24, // 33: MazePay.BlacklistRS.black_user_list:type_name -> MazePay.BlackUserInfo
	34, // [34:34] is the sub-list for method output_type
	34, // [34:34] is the sub-list for method input_type
	34, // [34:34] is the sub-list for extension type_name
	34, // [34:34] is the sub-list for extension extendee
	0,  // [0:34] is the sub-list for field type_name
}

func init() { file_common_Friend_proto_init() }
func file_common_Friend_proto_init() {
	if File_common_Friend_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_Friend_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendRequestRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendRequestRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddFriendRequestID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptFriendRequestRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptFriendRequestRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AcceptFriendRequestID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectFriendRequestRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RejectFriendRequestRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FriendListRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFriendRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveFriendRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBlacklistRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddBlacklistRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBlacklistRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*RemoveBlacklistRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendRequestListRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SendFriendRequestListRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveFriendRequestListRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiveFriendRequestListRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlackUserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Friend_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BlacklistRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_Friend_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_Friend_proto_goTypes,
		DependencyIndexes: file_common_Friend_proto_depIdxs,
		MessageInfos:      file_common_Friend_proto_msgTypes,
	}.Build()
	File_common_Friend_proto = out.File
	file_common_Friend_proto_rawDesc = nil
	file_common_Friend_proto_goTypes = nil
	file_common_Friend_proto_depIdxs = nil
}
