// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: server/MazeEquipSvr.proto

package MazeEquipSvr

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	MessageType "maze_game_server/pb/common/MessageType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ENUM_EQUIP_BAG_OP_TYPE int32

const (
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_FOE                 ENUM_EQUIP_BAG_OP_TYPE = 1  //迷宫怪物掉落
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_BOX_AWARD           ENUM_EQUIP_BAG_OP_TYPE = 2  //迷宫宝箱掉落
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_DRESS_EQUIP               ENUM_EQUIP_BAG_OP_TYPE = 3  //装备穿戴
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_SALE                ENUM_EQUIP_BAG_OP_TYPE = 4  //出售装备
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_EQUIP_AUTO_DEL      ENUM_EQUIP_BAG_OP_TYPE = 5  //迷宫装备穿戴自动删除
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_PASS_DEL            ENUM_EQUIP_BAG_OP_TYPE = 6  //迷宫关卡通关删除装备
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_INIT_EQUIP                ENUM_EQUIP_BAG_OP_TYPE = 7  // 迷宫初始化装备
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_COMPOUND            ENUM_EQUIP_BAG_OP_TYPE = 8  //迷宫装备合成 赵西明
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_PASS_AWARD          ENUM_EQUIP_BAG_OP_TYPE = 9  //迷宫通关奖励 张登元
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_SWEEP_AWARD         ENUM_EQUIP_BAG_OP_TYPE = 10 //迷宫扫荡奖励 张登元
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_MONSTER_DEATH_AWARD ENUM_EQUIP_BAG_OP_TYPE = 11 // 击杀怪物奖励
	ENUM_EQUIP_BAG_OP_TYPE_MAZE_EQUIP_DROP_ITEM_BOX_AWARD ENUM_EQUIP_BAG_OP_TYPE = 12 // 关卡掉落物宝箱装备奖励
)

// Enum value maps for ENUM_EQUIP_BAG_OP_TYPE.
var (
	ENUM_EQUIP_BAG_OP_TYPE_name = map[int32]string{
		1:  "MAZE_EQUIP_FOE",
		2:  "MAZE_EQUIP_BOX_AWARD",
		3:  "MAZE_DRESS_EQUIP",
		4:  "MAZE_EQUIP_SALE",
		5:  "MAZE_EQUIP_EQUIP_AUTO_DEL",
		6:  "MAZE_EQUIP_PASS_DEL",
		7:  "MAZE_INIT_EQUIP",
		8:  "MAZE_EQUIP_COMPOUND",
		9:  "MAZE_EQUIP_PASS_AWARD",
		10: "MAZE_EQUIP_SWEEP_AWARD",
		11: "MAZE_EQUIP_MONSTER_DEATH_AWARD",
		12: "MAZE_EQUIP_DROP_ITEM_BOX_AWARD",
	}
	ENUM_EQUIP_BAG_OP_TYPE_value = map[string]int32{
		"MAZE_EQUIP_FOE":                 1,
		"MAZE_EQUIP_BOX_AWARD":           2,
		"MAZE_DRESS_EQUIP":               3,
		"MAZE_EQUIP_SALE":                4,
		"MAZE_EQUIP_EQUIP_AUTO_DEL":      5,
		"MAZE_EQUIP_PASS_DEL":            6,
		"MAZE_INIT_EQUIP":                7,
		"MAZE_EQUIP_COMPOUND":            8,
		"MAZE_EQUIP_PASS_AWARD":          9,
		"MAZE_EQUIP_SWEEP_AWARD":         10,
		"MAZE_EQUIP_MONSTER_DEATH_AWARD": 11,
		"MAZE_EQUIP_DROP_ITEM_BOX_AWARD": 12,
	}
)

func (x ENUM_EQUIP_BAG_OP_TYPE) Enum() *ENUM_EQUIP_BAG_OP_TYPE {
	p := new(ENUM_EQUIP_BAG_OP_TYPE)
	*p = x
	return p
}

func (x ENUM_EQUIP_BAG_OP_TYPE) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ENUM_EQUIP_BAG_OP_TYPE) Descriptor() protoreflect.EnumDescriptor {
	return file_server_MazeEquipSvr_proto_enumTypes[0].Descriptor()
}

func (ENUM_EQUIP_BAG_OP_TYPE) Type() protoreflect.EnumType {
	return &file_server_MazeEquipSvr_proto_enumTypes[0]
}

func (x ENUM_EQUIP_BAG_OP_TYPE) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *ENUM_EQUIP_BAG_OP_TYPE) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = ENUM_EQUIP_BAG_OP_TYPE(num)
	return nil
}

// Deprecated: Use ENUM_EQUIP_BAG_OP_TYPE.Descriptor instead.
func (ENUM_EQUIP_BAG_OP_TYPE) EnumDescriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{0}
}

// 装备添加条件
type EQUIP_ADD_CONDITION int32

const (
	EQUIP_ADD_CONDITION_BE_SURE_SUIT          EQUIP_ADD_CONDITION = 1  //必定出套装属性
	EQUIP_ADD_CONDITION_ASSIGN_SUIT           EQUIP_ADD_CONDITION = 2  //指定出套装属性
	EQUIP_ADD_CONDITION_ASSIGN_EQUIP_SUB_TYPE EQUIP_ADD_CONDITION = 4  //指定装备子类型
	EQUIP_ADD_CONDITION_SPECIAL_EQUIP         EQUIP_ADD_CONDITION = 8  //随机词条走特殊表
	EQUIP_ADD_CONDITION_INSTANCE_EQUIP        EQUIP_ADD_CONDITION = 16 //实例化装备
)

// Enum value maps for EQUIP_ADD_CONDITION.
var (
	EQUIP_ADD_CONDITION_name = map[int32]string{
		1:  "BE_SURE_SUIT",
		2:  "ASSIGN_SUIT",
		4:  "ASSIGN_EQUIP_SUB_TYPE",
		8:  "SPECIAL_EQUIP",
		16: "INSTANCE_EQUIP",
	}
	EQUIP_ADD_CONDITION_value = map[string]int32{
		"BE_SURE_SUIT":          1,
		"ASSIGN_SUIT":           2,
		"ASSIGN_EQUIP_SUB_TYPE": 4,
		"SPECIAL_EQUIP":         8,
		"INSTANCE_EQUIP":        16,
	}
)

func (x EQUIP_ADD_CONDITION) Enum() *EQUIP_ADD_CONDITION {
	p := new(EQUIP_ADD_CONDITION)
	*p = x
	return p
}

func (x EQUIP_ADD_CONDITION) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EQUIP_ADD_CONDITION) Descriptor() protoreflect.EnumDescriptor {
	return file_server_MazeEquipSvr_proto_enumTypes[1].Descriptor()
}

func (EQUIP_ADD_CONDITION) Type() protoreflect.EnumType {
	return &file_server_MazeEquipSvr_proto_enumTypes[1]
}

func (x EQUIP_ADD_CONDITION) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *EQUIP_ADD_CONDITION) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = EQUIP_ADD_CONDITION(num)
	return nil
}

// Deprecated: Use EQUIP_ADD_CONDITION.Descriptor instead.
func (EQUIP_ADD_CONDITION) EnumDescriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{1}
}

//添加装备信息
type SvrEquipInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipId    *int32           `protobuf:"varint,1,opt,name=equip_id,json=equipId" json:"equip_id,omitempty"` //装备配置id
	Conditions []*ConditionInfo `protobuf:"bytes,2,rep,name=conditions" json:"conditions,omitempty"`           //添加装备条件 没有的不需要填
}

func (x *SvrEquipInfo) Reset() {
	*x = SvrEquipInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrEquipInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrEquipInfo) ProtoMessage() {}

func (x *SvrEquipInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrEquipInfo.ProtoReflect.Descriptor instead.
func (*SvrEquipInfo) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{0}
}

func (x *SvrEquipInfo) GetEquipId() int32 {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return 0
}

func (x *SvrEquipInfo) GetConditions() []*ConditionInfo {
	if x != nil {
		return x.Conditions
	}
	return nil
}

//装备信息
type EquipInstanceSvr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipId   *int32 `protobuf:"varint,1,opt,name=equip_id,json=equipId" json:"equip_id,omitempty"`       ///装备配置id
	EquipGuid *int64 `protobuf:"varint,2,opt,name=equip_guid,json=equipGuid" json:"equip_guid,omitempty"` ///实例id
	PopupId   *int64 `protobuf:"varint,3,opt,name=popup_id,json=popupId" json:"popup_id,omitempty"`       //弹窗id
}

func (x *EquipInstanceSvr) Reset() {
	*x = EquipInstanceSvr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipInstanceSvr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipInstanceSvr) ProtoMessage() {}

func (x *EquipInstanceSvr) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipInstanceSvr.ProtoReflect.Descriptor instead.
func (*EquipInstanceSvr) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{1}
}

func (x *EquipInstanceSvr) GetEquipId() int32 {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return 0
}

func (x *EquipInstanceSvr) GetEquipGuid() int64 {
	if x != nil && x.EquipGuid != nil {
		return *x.EquipGuid
	}
	return 0
}

func (x *EquipInstanceSvr) GetPopupId() int64 {
	if x != nil && x.PopupId != nil {
		return *x.PopupId
	}
	return 0
}

// 添加装备条件
type ConditionInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    *int32 `protobuf:"varint,1,opt,name=id" json:"id,omitempty"`       // EQUIP_ADD_CONDITION
	Value *int64 `protobuf:"varint,2,opt,name=value" json:"value,omitempty"` // 对应值
}

func (x *ConditionInfo) Reset() {
	*x = ConditionInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ConditionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConditionInfo) ProtoMessage() {}

func (x *ConditionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConditionInfo.ProtoReflect.Descriptor instead.
func (*ConditionInfo) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{2}
}

func (x *ConditionInfo) GetId() int32 {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return 0
}

func (x *ConditionInfo) GetValue() int64 {
	if x != nil && x.Value != nil {
		return *x.Value
	}
	return 0
}

//装备信息
type MazeEquipInfoSvr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipId    *int32  `protobuf:"varint,1,opt,name=equip_id,json=equipId" json:"equip_id,omitempty"`            //装备配置id
	EquipGuid  *int64  `protobuf:"varint,2,opt,name=equip_guid,json=equipGuid" json:"equip_guid,omitempty"`      //实例id
	EquipName  *string `protobuf:"bytes,3,opt,name=equip_name,json=equipName" json:"equip_name,omitempty"`       /// 装备名称
	EquipResId *int32  `protobuf:"varint,4,opt,name=equip_res_id,json=equipResId" json:"equip_res_id,omitempty"` ///装备资源id
	SuitId     *int32  `protobuf:"varint,5,opt,name=suit_id,json=suitId" json:"suit_id,omitempty"`               // 套装Id
	SealState  *int32  `protobuf:"varint,6,opt,name=seal_state,json=sealState" json:"seal_state,omitempty"`      ///封印状态 0=无封印 1=封印中 2=已解封
	Pos        *int32  `protobuf:"varint,7,opt,name=pos" json:"pos,omitempty"`                                   ///部位ENUM_ELEMENTS_POS
}

func (x *MazeEquipInfoSvr) Reset() {
	*x = MazeEquipInfoSvr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeEquipInfoSvr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeEquipInfoSvr) ProtoMessage() {}

func (x *MazeEquipInfoSvr) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeEquipInfoSvr.ProtoReflect.Descriptor instead.
func (*MazeEquipInfoSvr) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{3}
}

func (x *MazeEquipInfoSvr) GetEquipId() int32 {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return 0
}

func (x *MazeEquipInfoSvr) GetEquipGuid() int64 {
	if x != nil && x.EquipGuid != nil {
		return *x.EquipGuid
	}
	return 0
}

func (x *MazeEquipInfoSvr) GetEquipName() string {
	if x != nil && x.EquipName != nil {
		return *x.EquipName
	}
	return ""
}

func (x *MazeEquipInfoSvr) GetEquipResId() int32 {
	if x != nil && x.EquipResId != nil {
		return *x.EquipResId
	}
	return 0
}

func (x *MazeEquipInfoSvr) GetSuitId() int32 {
	if x != nil && x.SuitId != nil {
		return *x.SuitId
	}
	return 0
}

func (x *MazeEquipInfoSvr) GetSealState() int32 {
	if x != nil && x.SealState != nil {
		return *x.SealState
	}
	return 0
}

func (x *MazeEquipInfoSvr) GetPos() int32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

//## 100004	UN_RPC_PACK_ADD_MAZE_EQUIP_RQ
// 迷宫版添加装备请求
type SvrAddMazeEquipRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      *uint64         `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`                //用户id
	EquipList   []*SvrEquipInfo `protobuf:"bytes,2,rep,name=equip_list,json=equipList" json:"equip_list,omitempty"`        //装备
	OpType      *int32          `protobuf:"varint,3,opt,name=op_type,json=opType" json:"op_type,omitempty"`                //添加类型 ENUM_EQUIP_BAG_OP_TYPE
	Desc        []byte          `protobuf:"bytes,4,opt,name=desc" json:"desc,omitempty"`                                   // 添加描述
	TradeNumber *uint64         `protobuf:"varint,5,opt,name=trade_number,json=tradeNumber" json:"trade_number,omitempty"` // 交易流水号
}

func (x *SvrAddMazeEquipRQ) Reset() {
	*x = SvrAddMazeEquipRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrAddMazeEquipRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrAddMazeEquipRQ) ProtoMessage() {}

func (x *SvrAddMazeEquipRQ) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrAddMazeEquipRQ.ProtoReflect.Descriptor instead.
func (*SvrAddMazeEquipRQ) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{4}
}

func (x *SvrAddMazeEquipRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrAddMazeEquipRQ) GetEquipList() []*SvrEquipInfo {
	if x != nil {
		return x.EquipList
	}
	return nil
}

func (x *SvrAddMazeEquipRQ) GetOpType() int32 {
	if x != nil && x.OpType != nil {
		return *x.OpType
	}
	return 0
}

func (x *SvrAddMazeEquipRQ) GetDesc() []byte {
	if x != nil {
		return x.Desc
	}
	return nil
}

func (x *SvrAddMazeEquipRQ) GetTradeNumber() uint64 {
	if x != nil && x.TradeNumber != nil {
		return *x.TradeNumber
	}
	return 0
}

//## 100005	UN_RPC_PACK_ADD_MAZE_EQUIP_RS
// 迷宫版添加装备应答
type SvrAddMazeEquipRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo   *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserId    *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`         //用户id
	EquipList []*MazeEquipInfoSvr    `protobuf:"bytes,3,rep,name=equip_list,json=equipList" json:"equip_list,omitempty"` //装备
	OpType    *int32                 `protobuf:"varint,4,opt,name=op_type,json=opType" json:"op_type,omitempty"`         //添加类型 ENUM_EQUIP_BAG_OP_TYPE
}

func (x *SvrAddMazeEquipRS) Reset() {
	*x = SvrAddMazeEquipRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrAddMazeEquipRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrAddMazeEquipRS) ProtoMessage() {}

func (x *SvrAddMazeEquipRS) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrAddMazeEquipRS.ProtoReflect.Descriptor instead.
func (*SvrAddMazeEquipRS) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{5}
}

func (x *SvrAddMazeEquipRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *SvrAddMazeEquipRS) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrAddMazeEquipRS) GetEquipList() []*MazeEquipInfoSvr {
	if x != nil {
		return x.EquipList
	}
	return nil
}

func (x *SvrAddMazeEquipRS) GetOpType() int32 {
	if x != nil && x.OpType != nil {
		return *x.OpType
	}
	return 0
}

//## 131431 UN_RPC_PACK_SVR_MAZE_EQUIP_INSTANCE_RQ
// 迷宫版装备实例化请求
type SvrMazeEquipInstanceRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId      *uint64         `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`                //用户id
	EquipList   []*SvrEquipInfo `protobuf:"bytes,2,rep,name=equip_list,json=equipList" json:"equip_list,omitempty"`        //装备
	OpType      *int32          `protobuf:"varint,3,opt,name=op_type,json=opType" json:"op_type,omitempty"`                //添加类型ENUM_EQUIP_BAG_OP_TYPE
	TradeNumber *uint64         `protobuf:"varint,4,opt,name=trade_number,json=tradeNumber" json:"trade_number,omitempty"` // 交易流水号
	Desc        []byte          `protobuf:"bytes,5,opt,name=desc" json:"desc,omitempty"`                                   // 添加描述
}

func (x *SvrMazeEquipInstanceRQ) Reset() {
	*x = SvrMazeEquipInstanceRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrMazeEquipInstanceRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrMazeEquipInstanceRQ) ProtoMessage() {}

func (x *SvrMazeEquipInstanceRQ) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrMazeEquipInstanceRQ.ProtoReflect.Descriptor instead.
func (*SvrMazeEquipInstanceRQ) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{6}
}

func (x *SvrMazeEquipInstanceRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrMazeEquipInstanceRQ) GetEquipList() []*SvrEquipInfo {
	if x != nil {
		return x.EquipList
	}
	return nil
}

func (x *SvrMazeEquipInstanceRQ) GetOpType() int32 {
	if x != nil && x.OpType != nil {
		return *x.OpType
	}
	return 0
}

func (x *SvrMazeEquipInstanceRQ) GetTradeNumber() uint64 {
	if x != nil && x.TradeNumber != nil {
		return *x.TradeNumber
	}
	return 0
}

func (x *SvrMazeEquipInstanceRQ) GetDesc() []byte {
	if x != nil {
		return x.Desc
	}
	return nil
}

//## 131432 UN_RPC_PACK_SVR_MAZE_EQUIP_INSTANCE_RS
// 迷宫版装备实例化应答
type SvrMazeEquipInstanceRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrInfo   *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserId    *uint64                `protobuf:"varint,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`         //用户id
	EquipList []*EquipInstanceSvr    `protobuf:"bytes,3,rep,name=equip_list,json=equipList" json:"equip_list,omitempty"` //道具
}

func (x *SvrMazeEquipInstanceRS) Reset() {
	*x = SvrMazeEquipInstanceRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrMazeEquipInstanceRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrMazeEquipInstanceRS) ProtoMessage() {}

func (x *SvrMazeEquipInstanceRS) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrMazeEquipInstanceRS.ProtoReflect.Descriptor instead.
func (*SvrMazeEquipInstanceRS) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{7}
}

func (x *SvrMazeEquipInstanceRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *SvrMazeEquipInstanceRS) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrMazeEquipInstanceRS) GetEquipList() []*EquipInstanceSvr {
	if x != nil {
		return x.EquipList
	}
	return nil
}

//## 100006	UN_RPC_PACK_MAZE_EQUIP_ASSEMBLE_RQ
// 迷宫版背包装备穿戴请求
type SvrMazeEquipAssembleRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId            *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`                                    //用户id
	EquipPos          *int32  `protobuf:"varint,2,opt,name=equip_pos,json=equipPos" json:"equip_pos,omitempty"`                              // 装备位
	EquipGuid         *int64  `protobuf:"varint,3,opt,name=equip_guid,json=equipGuid" json:"equip_guid,omitempty"`                           // 装备guid
	ReplacedEquipGuid *int64  `protobuf:"varint,4,opt,name=replaced_equip_guid,json=replacedEquipGuid" json:"replaced_equip_guid,omitempty"` // 被替换的装备
	EquipSrc          *int32  `protobuf:"varint,5,opt,name=equip_src,json=equipSrc" json:"equip_src,omitempty"`                              // 0默认是主背包 1=多选一
	DiscardedGuids    []int64 `protobuf:"varint,6,rep,name=discarded_guids,json=discardedGuids" json:"discarded_guids,omitempty"`            // 放弃的装备
}

func (x *SvrMazeEquipAssembleRQ) Reset() {
	*x = SvrMazeEquipAssembleRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrMazeEquipAssembleRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrMazeEquipAssembleRQ) ProtoMessage() {}

func (x *SvrMazeEquipAssembleRQ) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrMazeEquipAssembleRQ.ProtoReflect.Descriptor instead.
func (*SvrMazeEquipAssembleRQ) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{8}
}

func (x *SvrMazeEquipAssembleRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrMazeEquipAssembleRQ) GetEquipPos() int32 {
	if x != nil && x.EquipPos != nil {
		return *x.EquipPos
	}
	return 0
}

func (x *SvrMazeEquipAssembleRQ) GetEquipGuid() int64 {
	if x != nil && x.EquipGuid != nil {
		return *x.EquipGuid
	}
	return 0
}

func (x *SvrMazeEquipAssembleRQ) GetReplacedEquipGuid() int64 {
	if x != nil && x.ReplacedEquipGuid != nil {
		return *x.ReplacedEquipGuid
	}
	return 0
}

func (x *SvrMazeEquipAssembleRQ) GetEquipSrc() int32 {
	if x != nil && x.EquipSrc != nil {
		return *x.EquipSrc
	}
	return 0
}

func (x *SvrMazeEquipAssembleRQ) GetDiscardedGuids() []int64 {
	if x != nil {
		return x.DiscardedGuids
	}
	return nil
}

//## 100007	UN_RPC_PACK_MAZE_EQUIP_ASSEMBLE_RS
// 迷宫版背包装备穿戴应答
type SvrMazeEquipAssembleRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  *uint64                `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`   //用户id
	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"` //结果
}

func (x *SvrMazeEquipAssembleRS) Reset() {
	*x = SvrMazeEquipAssembleRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrMazeEquipAssembleRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrMazeEquipAssembleRS) ProtoMessage() {}

func (x *SvrMazeEquipAssembleRS) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrMazeEquipAssembleRS.ProtoReflect.Descriptor instead.
func (*SvrMazeEquipAssembleRS) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{9}
}

func (x *SvrMazeEquipAssembleRS) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrMazeEquipAssembleRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

//## 100008	UN_RPC_PACK_MAZE_EQUIP_SALE_RQ
// 迷宫版背包装备出售请求
type SvrMazeEquipSaleRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId     *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`             //用户id
	EquipGuids []int64 `protobuf:"varint,2,rep,name=equip_guids,json=equipGuids" json:"equip_guids,omitempty"` // 出售的装备guid列表
	TradeNum   *uint64 `protobuf:"varint,3,opt,name=trade_num,json=tradeNum" json:"trade_num,omitempty"`       // 交易单号
}

func (x *SvrMazeEquipSaleRQ) Reset() {
	*x = SvrMazeEquipSaleRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrMazeEquipSaleRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrMazeEquipSaleRQ) ProtoMessage() {}

func (x *SvrMazeEquipSaleRQ) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrMazeEquipSaleRQ.ProtoReflect.Descriptor instead.
func (*SvrMazeEquipSaleRQ) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{10}
}

func (x *SvrMazeEquipSaleRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrMazeEquipSaleRQ) GetEquipGuids() []int64 {
	if x != nil {
		return x.EquipGuids
	}
	return nil
}

func (x *SvrMazeEquipSaleRQ) GetTradeNum() uint64 {
	if x != nil && x.TradeNum != nil {
		return *x.TradeNum
	}
	return 0
}

//## 100009	UN_RPC_PACK_MAZE_EQUIP_SALE_RS
// 迷宫版背包装备出售应答
type SvrMazeEquipSaleRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  *uint64                `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`   //用户id
	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"` //结果
}

func (x *SvrMazeEquipSaleRS) Reset() {
	*x = SvrMazeEquipSaleRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipSvr_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SvrMazeEquipSaleRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SvrMazeEquipSaleRS) ProtoMessage() {}

func (x *SvrMazeEquipSaleRS) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipSvr_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SvrMazeEquipSaleRS.ProtoReflect.Descriptor instead.
func (*SvrMazeEquipSaleRS) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipSvr_proto_rawDescGZIP(), []int{11}
}

func (x *SvrMazeEquipSaleRS) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *SvrMazeEquipSaleRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

var File_server_MazeEquipSvr_proto protoreflect.FileDescriptor

var file_server_MazeEquipSvr_proto_rawDesc = []byte{
	0x0a, 0x19, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x53, 0x76, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x4d, 0x61, 0x7a,
	0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x76, 0x72, 0x1a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x66, 0x0a, 0x0c, 0x53, 0x76, 0x72, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49,
	0x6e, 0x66, 0x6f, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x3b,
	0x0a, 0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03,
	0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x76,
	0x72, 0x2e, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x63, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x67, 0x0a, 0x10, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x76, 0x72, 0x12,
	0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x70,
	0x75, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x70, 0x6f, 0x70,
	0x75, 0x70, 0x49, 0x64, 0x22, 0x35, 0x0a, 0x0d, 0x43, 0x6f, 0x6e, 0x64, 0x69, 0x74, 0x69, 0x6f,
	0x6e, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x22, 0xd7, 0x01, 0x0a, 0x10,
	0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x53, 0x76, 0x72,
	0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71,
	0x75, 0x69, 0x70, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0c, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x5f, 0x72, 0x65, 0x73, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x52, 0x65, 0x73, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x73,
	0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x75,
	0x69, 0x74, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x65, 0x61, 0x6c, 0x5f, 0x73, 0x74, 0x61,
	0x74, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x73, 0x65, 0x61, 0x6c, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x11, 0x53, 0x76, 0x72, 0x41, 0x64, 0x64,
	0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x52, 0x51, 0x12, 0x17, 0x0a, 0x07, 0x75,
	0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73,
	0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6c, 0x69,
	0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x53, 0x76, 0x72, 0x2e, 0x53, 0x76, 0x72, 0x45, 0x71, 0x75, 0x69, 0x70,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12,
	0x17, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x12, 0x21, 0x0a, 0x0c,
	0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x22,
	0xb7, 0x01, 0x0a, 0x11, 0x53, 0x76, 0x72, 0x41, 0x64, 0x64, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71,
	0x75, 0x69, 0x70, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66,
	0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72,
	0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x64, 0x12, 0x3d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69,
	0x70, 0x53, 0x76, 0x72, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x53, 0x76, 0x72, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74,
	0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70, 0x65, 0x22, 0xbc, 0x01, 0x0a, 0x16, 0x53, 0x76,
	0x72, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e,
	0x63, 0x65, 0x52, 0x51, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x39, 0x0a,
	0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x76, 0x72,
	0x2e, 0x53, 0x76, 0x72, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x17, 0x0a, 0x07, 0x6f, 0x70, 0x5f, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6f, 0x70, 0x54, 0x79, 0x70,
	0x65, 0x12, 0x21, 0x0a, 0x0c, 0x74, 0x72, 0x61, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0b, 0x74, 0x72, 0x61, 0x64, 0x65, 0x4e, 0x75,
	0x6d, 0x62, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x64, 0x65, 0x73, 0x63, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x04, 0x64, 0x65, 0x73, 0x63, 0x22, 0xa3, 0x01, 0x0a, 0x16, 0x53, 0x76, 0x72,
	0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63,
	0x65, 0x52, 0x53, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65,
	0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12,
	0x3d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53,
	0x76, 0x72, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x53, 0x76, 0x72, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4c, 0x69, 0x73, 0x74, 0x22, 0xe3,
	0x01, 0x0a, 0x16, 0x53, 0x76, 0x72, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x41,
	0x73, 0x73, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x52, 0x51, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65,
	0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72,
	0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x70, 0x6f, 0x73, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x12,
	0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x2e,
	0x0a, 0x13, 0x72, 0x65, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x64, 0x5f, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x72, 0x65, 0x70,
	0x6c, 0x61, 0x63, 0x65, 0x64, 0x45, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x1b,
	0x0a, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x73, 0x72, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x72, 0x63, 0x12, 0x27, 0x0a, 0x0f, 0x64,
	0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x65, 0x64, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x73, 0x18, 0x06,
	0x20, 0x03, 0x28, 0x03, 0x52, 0x0e, 0x64, 0x69, 0x73, 0x63, 0x61, 0x72, 0x64, 0x65, 0x64, 0x47,
	0x75, 0x69, 0x64, 0x73, 0x22, 0x64, 0x0a, 0x16, 0x53, 0x76, 0x72, 0x4d, 0x61, 0x7a, 0x65, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x41, 0x73, 0x73, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x52, 0x53, 0x12, 0x17,
	0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69,
	0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x6b, 0x0a, 0x12, 0x53, 0x76,
	0x72, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x51,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x03, 0x52, 0x0a,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x72,
	0x61, 0x64, 0x65, 0x5f, 0x6e, 0x75, 0x6d, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x08, 0x74,
	0x72, 0x61, 0x64, 0x65, 0x4e, 0x75, 0x6d, 0x22, 0x60, 0x0a, 0x12, 0x53, 0x76, 0x72, 0x4d, 0x61,
	0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x61, 0x6c, 0x65, 0x52, 0x53, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2a, 0xd6, 0x02, 0x0a, 0x16, 0x45, 0x4e,
	0x55, 0x4d, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x42, 0x41, 0x47, 0x5f, 0x4f, 0x50, 0x5f,
	0x54, 0x59, 0x50, 0x45, 0x12, 0x12, 0x0a, 0x0e, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55,
	0x49, 0x50, 0x5f, 0x46, 0x4f, 0x45, 0x10, 0x01, 0x12, 0x18, 0x0a, 0x14, 0x4d, 0x41, 0x5a, 0x45,
	0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x42, 0x4f, 0x58, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44,
	0x10, 0x02, 0x12, 0x14, 0x0a, 0x10, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x44, 0x52, 0x45, 0x53, 0x53,
	0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x03, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x41, 0x5a, 0x45,
	0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x53, 0x41, 0x4c, 0x45, 0x10, 0x04, 0x12, 0x1d, 0x0a,
	0x19, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x45, 0x51, 0x55, 0x49,
	0x50, 0x5f, 0x41, 0x55, 0x54, 0x4f, 0x5f, 0x44, 0x45, 0x4c, 0x10, 0x05, 0x12, 0x17, 0x0a, 0x13,
	0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x5f,
	0x44, 0x45, 0x4c, 0x10, 0x06, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x49, 0x4e,
	0x49, 0x54, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x07, 0x12, 0x17, 0x0a, 0x13, 0x4d, 0x41,
	0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x43, 0x4f, 0x4d, 0x50, 0x4f, 0x55, 0x4e,
	0x44, 0x10, 0x08, 0x12, 0x19, 0x0a, 0x15, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49,
	0x50, 0x5f, 0x50, 0x41, 0x53, 0x53, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44, 0x10, 0x09, 0x12, 0x1a,
	0x0a, 0x16, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x53, 0x57, 0x45,
	0x45, 0x50, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44, 0x10, 0x0a, 0x12, 0x22, 0x0a, 0x1e, 0x4d, 0x41,
	0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x4d, 0x4f, 0x4e, 0x53, 0x54, 0x45, 0x52,
	0x5f, 0x44, 0x45, 0x41, 0x54, 0x48, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44, 0x10, 0x0b, 0x12, 0x22,
	0x0a, 0x1e, 0x4d, 0x41, 0x5a, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x44, 0x52, 0x4f,
	0x50, 0x5f, 0x49, 0x54, 0x45, 0x4d, 0x5f, 0x42, 0x4f, 0x58, 0x5f, 0x41, 0x57, 0x41, 0x52, 0x44,
	0x10, 0x0c, 0x2a, 0x7a, 0x0a, 0x13, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x41, 0x44, 0x44, 0x5f,
	0x43, 0x4f, 0x4e, 0x44, 0x49, 0x54, 0x49, 0x4f, 0x4e, 0x12, 0x10, 0x0a, 0x0c, 0x42, 0x45, 0x5f,
	0x53, 0x55, 0x52, 0x45, 0x5f, 0x53, 0x55, 0x49, 0x54, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x41,
	0x53, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x53, 0x55, 0x49, 0x54, 0x10, 0x02, 0x12, 0x19, 0x0a, 0x15,
	0x41, 0x53, 0x53, 0x49, 0x47, 0x4e, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x5f, 0x53, 0x55, 0x42,
	0x5f, 0x54, 0x59, 0x50, 0x45, 0x10, 0x04, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x50, 0x45, 0x43, 0x49,
	0x41, 0x4c, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x08, 0x12, 0x12, 0x0a, 0x0e, 0x49, 0x4e,
	0x53, 0x54, 0x41, 0x4e, 0x43, 0x45, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x10, 0x42, 0x3b,
	0x5a, 0x27, 0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76,
	0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x4d, 0x61, 0x7a,
	0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x76, 0x72, 0xaa, 0x02, 0x0f, 0x50, 0x62, 0x2e, 0x4d,
	0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x76, 0x72,
}

var (
	file_server_MazeEquipSvr_proto_rawDescOnce sync.Once
	file_server_MazeEquipSvr_proto_rawDescData = file_server_MazeEquipSvr_proto_rawDesc
)

func file_server_MazeEquipSvr_proto_rawDescGZIP() []byte {
	file_server_MazeEquipSvr_proto_rawDescOnce.Do(func() {
		file_server_MazeEquipSvr_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_MazeEquipSvr_proto_rawDescData)
	})
	return file_server_MazeEquipSvr_proto_rawDescData
}

var file_server_MazeEquipSvr_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_server_MazeEquipSvr_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_server_MazeEquipSvr_proto_goTypes = []interface{}{
	(ENUM_EQUIP_BAG_OP_TYPE)(0),    // 0: MazeEquipSvr.ENUM_EQUIP_BAG_OP_TYPE
	(EQUIP_ADD_CONDITION)(0),       // 1: MazeEquipSvr.EQUIP_ADD_CONDITION
	(*SvrEquipInfo)(nil),           // 2: MazeEquipSvr.SvrEquipInfo
	(*EquipInstanceSvr)(nil),       // 3: MazeEquipSvr.EquipInstanceSvr
	(*ConditionInfo)(nil),          // 4: MazeEquipSvr.ConditionInfo
	(*MazeEquipInfoSvr)(nil),       // 5: MazeEquipSvr.MazeEquipInfoSvr
	(*SvrAddMazeEquipRQ)(nil),      // 6: MazeEquipSvr.SvrAddMazeEquipRQ
	(*SvrAddMazeEquipRS)(nil),      // 7: MazeEquipSvr.SvrAddMazeEquipRS
	(*SvrMazeEquipInstanceRQ)(nil), // 8: MazeEquipSvr.SvrMazeEquipInstanceRQ
	(*SvrMazeEquipInstanceRS)(nil), // 9: MazeEquipSvr.SvrMazeEquipInstanceRS
	(*SvrMazeEquipAssembleRQ)(nil), // 10: MazeEquipSvr.SvrMazeEquipAssembleRQ
	(*SvrMazeEquipAssembleRS)(nil), // 11: MazeEquipSvr.SvrMazeEquipAssembleRS
	(*SvrMazeEquipSaleRQ)(nil),     // 12: MazeEquipSvr.SvrMazeEquipSaleRQ
	(*SvrMazeEquipSaleRS)(nil),     // 13: MazeEquipSvr.SvrMazeEquipSaleRS
	(*MessageType.ErrorInfo)(nil),  // 14: MessageType.ErrorInfo
}
var file_server_MazeEquipSvr_proto_depIdxs = []int32{
	4,  // 0: MazeEquipSvr.SvrEquipInfo.conditions:type_name -> MazeEquipSvr.ConditionInfo
	2,  // 1: MazeEquipSvr.SvrAddMazeEquipRQ.equip_list:type_name -> MazeEquipSvr.SvrEquipInfo
	14, // 2: MazeEquipSvr.SvrAddMazeEquipRS.err_info:type_name -> MessageType.ErrorInfo
	5,  // 3: MazeEquipSvr.SvrAddMazeEquipRS.equip_list:type_name -> MazeEquipSvr.MazeEquipInfoSvr
	2,  // 4: MazeEquipSvr.SvrMazeEquipInstanceRQ.equip_list:type_name -> MazeEquipSvr.SvrEquipInfo
	14, // 5: MazeEquipSvr.SvrMazeEquipInstanceRS.err_info:type_name -> MessageType.ErrorInfo
	3,  // 6: MazeEquipSvr.SvrMazeEquipInstanceRS.equip_list:type_name -> MazeEquipSvr.EquipInstanceSvr
	14, // 7: MazeEquipSvr.SvrMazeEquipAssembleRS.err_info:type_name -> MessageType.ErrorInfo
	14, // 8: MazeEquipSvr.SvrMazeEquipSaleRS.err_info:type_name -> MessageType.ErrorInfo
	9,  // [9:9] is the sub-list for method output_type
	9,  // [9:9] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_server_MazeEquipSvr_proto_init() }
func file_server_MazeEquipSvr_proto_init() {
	if File_server_MazeEquipSvr_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_MazeEquipSvr_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrEquipInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipInstanceSvr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ConditionInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeEquipInfoSvr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrAddMazeEquipRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrAddMazeEquipRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrMazeEquipInstanceRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrMazeEquipInstanceRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrMazeEquipAssembleRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrMazeEquipAssembleRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrMazeEquipSaleRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipSvr_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SvrMazeEquipSaleRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_MazeEquipSvr_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_MazeEquipSvr_proto_goTypes,
		DependencyIndexes: file_server_MazeEquipSvr_proto_depIdxs,
		EnumInfos:         file_server_MazeEquipSvr_proto_enumTypes,
		MessageInfos:      file_server_MazeEquipSvr_proto_msgTypes,
	}.Build()
	File_server_MazeEquipSvr_proto = out.File
	file_server_MazeEquipSvr_proto_rawDesc = nil
	file_server_MazeEquipSvr_proto_goTypes = nil
	file_server_MazeEquipSvr_proto_depIdxs = nil
}
