// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: server/MazeEquipCache.proto

package MazeEquipCache

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//装备信息
type MazeEquipInfoDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipId      *int32          `protobuf:"varint,1,opt,name=equip_id,json=equipId" json:"equip_id,omitempty"`                  //装备配置id
	EquipGuid    *int64          `protobuf:"varint,2,opt,name=equip_guid,json=equipGuid" json:"equip_guid,omitempty"`            //实例id
	BaseAttrs    []*BaseAttrInfo `protobuf:"bytes,3,rep,name=base_attrs,json=baseAttrs" json:"base_attrs,omitempty"`             //装备基础属性
	EquipSubType *int32          `protobuf:"varint,4,opt,name=equip_sub_type,json=equipSubType" json:"equip_sub_type,omitempty"` //装备子类型
	SuitId       *int32          `protobuf:"varint,5,opt,name=suit_id,json=suitId" json:"suit_id,omitempty"`                     //套装id
	RuleId       *int32          `protobuf:"varint,6,opt,name=rule_id,json=ruleId" json:"rule_id,omitempty"`                     //装备特殊逻辑id
	EquipScore   *int32          `protobuf:"varint,7,opt,name=equip_score,json=equipScore" json:"equip_score,omitempty"`         //装备分值
	MakeTime     *int64          `protobuf:"varint,8,opt,name=make_time,json=makeTime" json:"make_time,omitempty"`               //装备创建时间
}

func (x *MazeEquipInfoDb) Reset() {
	*x = MazeEquipInfoDb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeEquipInfoDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeEquipInfoDb) ProtoMessage() {}

func (x *MazeEquipInfoDb) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeEquipInfoDb.ProtoReflect.Descriptor instead.
func (*MazeEquipInfoDb) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{0}
}

func (x *MazeEquipInfoDb) GetEquipId() int32 {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return 0
}

func (x *MazeEquipInfoDb) GetEquipGuid() int64 {
	if x != nil && x.EquipGuid != nil {
		return *x.EquipGuid
	}
	return 0
}

func (x *MazeEquipInfoDb) GetBaseAttrs() []*BaseAttrInfo {
	if x != nil {
		return x.BaseAttrs
	}
	return nil
}

func (x *MazeEquipInfoDb) GetEquipSubType() int32 {
	if x != nil && x.EquipSubType != nil {
		return *x.EquipSubType
	}
	return 0
}

func (x *MazeEquipInfoDb) GetSuitId() int32 {
	if x != nil && x.SuitId != nil {
		return *x.SuitId
	}
	return 0
}

func (x *MazeEquipInfoDb) GetRuleId() int32 {
	if x != nil && x.RuleId != nil {
		return *x.RuleId
	}
	return 0
}

func (x *MazeEquipInfoDb) GetEquipScore() int32 {
	if x != nil && x.EquipScore != nil {
		return *x.EquipScore
	}
	return 0
}

func (x *MazeEquipInfoDb) GetMakeTime() int64 {
	if x != nil && x.MakeTime != nil {
		return *x.MakeTime
	}
	return 0
}

//基础属性
type BaseAttrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrGroup    *int32           `protobuf:"varint,1,opt,name=attr_group,json=attrGroup" json:"attr_group,omitempty"`           //词条id
	ShowAttrList []*EquipAttrInfo `protobuf:"bytes,2,rep,name=show_attr_list,json=showAttrList" json:"show_attr_list,omitempty"` //基础显示属性列表
	RealAttrList []*EquipAttrInfo `protobuf:"bytes,3,rep,name=real_attr_list,json=realAttrList" json:"real_attr_list,omitempty"` //基础真实属性列表
	AttrType     *int32           `protobuf:"varint,4,opt,name=attr_type,json=attrType" json:"attr_type,omitempty"`              //属性类型 ENUM_EQUIP_ATTR_TYPE
	RandWeight   *int32           `protobuf:"varint,5,opt,name=rand_weight,json=randWeight" json:"rand_weight,omitempty"`        //随机值
	Index        *int32           `protobuf:"varint,6,opt,name=index" json:"index,omitempty"`                                    //序号
}

func (x *BaseAttrInfo) Reset() {
	*x = BaseAttrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BaseAttrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseAttrInfo) ProtoMessage() {}

func (x *BaseAttrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseAttrInfo.ProtoReflect.Descriptor instead.
func (*BaseAttrInfo) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{1}
}

func (x *BaseAttrInfo) GetAttrGroup() int32 {
	if x != nil && x.AttrGroup != nil {
		return *x.AttrGroup
	}
	return 0
}

func (x *BaseAttrInfo) GetShowAttrList() []*EquipAttrInfo {
	if x != nil {
		return x.ShowAttrList
	}
	return nil
}

func (x *BaseAttrInfo) GetRealAttrList() []*EquipAttrInfo {
	if x != nil {
		return x.RealAttrList
	}
	return nil
}

func (x *BaseAttrInfo) GetAttrType() int32 {
	if x != nil && x.AttrType != nil {
		return *x.AttrType
	}
	return 0
}

func (x *BaseAttrInfo) GetRandWeight() int32 {
	if x != nil && x.RandWeight != nil {
		return *x.RandWeight
	}
	return 0
}

func (x *BaseAttrInfo) GetIndex() int32 {
	if x != nil && x.Index != nil {
		return *x.Index
	}
	return 0
}

type EquipAttrInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrId    *int32 `protobuf:"varint,1,opt,name=attr_id,json=attrId" json:"attr_id,omitempty"`          //属性id
	AttrValue *int64 `protobuf:"varint,2,opt,name=attr_value,json=attrValue" json:"attr_value,omitempty"` //当前值
}

func (x *EquipAttrInfo) Reset() {
	*x = EquipAttrInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EquipAttrInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EquipAttrInfo) ProtoMessage() {}

func (x *EquipAttrInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EquipAttrInfo.ProtoReflect.Descriptor instead.
func (*EquipAttrInfo) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{2}
}

func (x *EquipAttrInfo) GetAttrId() int32 {
	if x != nil && x.AttrId != nil {
		return *x.AttrId
	}
	return 0
}

func (x *EquipAttrInfo) GetAttrValue() int64 {
	if x != nil && x.AttrValue != nil {
		return *x.AttrValue
	}
	return 0
}

// 装备位信息
type MazeEquipSlotDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos   *int32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`     // 装备位Id
	Level *int32 `protobuf:"varint,2,opt,name=level" json:"level,omitempty"` // 装备位等级
}

func (x *MazeEquipSlotDb) Reset() {
	*x = MazeEquipSlotDb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeEquipSlotDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeEquipSlotDb) ProtoMessage() {}

func (x *MazeEquipSlotDb) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeEquipSlotDb.ProtoReflect.Descriptor instead.
func (*MazeEquipSlotDb) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{3}
}

func (x *MazeEquipSlotDb) GetPos() int32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *MazeEquipSlotDb) GetLevel() int32 {
	if x != nil && x.Level != nil {
		return *x.Level
	}
	return 0
}

// 装备位装配信息
type MazeEquipPosDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos          *int32 `protobuf:"varint,1,opt,name=pos" json:"pos,omitempty"`                                       // 装备位
	EquipGuid    *int64 `protobuf:"varint,2,opt,name=equip_guid,json=equipGuid" json:"equip_guid,omitempty"`          // 装备guid
	EquipId      *int32 `protobuf:"varint,3,opt,name=equip_id,json=equipId" json:"equip_id,omitempty"`                // 装备配置Id
	ActivateMask *int32 `protobuf:"varint,4,opt,name=activate_mask,json=activateMask" json:"activate_mask,omitempty"` //激活状态 1=五行激活 2=伤害套装激活
}

func (x *MazeEquipPosDb) Reset() {
	*x = MazeEquipPosDb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeEquipPosDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeEquipPosDb) ProtoMessage() {}

func (x *MazeEquipPosDb) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeEquipPosDb.ProtoReflect.Descriptor instead.
func (*MazeEquipPosDb) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{4}
}

func (x *MazeEquipPosDb) GetPos() int32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *MazeEquipPosDb) GetEquipGuid() int64 {
	if x != nil && x.EquipGuid != nil {
		return *x.EquipGuid
	}
	return 0
}

func (x *MazeEquipPosDb) GetEquipId() int32 {
	if x != nil && x.EquipId != nil {
		return *x.EquipId
	}
	return 0
}

func (x *MazeEquipPosDb) GetActivateMask() int32 {
	if x != nil && x.ActivateMask != nil {
		return *x.ActivateMask
	}
	return 0
}

// 装配位打包结构
type MazeEquipPosInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	EquipPos      *MazeEquipSlotDb `protobuf:"bytes,1,opt,name=equip_pos,json=equipPos" json:"equip_pos,omitempty"`                  // 装备位存储
	EquipLoadInfo *MazeEquipPosDb  `protobuf:"bytes,2,opt,name=equip_load_info,json=equipLoadInfo" json:"equip_load_info,omitempty"` // 装配信息
	EquipInfo     *MazeEquipInfoDb `protobuf:"bytes,3,opt,name=equip_info,json=equipInfo" json:"equip_info,omitempty"`               // 装备详情存储
	Force         *int64           `protobuf:"varint,4,opt,name=force" json:"force,omitempty"`                                       // 装备武力值
}

func (x *MazeEquipPosInfo) Reset() {
	*x = MazeEquipPosInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeEquipPosInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeEquipPosInfo) ProtoMessage() {}

func (x *MazeEquipPosInfo) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeEquipPosInfo.ProtoReflect.Descriptor instead.
func (*MazeEquipPosInfo) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{5}
}

func (x *MazeEquipPosInfo) GetEquipPos() *MazeEquipSlotDb {
	if x != nil {
		return x.EquipPos
	}
	return nil
}

func (x *MazeEquipPosInfo) GetEquipLoadInfo() *MazeEquipPosDb {
	if x != nil {
		return x.EquipLoadInfo
	}
	return nil
}

func (x *MazeEquipPosInfo) GetEquipInfo() *MazeEquipInfoDb {
	if x != nil {
		return x.EquipInfo
	}
	return nil
}

func (x *MazeEquipPosInfo) GetForce() int64 {
	if x != nil && x.Force != nil {
		return *x.Force
	}
	return 0
}

// 人偶装配信息
type MazeAssembleDb struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MazeEquips     []*MazeEquipPosInfo `protobuf:"bytes,1,rep,name=maze_equips,json=mazeEquips" json:"maze_equips,omitempty"`                // 已装备列表
	CurSuitIndex   *int32              `protobuf:"varint,2,opt,name=cur_suit_index,json=curSuitIndex" json:"cur_suit_index,omitempty"`       // 从1开始
	SwitchSuitTime *int64              `protobuf:"varint,3,opt,name=switch_suit_time,json=switchSuitTime" json:"switch_suit_time,omitempty"` // 切换套装时间
	EpEnSuitId     *int32              `protobuf:"varint,4,opt,name=ep_en_suit_id,json=epEnSuitId" json:"ep_en_suit_id,omitempty"`           // 装备位强化套装Id
	EpSuitId       *int32              `protobuf:"varint,5,opt,name=ep_suit_id,json=epSuitId" json:"ep_suit_id,omitempty"`                   // 装备套装Id
}

func (x *MazeAssembleDb) Reset() {
	*x = MazeAssembleDb{}
	if protoimpl.UnsafeEnabled {
		mi := &file_server_MazeEquipCache_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeAssembleDb) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeAssembleDb) ProtoMessage() {}

func (x *MazeAssembleDb) ProtoReflect() protoreflect.Message {
	mi := &file_server_MazeEquipCache_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeAssembleDb.ProtoReflect.Descriptor instead.
func (*MazeAssembleDb) Descriptor() ([]byte, []int) {
	return file_server_MazeEquipCache_proto_rawDescGZIP(), []int{6}
}

func (x *MazeAssembleDb) GetMazeEquips() []*MazeEquipPosInfo {
	if x != nil {
		return x.MazeEquips
	}
	return nil
}

func (x *MazeAssembleDb) GetCurSuitIndex() int32 {
	if x != nil && x.CurSuitIndex != nil {
		return *x.CurSuitIndex
	}
	return 0
}

func (x *MazeAssembleDb) GetSwitchSuitTime() int64 {
	if x != nil && x.SwitchSuitTime != nil {
		return *x.SwitchSuitTime
	}
	return 0
}

func (x *MazeAssembleDb) GetEpEnSuitId() int32 {
	if x != nil && x.EpEnSuitId != nil {
		return *x.EpEnSuitId
	}
	return 0
}

func (x *MazeAssembleDb) GetEpSuitId() int32 {
	if x != nil && x.EpSuitId != nil {
		return *x.EpSuitId
	}
	return 0
}

var File_server_MazeEquipCache_proto protoreflect.FileDescriptor

var file_server_MazeEquipCache_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e, 0x4d,
	0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x22, 0x9e, 0x02,
	0x0a, 0x0f, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x44,
	0x62, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a,
	0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x67, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x47, 0x75, 0x69, 0x64, 0x12, 0x3b, 0x0a, 0x0a, 0x62,
	0x61, 0x73, 0x65, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32,
	0x1c, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65,
	0x2e, 0x42, 0x61, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x62,
	0x61, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x65, 0x71, 0x75, 0x69,
	0x70, 0x5f, 0x73, 0x75, 0x62, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x0c, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x75, 0x62, 0x54, 0x79, 0x70, 0x65, 0x12, 0x17,
	0x0a, 0x07, 0x73, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x06, 0x73, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x72, 0x75, 0x6c, 0x65, 0x5f,
	0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x72, 0x75, 0x6c, 0x65, 0x49, 0x64,
	0x12, 0x1f, 0x0a, 0x0b, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6d, 0x61, 0x6b, 0x65, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x6d, 0x61, 0x6b, 0x65, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x8b,
	0x02, 0x0a, 0x0c, 0x42, 0x61, 0x73, 0x65, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x67, 0x72, 0x6f, 0x75, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x47, 0x72, 0x6f, 0x75, 0x70, 0x12, 0x43,
	0x0a, 0x0e, 0x73, 0x68, 0x6f, 0x77, 0x5f, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x6c, 0x69, 0x73, 0x74,
	0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x45, 0x71, 0x75, 0x69, 0x70, 0x41, 0x74, 0x74,
	0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x73, 0x68, 0x6f, 0x77, 0x41, 0x74, 0x74, 0x72, 0x4c,
	0x69, 0x73, 0x74, 0x12, 0x43, 0x0a, 0x0e, 0x72, 0x65, 0x61, 0x6c, 0x5f, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x6c, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x4d, 0x61,
	0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x72, 0x65, 0x61, 0x6c,
	0x41, 0x74, 0x74, 0x72, 0x4c, 0x69, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x61, 0x74, 0x74, 0x72,
	0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x61, 0x74, 0x74,
	0x72, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x61, 0x6e, 0x64, 0x5f, 0x77, 0x65,
	0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x72, 0x61, 0x6e, 0x64,
	0x57, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x22, 0x47, 0x0a, 0x0d,
	0x45, 0x71, 0x75, 0x69, 0x70, 0x41, 0x74, 0x74, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a,
	0x07, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06,
	0x61, 0x74, 0x74, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76,
	0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72,
	0x56, 0x61, 0x6c, 0x75, 0x65, 0x22, 0x39, 0x0a, 0x0f, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x22, 0x81, 0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x50, 0x6f,
	0x73, 0x44, 0x62, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x03, 0x70, 0x6f, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x67,
	0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x47, 0x75, 0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x64,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65, 0x5f, 0x6d, 0x61, 0x73, 0x6b,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0c, 0x61, 0x63, 0x74, 0x69, 0x76, 0x61, 0x74, 0x65,
	0x4d, 0x61, 0x73, 0x6b, 0x22, 0xee, 0x01, 0x0a, 0x10, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75,
	0x69, 0x70, 0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x3c, 0x0a, 0x09, 0x65, 0x71, 0x75,
	0x69, 0x70, 0x5f, 0x70, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4d,
	0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x4d, 0x61,
	0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x53, 0x6c, 0x6f, 0x74, 0x44, 0x62, 0x52, 0x08, 0x65,
	0x71, 0x75, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x12, 0x46, 0x0a, 0x0f, 0x65, 0x71, 0x75, 0x69, 0x70,
	0x5f, 0x6c, 0x6f, 0x61, 0x64, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x1e, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68,
	0x65, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x44, 0x62,
	0x52, 0x0d, 0x65, 0x71, 0x75, 0x69, 0x70, 0x4c, 0x6f, 0x61, 0x64, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x3e, 0x0a, 0x0a, 0x65, 0x71, 0x75, 0x69, 0x70, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1f, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43,
	0x61, 0x63, 0x68, 0x65, 0x2e, 0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e,
	0x66, 0x6f, 0x44, 0x62, 0x52, 0x09, 0x65, 0x71, 0x75, 0x69, 0x70, 0x49, 0x6e, 0x66, 0x6f, 0x12,
	0x14, 0x0a, 0x05, 0x66, 0x6f, 0x72, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05,
	0x66, 0x6f, 0x72, 0x63, 0x65, 0x22, 0xe4, 0x01, 0x0a, 0x0e, 0x4d, 0x61, 0x7a, 0x65, 0x41, 0x73,
	0x73, 0x65, 0x6d, 0x62, 0x6c, 0x65, 0x44, 0x62, 0x12, 0x41, 0x0a, 0x0b, 0x6d, 0x61, 0x7a, 0x65,
	0x5f, 0x65, 0x71, 0x75, 0x69, 0x70, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x20, 0x2e,
	0x4d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x4d,
	0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x50, 0x6f, 0x73, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x0a, 0x6d, 0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x73, 0x12, 0x24, 0x0a, 0x0e, 0x63,
	0x75, 0x72, 0x5f, 0x73, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x6e, 0x64, 0x65, 0x78, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x0c, 0x63, 0x75, 0x72, 0x53, 0x75, 0x69, 0x74, 0x49, 0x6e, 0x64, 0x65,
	0x78, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x77, 0x69, 0x74, 0x63, 0x68, 0x5f, 0x73, 0x75, 0x69, 0x74,
	0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e, 0x73, 0x77, 0x69,
	0x74, 0x63, 0x68, 0x53, 0x75, 0x69, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x21, 0x0a, 0x0d, 0x65,
	0x70, 0x5f, 0x65, 0x6e, 0x5f, 0x73, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x0a, 0x65, 0x70, 0x45, 0x6e, 0x53, 0x75, 0x69, 0x74, 0x49, 0x64, 0x12, 0x1c,
	0x0a, 0x0a, 0x65, 0x70, 0x5f, 0x73, 0x75, 0x69, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x08, 0x65, 0x70, 0x53, 0x75, 0x69, 0x74, 0x49, 0x64, 0x42, 0x3f, 0x5a, 0x29,
	0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72, 0x2f, 0x4d, 0x61, 0x7a, 0x65, 0x45,
	0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65, 0xaa, 0x02, 0x11, 0x50, 0x62, 0x2e, 0x4d,
	0x61, 0x7a, 0x65, 0x45, 0x71, 0x75, 0x69, 0x70, 0x43, 0x61, 0x63, 0x68, 0x65,
}

var (
	file_server_MazeEquipCache_proto_rawDescOnce sync.Once
	file_server_MazeEquipCache_proto_rawDescData = file_server_MazeEquipCache_proto_rawDesc
)

func file_server_MazeEquipCache_proto_rawDescGZIP() []byte {
	file_server_MazeEquipCache_proto_rawDescOnce.Do(func() {
		file_server_MazeEquipCache_proto_rawDescData = protoimpl.X.CompressGZIP(file_server_MazeEquipCache_proto_rawDescData)
	})
	return file_server_MazeEquipCache_proto_rawDescData
}

var file_server_MazeEquipCache_proto_msgTypes = make([]protoimpl.MessageInfo, 7)
var file_server_MazeEquipCache_proto_goTypes = []interface{}{
	(*MazeEquipInfoDb)(nil),  // 0: MazeEquipCache.MazeEquipInfoDb
	(*BaseAttrInfo)(nil),     // 1: MazeEquipCache.BaseAttrInfo
	(*EquipAttrInfo)(nil),    // 2: MazeEquipCache.EquipAttrInfo
	(*MazeEquipSlotDb)(nil),  // 3: MazeEquipCache.MazeEquipSlotDb
	(*MazeEquipPosDb)(nil),   // 4: MazeEquipCache.MazeEquipPosDb
	(*MazeEquipPosInfo)(nil), // 5: MazeEquipCache.MazeEquipPosInfo
	(*MazeAssembleDb)(nil),   // 6: MazeEquipCache.MazeAssembleDb
}
var file_server_MazeEquipCache_proto_depIdxs = []int32{
	1, // 0: MazeEquipCache.MazeEquipInfoDb.base_attrs:type_name -> MazeEquipCache.BaseAttrInfo
	2, // 1: MazeEquipCache.BaseAttrInfo.show_attr_list:type_name -> MazeEquipCache.EquipAttrInfo
	2, // 2: MazeEquipCache.BaseAttrInfo.real_attr_list:type_name -> MazeEquipCache.EquipAttrInfo
	3, // 3: MazeEquipCache.MazeEquipPosInfo.equip_pos:type_name -> MazeEquipCache.MazeEquipSlotDb
	4, // 4: MazeEquipCache.MazeEquipPosInfo.equip_load_info:type_name -> MazeEquipCache.MazeEquipPosDb
	0, // 5: MazeEquipCache.MazeEquipPosInfo.equip_info:type_name -> MazeEquipCache.MazeEquipInfoDb
	5, // 6: MazeEquipCache.MazeAssembleDb.maze_equips:type_name -> MazeEquipCache.MazeEquipPosInfo
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_server_MazeEquipCache_proto_init() }
func file_server_MazeEquipCache_proto_init() {
	if File_server_MazeEquipCache_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_server_MazeEquipCache_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeEquipInfoDb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipCache_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BaseAttrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipCache_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EquipAttrInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipCache_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeEquipSlotDb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipCache_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeEquipPosDb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipCache_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeEquipPosInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_server_MazeEquipCache_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeAssembleDb); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_server_MazeEquipCache_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   7,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_server_MazeEquipCache_proto_goTypes,
		DependencyIndexes: file_server_MazeEquipCache_proto_depIdxs,
		MessageInfos:      file_server_MazeEquipCache_proto_msgTypes,
	}.Build()
	File_server_MazeEquipCache_proto = out.File
	file_server_MazeEquipCache_proto_rawDesc = nil
	file_server_MazeEquipCache_proto_goTypes = nil
	file_server_MazeEquipCache_proto_depIdxs = nil
}
