// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/MazeCommon.proto

package MazeCommon

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type MazeItemType int32

const (
	MazeItemType_ENUM_INVALID MazeItemType = 0
	MazeItemType_ENUM_GOODS   MazeItemType = 1 //物资
	MazeItemType_ENUM_EQUIP   MazeItemType = 2 //装备
)

// Enum value maps for MazeItemType.
var (
	MazeItemType_name = map[int32]string{
		0: "ENUM_INVALID",
		1: "ENUM_GOODS",
		2: "ENUM_EQUIP",
	}
	MazeItemType_value = map[string]int32{
		"ENUM_INVALID": 0,
		"ENUM_GOODS":   1,
		"ENUM_EQUIP":   2,
	}
)

func (x MazeItemType) Enum() *MazeItemType {
	p := new(MazeItemType)
	*p = x
	return p
}

func (x MazeItemType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MazeItemType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_MazeCommon_proto_enumTypes[0].Descriptor()
}

func (MazeItemType) Type() protoreflect.EnumType {
	return &file_common_MazeCommon_proto_enumTypes[0]
}

func (x MazeItemType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *MazeItemType) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = MazeItemType(num)
	return nil
}

// Deprecated: Use MazeItemType.Descriptor instead.
func (MazeItemType) EnumDescriptor() ([]byte, []int) {
	return file_common_MazeCommon_proto_rawDescGZIP(), []int{0}
}

type MazeItem struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ItemId    *int32  `protobuf:"varint,1,opt,name=item_id,json=itemId" json:"item_id,omitempty"`         //物品Id
	Count     *int64  `protobuf:"varint,2,opt,name=count" json:"count,omitempty"`                         //物品数量
	Guid      *int64  `protobuf:"varint,3,opt,name=guid" json:"guid,omitempty"`                           //guid
	ItemName  *string `protobuf:"bytes,4,opt,name=item_name,json=itemName" json:"item_name,omitempty"`    //物品名称
	AtlasName *string `protobuf:"bytes,5,opt,name=atlas_name,json=atlasName" json:"atlas_name,omitempty"` //图集名
	IconName  *string `protobuf:"bytes,6,opt,name=icon_name,json=iconName" json:"icon_name,omitempty"`    // 图标名
	Quality   *int32  `protobuf:"varint,7,opt,name=quality" json:"quality,omitempty"`                     // 品质
}

func (x *MazeItem) Reset() {
	*x = MazeItem{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MazeCommon_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeItem) ProtoMessage() {}

func (x *MazeItem) ProtoReflect() protoreflect.Message {
	mi := &file_common_MazeCommon_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeItem.ProtoReflect.Descriptor instead.
func (*MazeItem) Descriptor() ([]byte, []int) {
	return file_common_MazeCommon_proto_rawDescGZIP(), []int{0}
}

func (x *MazeItem) GetItemId() int32 {
	if x != nil && x.ItemId != nil {
		return *x.ItemId
	}
	return 0
}

func (x *MazeItem) GetCount() int64 {
	if x != nil && x.Count != nil {
		return *x.Count
	}
	return 0
}

func (x *MazeItem) GetGuid() int64 {
	if x != nil && x.Guid != nil {
		return *x.Guid
	}
	return 0
}

func (x *MazeItem) GetItemName() string {
	if x != nil && x.ItemName != nil {
		return *x.ItemName
	}
	return ""
}

func (x *MazeItem) GetAtlasName() string {
	if x != nil && x.AtlasName != nil {
		return *x.AtlasName
	}
	return ""
}

func (x *MazeItem) GetIconName() string {
	if x != nil && x.IconName != nil {
		return *x.IconName
	}
	return ""
}

func (x *MazeItem) GetQuality() int32 {
	if x != nil && x.Quality != nil {
		return *x.Quality
	}
	return 0
}

type MazeCount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CurCount   *int32 `protobuf:"varint,1,opt,name=cur_count,json=curCount" json:"cur_count,omitempty"`       /// 当前数量
	TotalCount *int32 `protobuf:"varint,2,opt,name=total_count,json=totalCount" json:"total_count,omitempty"` /// 总数
}

func (x *MazeCount) Reset() {
	*x = MazeCount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MazeCommon_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *MazeCount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MazeCount) ProtoMessage() {}

func (x *MazeCount) ProtoReflect() protoreflect.Message {
	mi := &file_common_MazeCommon_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MazeCount.ProtoReflect.Descriptor instead.
func (*MazeCount) Descriptor() ([]byte, []int) {
	return file_common_MazeCommon_proto_rawDescGZIP(), []int{1}
}

func (x *MazeCount) GetCurCount() int32 {
	if x != nil && x.CurCount != nil {
		return *x.CurCount
	}
	return 0
}

func (x *MazeCount) GetTotalCount() int32 {
	if x != nil && x.TotalCount != nil {
		return *x.TotalCount
	}
	return 0
}

type Attr struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AttrId    *int32  `protobuf:"varint,1,opt,name=attr_id,json=attrId" json:"attr_id,omitempty"`          // 比例对应的类型，根据业务分配，实际用d，会用到比例值和对放用户id
	AttrValue *int32  `protobuf:"varint,2,opt,name=attr_value,json=attrValue" json:"attr_value,omitempty"` // 带比例，培育用户
	PeerUid   *uint64 `protobuf:"varint,3,opt,name=peer_uid,json=peerUid" json:"peer_uid,omitempty"`       /// 对方用户id
}

func (x *Attr) Reset() {
	*x = Attr{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_MazeCommon_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Attr) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Attr) ProtoMessage() {}

func (x *Attr) ProtoReflect() protoreflect.Message {
	mi := &file_common_MazeCommon_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Attr.ProtoReflect.Descriptor instead.
func (*Attr) Descriptor() ([]byte, []int) {
	return file_common_MazeCommon_proto_rawDescGZIP(), []int{2}
}

func (x *Attr) GetAttrId() int32 {
	if x != nil && x.AttrId != nil {
		return *x.AttrId
	}
	return 0
}

func (x *Attr) GetAttrValue() int32 {
	if x != nil && x.AttrValue != nil {
		return *x.AttrValue
	}
	return 0
}

func (x *Attr) GetPeerUid() uint64 {
	if x != nil && x.PeerUid != nil {
		return *x.PeerUid
	}
	return 0
}

var File_common_MazeCommon_proto protoreflect.FileDescriptor

var file_common_MazeCommon_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d, 0x61, 0x7a, 0x65, 0x43, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x4d, 0x61, 0x7a, 0x65, 0x43,
	0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0xc0, 0x01, 0x0a, 0x08, 0x4d, 0x61, 0x7a, 0x65, 0x49, 0x74,
	0x65, 0x6d, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x74, 0x65, 0x6d, 0x49, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x12, 0x0a, 0x04, 0x67, 0x75, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52,
	0x04, 0x67, 0x75, 0x69, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x74, 0x65, 0x6d, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x74, 0x65, 0x6d, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x61, 0x74, 0x6c, 0x61, 0x73, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x1b, 0x0a, 0x09, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x06,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x69, 0x63, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x07, 0x71, 0x75, 0x61, 0x6c, 0x69, 0x74, 0x79, 0x22, 0x49, 0x0a, 0x09, 0x4d, 0x61, 0x7a, 0x65,
	0x43, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x63, 0x75, 0x72, 0x5f, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x63, 0x75, 0x72, 0x43, 0x6f, 0x75,
	0x6e, 0x74, 0x12, 0x1f, 0x0a, 0x0b, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0a, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x43, 0x6f,
	0x75, 0x6e, 0x74, 0x22, 0x59, 0x0a, 0x04, 0x41, 0x74, 0x74, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x61,
	0x74, 0x74, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x61, 0x74,
	0x74, 0x72, 0x49, 0x64, 0x12, 0x1d, 0x0a, 0x0a, 0x61, 0x74, 0x74, 0x72, 0x5f, 0x76, 0x61, 0x6c,
	0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x61, 0x74, 0x74, 0x72, 0x56, 0x61,
	0x6c, 0x75, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x75, 0x69, 0x64, 0x18,
	0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x70, 0x65, 0x65, 0x72, 0x55, 0x69, 0x64, 0x2a, 0x40,
	0x0a, 0x0c, 0x4d, 0x61, 0x7a, 0x65, 0x49, 0x74, 0x65, 0x6d, 0x54, 0x79, 0x70, 0x65, 0x12, 0x10,
	0x0a, 0x0c, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x49, 0x4e, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x10, 0x00,
	0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x47, 0x4f, 0x4f, 0x44, 0x53, 0x10, 0x01,
	0x12, 0x0e, 0x0a, 0x0a, 0x45, 0x4e, 0x55, 0x4d, 0x5f, 0x45, 0x51, 0x55, 0x49, 0x50, 0x10, 0x02,
	0x42, 0x37, 0x5a, 0x25, 0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65,
	0x72, 0x76, 0x65, 0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d,
	0x61, 0x7a, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0xaa, 0x02, 0x0d, 0x50, 0x62, 0x2e, 0x4d,
	0x61, 0x7a, 0x65, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e,
}

var (
	file_common_MazeCommon_proto_rawDescOnce sync.Once
	file_common_MazeCommon_proto_rawDescData = file_common_MazeCommon_proto_rawDesc
)

func file_common_MazeCommon_proto_rawDescGZIP() []byte {
	file_common_MazeCommon_proto_rawDescOnce.Do(func() {
		file_common_MazeCommon_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_MazeCommon_proto_rawDescData)
	})
	return file_common_MazeCommon_proto_rawDescData
}

var file_common_MazeCommon_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_MazeCommon_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_common_MazeCommon_proto_goTypes = []interface{}{
	(MazeItemType)(0), // 0: MazeCommon.MazeItemType
	(*MazeItem)(nil),  // 1: MazeCommon.MazeItem
	(*MazeCount)(nil), // 2: MazeCommon.MazeCount
	(*Attr)(nil),      // 3: MazeCommon.Attr
}
var file_common_MazeCommon_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_common_MazeCommon_proto_init() }
func file_common_MazeCommon_proto_init() {
	if File_common_MazeCommon_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_MazeCommon_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeItem); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_MazeCommon_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*MazeCount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_MazeCommon_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Attr); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_MazeCommon_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_MazeCommon_proto_goTypes,
		DependencyIndexes: file_common_MazeCommon_proto_depIdxs,
		EnumInfos:         file_common_MazeCommon_proto_enumTypes,
		MessageInfos:      file_common_MazeCommon_proto_msgTypes,
	}.Build()
	File_common_MazeCommon_proto = out.File
	file_common_MazeCommon_proto_rawDesc = nil
	file_common_MazeCommon_proto_goTypes = nil
	file_common_MazeCommon_proto_depIdxs = nil
}
