// Code generated by protoc-gen-go.
// source: FriendsBaseStruct.proto
// DO NOT EDIT!

/*
Package FriendsBaseStruct is a generated protocol buffer package.

It is generated from these files:
	FriendsBaseStruct.proto

It has these top-level messages:
	RelevancyAccountInfo
	FriendInfo
	ApplyInfo
	BlackListItem
	RelationItem
*/
package FriendsBaseStruct

import proto "gitlab.ifreetalk.com/plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type FriendType int32

const (
	FriendType_ENUM_FRIEND_TYPE_NONE     FriendType = 0
	FriendType_ENUM_FRIEND_TYPE_NORMAL   FriendType = 1
	FriendType_ENUM_FRIEND_TYPE_PHONE    FriendType = 2
	FriendType_ENUM_FRIEND_TYPE_PHONE_1  FriendType = 3
	FriendType_ENUM_FRIEND_TYPE_QQ       FriendType = 4
	FriendType_ENUM_FRIEND_TYPE_QQ_1     FriendType = 5
	FriendType_ENUM_FRIEND_TYPE_WEIXIN   FriendType = 6
	FriendType_ENUM_FRIEND_TYPE_WEIXIN_1 FriendType = 7
	FriendType_ENUM_FRIEND_TYPE_QRCODE   FriendType = 8
)

var FriendType_name = map[int32]string{
	0: "ENUM_FRIEND_TYPE_NONE",
	1: "ENUM_FRIEND_TYPE_NORMAL",
	2: "ENUM_FRIEND_TYPE_PHONE",
	3: "ENUM_FRIEND_TYPE_PHONE_1",
	4: "ENUM_FRIEND_TYPE_QQ",
	5: "ENUM_FRIEND_TYPE_QQ_1",
	6: "ENUM_FRIEND_TYPE_WEIXIN",
	7: "ENUM_FRIEND_TYPE_WEIXIN_1",
	8: "ENUM_FRIEND_TYPE_QRCODE",
}
var FriendType_value = map[string]int32{
	"ENUM_FRIEND_TYPE_NONE":     0,
	"ENUM_FRIEND_TYPE_NORMAL":   1,
	"ENUM_FRIEND_TYPE_PHONE":    2,
	"ENUM_FRIEND_TYPE_PHONE_1":  3,
	"ENUM_FRIEND_TYPE_QQ":       4,
	"ENUM_FRIEND_TYPE_QQ_1":     5,
	"ENUM_FRIEND_TYPE_WEIXIN":   6,
	"ENUM_FRIEND_TYPE_WEIXIN_1": 7,
	"ENUM_FRIEND_TYPE_QRCODE":   8,
}

func (x FriendType) Enum() *FriendType {
	p := new(FriendType)
	*p = x
	return p
}
func (x FriendType) String() string {
	return proto.EnumName(FriendType_name, int32(x))
}
func (x *FriendType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FriendType_value, data, "FriendType")
	if err != nil {
		return err
	}
	*x = FriendType(value)
	return nil
}
func (FriendType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type FriendExtType int32

const (
	FriendExtType_ENUM_FRIEND_EXT_TYPE_DEG FriendExtType = 0
)

var FriendExtType_name = map[int32]string{
	0: "ENUM_FRIEND_EXT_TYPE_DEG",
}
var FriendExtType_value = map[string]int32{
	"ENUM_FRIEND_EXT_TYPE_DEG": 0,
}

func (x FriendExtType) Enum() *FriendExtType {
	p := new(FriendExtType)
	*p = x
	return p
}
func (x FriendExtType) String() string {
	return proto.EnumName(FriendExtType_name, int32(x))
}
func (x *FriendExtType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(FriendExtType_value, data, "FriendExtType")
	if err != nil {
		return err
	}
	*x = FriendExtType(value)
	return nil
}
func (FriendExtType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type RegisterType int32

const (
	RegisterType_ENUM_REGISTE_APP RegisterType = 0
	RegisterType_ENUM_REGISTE_H5  RegisterType = 1
)

var RegisterType_name = map[int32]string{
	0: "ENUM_REGISTE_APP",
	1: "ENUM_REGISTE_H5",
}
var RegisterType_value = map[string]int32{
	"ENUM_REGISTE_APP": 0,
	"ENUM_REGISTE_H5":  1,
}

func (x RegisterType) Enum() *RegisterType {
	p := new(RegisterType)
	*p = x
	return p
}
func (x RegisterType) String() string {
	return proto.EnumName(RegisterType_name, int32(x))
}
func (x *RegisterType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RegisterType_value, data, "RegisterType")
	if err != nil {
		return err
	}
	*x = RegisterType(value)
	return nil
}
func (RegisterType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type ApplyType int32

const (
	ApplyType_ENUM_APPLY_NORMAL_SEARCH       ApplyType = 0
	ApplyType_ENUM_APPLY_RECOMMEND           ApplyType = 1
	ApplyType_ENUM_APPLY_INTERSECTION        ApplyType = 2
	ApplyType_ENUM_APPLY_LBS                 ApplyType = 3
	ApplyType_ENUM_APPLY_PHONE               ApplyType = 4
	ApplyType_ENUM_APPLY_QQ                  ApplyType = 5
	ApplyType_ENUM_APPLY_WEIXIN              ApplyType = 6
	ApplyType_ENUM_APPLY_QRCODE              ApplyType = 7
	ApplyType_ENUM_APPLY_QRCODE_INTERSECTION ApplyType = 8
)

var ApplyType_name = map[int32]string{
	0: "ENUM_APPLY_NORMAL_SEARCH",
	1: "ENUM_APPLY_RECOMMEND",
	2: "ENUM_APPLY_INTERSECTION",
	3: "ENUM_APPLY_LBS",
	4: "ENUM_APPLY_PHONE",
	5: "ENUM_APPLY_QQ",
	6: "ENUM_APPLY_WEIXIN",
	7: "ENUM_APPLY_QRCODE",
	8: "ENUM_APPLY_QRCODE_INTERSECTION",
}
var ApplyType_value = map[string]int32{
	"ENUM_APPLY_NORMAL_SEARCH":       0,
	"ENUM_APPLY_RECOMMEND":           1,
	"ENUM_APPLY_INTERSECTION":        2,
	"ENUM_APPLY_LBS":                 3,
	"ENUM_APPLY_PHONE":               4,
	"ENUM_APPLY_QQ":                  5,
	"ENUM_APPLY_WEIXIN":              6,
	"ENUM_APPLY_QRCODE":              7,
	"ENUM_APPLY_QRCODE_INTERSECTION": 8,
}

func (x ApplyType) Enum() *ApplyType {
	p := new(ApplyType)
	*p = x
	return p
}
func (x ApplyType) String() string {
	return proto.EnumName(ApplyType_name, int32(x))
}
func (x *ApplyType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ApplyType_value, data, "ApplyType")
	if err != nil {
		return err
	}
	*x = ApplyType(value)
	return nil
}
func (ApplyType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type RelationType int32

const (
	RelationType_ENUM_RELATION_TYPE_PHONE           RelationType = 0
	RelationType_ENUM_RELATION_TYPE_QQ              RelationType = 1
	RelationType_ENUM_RELATION_TYPE_WEIXIN          RelationType = 2
	RelationType_ENUM_RELATION_TYPE_LBS             RelationType = 3
	RelationType_ENUM_RELATION_TYPE_IN_MY_CONTACT   RelationType = 4
	RelationType_ENUM_RELATION_TYPE_IN_PEER_CONTACT RelationType = 5
)

var RelationType_name = map[int32]string{
	0: "ENUM_RELATION_TYPE_PHONE",
	1: "ENUM_RELATION_TYPE_QQ",
	2: "ENUM_RELATION_TYPE_WEIXIN",
	3: "ENUM_RELATION_TYPE_LBS",
	4: "ENUM_RELATION_TYPE_IN_MY_CONTACT",
	5: "ENUM_RELATION_TYPE_IN_PEER_CONTACT",
}
var RelationType_value = map[string]int32{
	"ENUM_RELATION_TYPE_PHONE":           0,
	"ENUM_RELATION_TYPE_QQ":              1,
	"ENUM_RELATION_TYPE_WEIXIN":          2,
	"ENUM_RELATION_TYPE_LBS":             3,
	"ENUM_RELATION_TYPE_IN_MY_CONTACT":   4,
	"ENUM_RELATION_TYPE_IN_PEER_CONTACT": 5,
}

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}
func (x RelationType) String() string {
	return proto.EnumName(RelationType_name, int32(x))
}
func (x *RelationType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RelationType_value, data, "RelationType")
	if err != nil {
		return err
	}
	*x = RelationType(value)
	return nil
}
func (RelationType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

// 隐私选项
// 由一个64位的整数来表示隐私选项组合,当对应的位上为1时,表示禁止
// 如 0x1表示禁止通过派派号搜索到我
// 如 0x2拒绝添加好友
// 0x3表示禁止通过派派号搜索到我、拒绝添加好友
type PrivateOptionType int32

const (
	PrivateOptionType_ENUM_FORBID_SEARCH_ME_BY_PAIPAI PrivateOptionType = 0
	PrivateOptionType_ENUM_FORBID_FRIEND_ADD_ME       PrivateOptionType = 1
)

var PrivateOptionType_name = map[int32]string{
	0: "ENUM_FORBID_SEARCH_ME_BY_PAIPAI",
	1: "ENUM_FORBID_FRIEND_ADD_ME",
}
var PrivateOptionType_value = map[string]int32{
	"ENUM_FORBID_SEARCH_ME_BY_PAIPAI": 0,
	"ENUM_FORBID_FRIEND_ADD_ME":       1,
}

func (x PrivateOptionType) Enum() *PrivateOptionType {
	p := new(PrivateOptionType)
	*p = x
	return p
}
func (x PrivateOptionType) String() string {
	return proto.EnumName(PrivateOptionType_name, int32(x))
}
func (x *PrivateOptionType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(PrivateOptionType_value, data, "PrivateOptionType")
	if err != nil {
		return err
	}
	*x = PrivateOptionType(value)
	return nil
}
func (PrivateOptionType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

// 黑名单操作
type BlackListOPType int32

const (
	BlackListOPType_ENUM_BLACKLIST_OP_TYPE_ADD BlackListOPType = 0
	BlackListOPType_ENUM_BLACKLIST_OP_TYPE_DEL BlackListOPType = 1
)

var BlackListOPType_name = map[int32]string{
	0: "ENUM_BLACKLIST_OP_TYPE_ADD",
	1: "ENUM_BLACKLIST_OP_TYPE_DEL",
}
var BlackListOPType_value = map[string]int32{
	"ENUM_BLACKLIST_OP_TYPE_ADD": 0,
	"ENUM_BLACKLIST_OP_TYPE_DEL": 1,
}

func (x BlackListOPType) Enum() *BlackListOPType {
	p := new(BlackListOPType)
	*p = x
	return p
}
func (x BlackListOPType) String() string {
	return proto.EnumName(BlackListOPType_name, int32(x))
}
func (x *BlackListOPType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(BlackListOPType_value, data, "BlackListOPType")
	if err != nil {
		return err
	}
	*x = BlackListOPType(value)
	return nil
}
func (BlackListOPType) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

type RelevancyAccountInfo_RelevancyAcountType int32

const (
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_PHONE     RelevancyAccountInfo_RelevancyAcountType = 0
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_PASSPORT  RelevancyAccountInfo_RelevancyAcountType = 1
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_WEIBO     RelevancyAccountInfo_RelevancyAcountType = 2
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_QQ        RelevancyAccountInfo_RelevancyAcountType = 3
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_WEIXIN    RelevancyAccountInfo_RelevancyAcountType = 4
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_WEIXIN_EX RelevancyAccountInfo_RelevancyAcountType = 5
	RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_GUEST     RelevancyAccountInfo_RelevancyAcountType = 32
)

var RelevancyAccountInfo_RelevancyAcountType_name = map[int32]string{
	0:  "ENUM_RELEVANCY_ACCOUNT_TYPE_PHONE",
	1:  "ENUM_RELEVANCY_ACCOUNT_TYPE_PASSPORT",
	2:  "ENUM_RELEVANCY_ACCOUNT_TYPE_WEIBO",
	3:  "ENUM_RELEVANCY_ACCOUNT_TYPE_QQ",
	4:  "ENUM_RELEVANCY_ACCOUNT_TYPE_WEIXIN",
	5:  "ENUM_RELEVANCY_ACCOUNT_TYPE_WEIXIN_EX",
	32: "ENUM_RELEVANCY_ACCOUNT_TYPE_GUEST",
}
var RelevancyAccountInfo_RelevancyAcountType_value = map[string]int32{
	"ENUM_RELEVANCY_ACCOUNT_TYPE_PHONE":     0,
	"ENUM_RELEVANCY_ACCOUNT_TYPE_PASSPORT":  1,
	"ENUM_RELEVANCY_ACCOUNT_TYPE_WEIBO":     2,
	"ENUM_RELEVANCY_ACCOUNT_TYPE_QQ":        3,
	"ENUM_RELEVANCY_ACCOUNT_TYPE_WEIXIN":    4,
	"ENUM_RELEVANCY_ACCOUNT_TYPE_WEIXIN_EX": 5,
	"ENUM_RELEVANCY_ACCOUNT_TYPE_GUEST":     32,
}

func (x RelevancyAccountInfo_RelevancyAcountType) Enum() *RelevancyAccountInfo_RelevancyAcountType {
	p := new(RelevancyAccountInfo_RelevancyAcountType)
	*p = x
	return p
}
func (x RelevancyAccountInfo_RelevancyAcountType) String() string {
	return proto.EnumName(RelevancyAccountInfo_RelevancyAcountType_name, int32(x))
}
func (x *RelevancyAccountInfo_RelevancyAcountType) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(RelevancyAccountInfo_RelevancyAcountType_value, data, "RelevancyAccountInfo_RelevancyAcountType")
	if err != nil {
		return err
	}
	*x = RelevancyAccountInfo_RelevancyAcountType(value)
	return nil
}
func (RelevancyAccountInfo_RelevancyAcountType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0, 0}
}

// 关联账号信息
type RelevancyAccountInfo struct {
	Type             *RelevancyAccountInfo_RelevancyAcountType `protobuf:"varint,1,req,name=type,enum=FriendsBaseStruct.RelevancyAccountInfo_RelevancyAcountType" json:"type,omitempty"`
	UnionID          []byte                                    `protobuf:"bytes,2,opt,name=unionID" json:"unionID,omitempty"`
	OpenID           []byte                                    `protobuf:"bytes,3,opt,name=openID" json:"openID,omitempty"`
	AccessToken      []byte                                    `protobuf:"bytes,4,opt,name=accessToken" json:"accessToken,omitempty"`
	Phone            []byte                                    `protobuf:"bytes,5,opt,name=phone" json:"phone,omitempty"`
	Nickname         []byte                                    `protobuf:"bytes,6,opt,name=nickname" json:"nickname,omitempty"`
	Passport         []byte                                    `protobuf:"bytes,7,opt,name=passport" json:"passport,omitempty"`
	Password         []byte                                    `protobuf:"bytes,8,opt,name=password" json:"password,omitempty"`
	XXX_unrecognized []byte                                    `json:"-"`
}

func (m *RelevancyAccountInfo) Reset()                    { *m = RelevancyAccountInfo{} }
func (m *RelevancyAccountInfo) String() string            { return proto.CompactTextString(m) }
func (*RelevancyAccountInfo) ProtoMessage()               {}
func (*RelevancyAccountInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *RelevancyAccountInfo) GetType() RelevancyAccountInfo_RelevancyAcountType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return RelevancyAccountInfo_ENUM_RELEVANCY_ACCOUNT_TYPE_PHONE
}

func (m *RelevancyAccountInfo) GetUnionID() []byte {
	if m != nil {
		return m.UnionID
	}
	return nil
}

func (m *RelevancyAccountInfo) GetOpenID() []byte {
	if m != nil {
		return m.OpenID
	}
	return nil
}

func (m *RelevancyAccountInfo) GetAccessToken() []byte {
	if m != nil {
		return m.AccessToken
	}
	return nil
}

func (m *RelevancyAccountInfo) GetPhone() []byte {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *RelevancyAccountInfo) GetNickname() []byte {
	if m != nil {
		return m.Nickname
	}
	return nil
}

func (m *RelevancyAccountInfo) GetPassport() []byte {
	if m != nil {
		return m.Passport
	}
	return nil
}

func (m *RelevancyAccountInfo) GetPassword() []byte {
	if m != nil {
		return m.Password
	}
	return nil
}

// 好友信息
type FriendInfo struct {
	UserID           *uint64     `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	Sex              *int32      `protobuf:"varint,2,opt,name=sex" json:"sex,omitempty"`
	NickName         []byte      `protobuf:"bytes,3,opt,name=nickName" json:"nickName,omitempty"`
	ExtraName        [][]byte    `protobuf:"bytes,4,rep,name=extraName" json:"extraName,omitempty"`
	Delete           *int32      `protobuf:"varint,5,opt,name=delete" json:"delete,omitempty"`
	Token            *int64      `protobuf:"varint,6,opt,name=token" json:"token,omitempty"`
	FriendType       *FriendType `protobuf:"varint,7,opt,name=friendType,enum=FriendsBaseStruct.FriendType" json:"friendType,omitempty"`
	Phone            *uint64     `protobuf:"varint,8,opt,name=phone" json:"phone,omitempty"`
	ExtType          *int64      `protobuf:"varint,9,opt,name=extType" json:"extType,omitempty"`
	XXX_unrecognized []byte      `json:"-"`
}

func (m *FriendInfo) Reset()                    { *m = FriendInfo{} }
func (m *FriendInfo) String() string            { return proto.CompactTextString(m) }
func (*FriendInfo) ProtoMessage()               {}
func (*FriendInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *FriendInfo) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *FriendInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *FriendInfo) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *FriendInfo) GetExtraName() [][]byte {
	if m != nil {
		return m.ExtraName
	}
	return nil
}

func (m *FriendInfo) GetDelete() int32 {
	if m != nil && m.Delete != nil {
		return *m.Delete
	}
	return 0
}

func (m *FriendInfo) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *FriendInfo) GetFriendType() FriendType {
	if m != nil && m.FriendType != nil {
		return *m.FriendType
	}
	return FriendType_ENUM_FRIEND_TYPE_NONE
}

func (m *FriendInfo) GetPhone() uint64 {
	if m != nil && m.Phone != nil {
		return *m.Phone
	}
	return 0
}

func (m *FriendInfo) GetExtType() int64 {
	if m != nil && m.ExtType != nil {
		return *m.ExtType
	}
	return 0
}

// 好友信息
type ApplyInfo struct {
	UserId             *uint64    `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Type               *ApplyType `protobuf:"varint,2,opt,name=type,enum=FriendsBaseStruct.ApplyType" json:"type,omitempty"`
	Msg                []byte     `protobuf:"bytes,3,opt,name=msg" json:"msg,omitempty"`
	Token              *int64     `protobuf:"varint,4,opt,name=token" json:"token,omitempty"`
	Relation           *int32     `protobuf:"varint,5,opt,name=relation" json:"relation,omitempty"`
	NickName           []byte     `protobuf:"bytes,6,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`
	Sex                *int32     `protobuf:"varint,7,opt,name=sex" json:"sex,omitempty"`
	UserId1            *string    `protobuf:"bytes,8,opt,name=user_id1,json=userId1" json:"user_id1,omitempty"`
	Msg1               *string    `protobuf:"bytes,9,opt,name=msg1" json:"msg1,omitempty"`
	NickName1          *string    `protobuf:"bytes,10,opt,name=nick_name1,json=nickName1" json:"nick_name1,omitempty"`
	CurrentFriendCount *uint32    `protobuf:"varint,11,opt,name=current_friend_count,json=currentFriendCount" json:"current_friend_count,omitempty"`
	CurrentCountLimit  *uint32    `protobuf:"varint,12,opt,name=current_count_limit,json=currentCountLimit" json:"current_count_limit,omitempty"`
	NextVipCountLimit  *uint32    `protobuf:"varint,13,opt,name=next_vip_count_limit,json=nextVipCountLimit" json:"next_vip_count_limit,omitempty"`
	CurrentVipLevel    *uint32    `protobuf:"varint,14,opt,name=current_vip_level,json=currentVipLevel" json:"current_vip_level,omitempty"`
	NextVipLevel       *uint32    `protobuf:"varint,15,opt,name=next_vip_level,json=nextVipLevel" json:"next_vip_level,omitempty"`
	XXX_unrecognized   []byte     `json:"-"`
}

func (m *ApplyInfo) Reset()                    { *m = ApplyInfo{} }
func (m *ApplyInfo) String() string            { return proto.CompactTextString(m) }
func (*ApplyInfo) ProtoMessage()               {}
func (*ApplyInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ApplyInfo) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *ApplyInfo) GetType() ApplyType {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ApplyType_ENUM_APPLY_NORMAL_SEARCH
}

func (m *ApplyInfo) GetMsg() []byte {
	if m != nil {
		return m.Msg
	}
	return nil
}

func (m *ApplyInfo) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *ApplyInfo) GetRelation() int32 {
	if m != nil && m.Relation != nil {
		return *m.Relation
	}
	return 0
}

func (m *ApplyInfo) GetNickName() []byte {
	if m != nil {
		return m.NickName
	}
	return nil
}

func (m *ApplyInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *ApplyInfo) GetUserId1() string {
	if m != nil && m.UserId1 != nil {
		return *m.UserId1
	}
	return ""
}

func (m *ApplyInfo) GetMsg1() string {
	if m != nil && m.Msg1 != nil {
		return *m.Msg1
	}
	return ""
}

func (m *ApplyInfo) GetNickName1() string {
	if m != nil && m.NickName1 != nil {
		return *m.NickName1
	}
	return ""
}

func (m *ApplyInfo) GetCurrentFriendCount() uint32 {
	if m != nil && m.CurrentFriendCount != nil {
		return *m.CurrentFriendCount
	}
	return 0
}

func (m *ApplyInfo) GetCurrentCountLimit() uint32 {
	if m != nil && m.CurrentCountLimit != nil {
		return *m.CurrentCountLimit
	}
	return 0
}

func (m *ApplyInfo) GetNextVipCountLimit() uint32 {
	if m != nil && m.NextVipCountLimit != nil {
		return *m.NextVipCountLimit
	}
	return 0
}

func (m *ApplyInfo) GetCurrentVipLevel() uint32 {
	if m != nil && m.CurrentVipLevel != nil {
		return *m.CurrentVipLevel
	}
	return 0
}

func (m *ApplyInfo) GetNextVipLevel() uint32 {
	if m != nil && m.NextVipLevel != nil {
		return *m.NextVipLevel
	}
	return 0
}

// 黑名单
type BlackListItem struct {
	UserID           *uint64 `protobuf:"varint,1,opt,name=userID" json:"userID,omitempty"`
	OpType           *int32  `protobuf:"varint,2,opt,name=op_type,json=opType" json:"op_type,omitempty"`
	Token            *int64  `protobuf:"varint,3,opt,name=token" json:"token,omitempty"`
	Sex              *int32  `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	Nickname         []byte  `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *BlackListItem) Reset()                    { *m = BlackListItem{} }
func (m *BlackListItem) String() string            { return proto.CompactTextString(m) }
func (*BlackListItem) ProtoMessage()               {}
func (*BlackListItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *BlackListItem) GetUserID() uint64 {
	if m != nil && m.UserID != nil {
		return *m.UserID
	}
	return 0
}

func (m *BlackListItem) GetOpType() int32 {
	if m != nil && m.OpType != nil {
		return *m.OpType
	}
	return 0
}

func (m *BlackListItem) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *BlackListItem) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *BlackListItem) GetNickname() []byte {
	if m != nil {
		return m.Nickname
	}
	return nil
}

// 关系
type RelationItem struct {
	User             *uint64 `protobuf:"varint,1,opt,name=user" json:"user,omitempty"`
	Relation         *int64  `protobuf:"varint,2,opt,name=relation" json:"relation,omitempty"`
	Token            *int64  `protobuf:"varint,3,opt,name=token" json:"token,omitempty"`
	Sex              *int32  `protobuf:"varint,4,opt,name=sex" json:"sex,omitempty"`
	Nickname         []byte  `protobuf:"bytes,5,opt,name=nickname" json:"nickname,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *RelationItem) Reset()                    { *m = RelationItem{} }
func (m *RelationItem) String() string            { return proto.CompactTextString(m) }
func (*RelationItem) ProtoMessage()               {}
func (*RelationItem) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *RelationItem) GetUser() uint64 {
	if m != nil && m.User != nil {
		return *m.User
	}
	return 0
}

func (m *RelationItem) GetRelation() int64 {
	if m != nil && m.Relation != nil {
		return *m.Relation
	}
	return 0
}

func (m *RelationItem) GetToken() int64 {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return 0
}

func (m *RelationItem) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *RelationItem) GetNickname() []byte {
	if m != nil {
		return m.Nickname
	}
	return nil
}

func init() {
	proto.RegisterType((*RelevancyAccountInfo)(nil), "FriendsBaseStruct.RelevancyAccountInfo")
	proto.RegisterType((*FriendInfo)(nil), "FriendsBaseStruct.FriendInfo")
	proto.RegisterType((*ApplyInfo)(nil), "FriendsBaseStruct.ApplyInfo")
	proto.RegisterType((*BlackListItem)(nil), "FriendsBaseStruct.BlackListItem")
	proto.RegisterType((*RelationItem)(nil), "FriendsBaseStruct.RelationItem")
	proto.RegisterEnum("FriendsBaseStruct.FriendType", FriendType_name, FriendType_value)
	proto.RegisterEnum("FriendsBaseStruct.FriendExtType", FriendExtType_name, FriendExtType_value)
	proto.RegisterEnum("FriendsBaseStruct.RegisterType", RegisterType_name, RegisterType_value)
	proto.RegisterEnum("FriendsBaseStruct.ApplyType", ApplyType_name, ApplyType_value)
	proto.RegisterEnum("FriendsBaseStruct.RelationType", RelationType_name, RelationType_value)
	proto.RegisterEnum("FriendsBaseStruct.PrivateOptionType", PrivateOptionType_name, PrivateOptionType_value)
	proto.RegisterEnum("FriendsBaseStruct.BlackListOPType", BlackListOPType_name, BlackListOPType_value)
	proto.RegisterEnum("FriendsBaseStruct.RelevancyAccountInfo_RelevancyAcountType", RelevancyAccountInfo_RelevancyAcountType_name, RelevancyAccountInfo_RelevancyAcountType_value)
}

func init() { proto.RegisterFile("FriendsBaseStruct.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1131 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4b, 0x6f, 0xdb, 0xc6,
	0x13, 0x17, 0x25, 0xca, 0x92, 0x26, 0x7e, 0xac, 0xd7, 0x4e, 0xcc, 0x38, 0x8f, 0xbf, 0xfe, 0x6a,
	0x52, 0xa8, 0x02, 0x9a, 0x46, 0x01, 0x7a, 0x28, 0x8a, 0x1e, 0x28, 0x71, 0x93, 0x10, 0x95, 0xf8,
	0x58, 0x31, 0x0f, 0x9f, 0x16, 0x82, 0xbc, 0x49, 0x89, 0xc8, 0x24, 0x41, 0xd2, 0xae, 0x7d, 0x2d,
	0x7a, 0x2b, 0xfa, 0x49, 0xfa, 0x65, 0x0a, 0xf4, 0x83, 0xf4, 0x0b, 0xf4, 0x50, 0x70, 0xb9, 0xa2,
	0xc8, 0x58, 0x89, 0x2f, 0xbd, 0xed, 0xcc, 0x6f, 0x66, 0x76, 0x1e, 0xbf, 0x9d, 0x85, 0xa3, 0xe7,
	0xb1, 0xcf, 0x83, 0xd3, 0x64, 0x34, 0x4f, 0xf8, 0x2c, 0x8d, 0xcf, 0x17, 0xe9, 0x93, 0x28, 0x0e,
	0xd3, 0x10, 0xef, 0x5f, 0x03, 0x7a, 0x7f, 0xa9, 0x70, 0x48, 0xf9, 0x92, 0x5f, 0xcc, 0x83, 0xc5,
	0x95, 0xbe, 0x58, 0x84, 0xe7, 0x41, 0x6a, 0x06, 0xef, 0x42, 0x6c, 0x83, 0x9a, 0x5e, 0x45, 0x5c,
	0x53, 0xba, 0xf5, 0xfe, 0xee, 0xb3, 0xef, 0x9f, 0x5c, 0x8f, 0xb9, 0xc9, 0xad, 0xac, 0xcc, 0x74,
	0xde, 0x55, 0xc4, 0xa9, 0x08, 0x84, 0x35, 0x68, 0x9d, 0x07, 0x7e, 0x18, 0x98, 0x86, 0x56, 0xef,
	0x2a, 0xfd, 0x6d, 0xba, 0x12, 0xf1, 0x1d, 0xd8, 0x0a, 0x23, 0x9e, 0x01, 0x0d, 0x01, 0x48, 0x09,
	0x77, 0xe1, 0xd6, 0x7c, 0xb1, 0xe0, 0x49, 0xe2, 0x85, 0x1f, 0x78, 0xa0, 0xa9, 0x02, 0x2c, 0xab,
	0xf0, 0x21, 0x34, 0xa3, 0x9f, 0xc2, 0x80, 0x6b, 0x4d, 0x81, 0xe5, 0x02, 0x3e, 0x86, 0x76, 0xe0,
	0x2f, 0x3e, 0x04, 0xf3, 0x33, 0xae, 0x6d, 0x09, 0xa0, 0x90, 0x33, 0x2c, 0x9a, 0x27, 0x49, 0x14,
	0xc6, 0xa9, 0xd6, 0xca, 0xb1, 0x95, 0xbc, 0xc2, 0x7e, 0x0e, 0xe3, 0x53, 0xad, 0xbd, 0xc6, 0x32,
	0xb9, 0xf7, 0x47, 0x1d, 0x0e, 0x36, 0xd4, 0x86, 0x1f, 0xc3, 0xff, 0x89, 0xf5, 0x6a, 0xca, 0x28,
	0x99, 0x90, 0xd7, 0xba, 0x35, 0x3e, 0x61, 0xfa, 0x78, 0x6c, 0xbf, 0xb2, 0x3c, 0xe6, 0x9d, 0x38,
	0x84, 0x39, 0x2f, 0x6d, 0x8b, 0xa0, 0x1a, 0xee, 0xc3, 0xa3, 0xcf, 0x9a, 0xe9, 0xb3, 0x99, 0x63,
	0x53, 0x0f, 0x29, 0x37, 0x05, 0x7c, 0x43, 0xcc, 0x91, 0x8d, 0xea, 0xb8, 0x07, 0x0f, 0x3f, 0x67,
	0xe6, 0xba, 0xa8, 0x81, 0xbf, 0x84, 0xde, 0x0d, 0xa1, 0xde, 0x9a, 0x16, 0x52, 0xf1, 0x57, 0xf0,
	0xf8, 0x66, 0x3b, 0x46, 0xde, 0xa2, 0xe6, 0x4d, 0xd9, 0xbd, 0x78, 0x45, 0x66, 0x1e, 0xea, 0xf6,
	0x7e, 0xaf, 0x03, 0xe4, 0x84, 0x11, 0x5c, 0xba, 0x03, 0x5b, 0xe7, 0x09, 0x8f, 0x4d, 0x43, 0x53,
	0xba, 0x4a, 0x5f, 0xa5, 0x52, 0xc2, 0x08, 0x1a, 0x09, 0xbf, 0x14, 0x74, 0x68, 0xd2, 0xec, 0xb8,
	0x1a, 0x9d, 0x95, 0x8d, 0xae, 0xb1, 0x1e, 0x5d, 0x26, 0xe3, 0xfb, 0xd0, 0xe1, 0x97, 0x69, 0x3c,
	0x17, 0xa0, 0xda, 0x6d, 0xf4, 0xb7, 0xe9, 0x5a, 0x91, 0xdd, 0x71, 0xca, 0x97, 0x3c, 0xcd, 0xb9,
	0xd0, 0xa4, 0x52, 0xca, 0x28, 0x92, 0x0a, 0xfa, 0x64, 0x4c, 0x68, 0xd0, 0x5c, 0xc0, 0x3f, 0x00,
	0xbc, 0x13, 0xf9, 0x65, 0x43, 0x14, 0x44, 0xd8, 0x7d, 0xf6, 0x60, 0x03, 0xc7, 0x9f, 0x17, 0x46,
	0xb4, 0xe4, 0xb0, 0xe6, 0x5d, 0x5b, 0xd4, 0x23, 0x79, 0xa7, 0x41, 0x8b, 0x5f, 0x0a, 0x5a, 0x68,
	0x1d, 0x71, 0xd9, 0x4a, 0xec, 0xfd, 0xd3, 0x80, 0x8e, 0x1e, 0x45, 0xcb, 0x2b, 0xd1, 0x8e, 0x23,
	0x68, 0x65, 0x0d, 0x60, 0xfe, 0x69, 0xa5, 0x1f, 0xa7, 0xf8, 0xa9, 0x7c, 0x73, 0x75, 0x91, 0xcf,
	0xfd, 0x0d, 0xf9, 0x88, 0x20, 0xa5, 0x47, 0x85, 0xa0, 0x71, 0x96, 0xbc, 0x97, 0xad, 0xca, 0x8e,
	0xeb, 0x7a, 0xd5, 0x72, 0xbd, 0xc7, 0xd0, 0x8e, 0xf9, 0x72, 0x9e, 0xfa, 0x61, 0x20, 0xfb, 0x53,
	0xc8, 0xf8, 0x1e, 0x74, 0xb2, 0x1e, 0xb3, 0x8f, 0xdf, 0x8b, 0x68, 0xab, 0x1c, 0x51, 0x6b, 0x3d,
	0xa2, 0xbb, 0xd0, 0x96, 0xd9, 0x0f, 0x45, 0xf9, 0x1d, 0xda, 0xca, 0xd3, 0x1f, 0x62, 0x0c, 0xea,
	0x59, 0xf2, 0x7e, 0x28, 0xaa, 0xef, 0x50, 0x71, 0xc6, 0x0f, 0x00, 0x8a, 0xe8, 0x43, 0x0d, 0x04,
	0xd2, 0x59, 0x85, 0x1f, 0xe2, 0xa7, 0x70, 0xb8, 0x38, 0x8f, 0x63, 0x1e, 0xa4, 0x2c, 0xef, 0x2f,
	0x13, 0x6f, 0x4b, 0xbb, 0xd5, 0x55, 0xfa, 0x3b, 0x14, 0x4b, 0x2c, 0x6f, 0xc4, 0x38, 0x43, 0xf0,
	0x13, 0x38, 0x58, 0x79, 0x08, 0x53, 0xb6, 0xf4, 0xcf, 0xfc, 0x54, 0xdb, 0x16, 0x0e, 0xfb, 0x12,
	0x12, 0xa6, 0x93, 0x0c, 0xc0, 0xdf, 0xc0, 0x61, 0xc0, 0x2f, 0x53, 0x76, 0xe1, 0x47, 0x15, 0x87,
	0x9d, 0xdc, 0x21, 0xc3, 0x5e, 0xfb, 0x51, 0xc9, 0x61, 0x00, 0xab, 0x28, 0xc2, 0x67, 0xc9, 0x2f,
	0xf8, 0x52, 0xdb, 0x15, 0xd6, 0x7b, 0x12, 0x78, 0xed, 0x47, 0x93, 0x4c, 0x8d, 0x1f, 0xc1, 0x6e,
	0x11, 0x3c, 0x37, 0xdc, 0x13, 0x86, 0xdb, 0x32, 0xac, 0xb0, 0xea, 0xfd, 0xaa, 0xc0, 0xce, 0x68,
	0x39, 0x5f, 0x7c, 0x98, 0xf8, 0x49, 0x6a, 0xa6, 0xfc, 0xec, 0x93, 0x2f, 0xe2, 0x08, 0x5a, 0x61,
	0xc4, 0x0a, 0x12, 0x34, 0xb3, 0x5d, 0xb8, 0x62, 0x5c, 0x3e, 0xd6, 0x46, 0x79, 0xac, 0x72, 0x3a,
	0xea, 0xb5, 0x07, 0x24, 0x66, 0xd9, 0xac, 0xee, 0xbe, 0xde, 0x2f, 0x0a, 0x6c, 0x53, 0x39, 0x75,
	0x91, 0x05, 0x06, 0x35, 0xbb, 0x57, 0xe6, 0x20, 0xce, 0x15, 0xa6, 0xd4, 0xc5, 0x5d, 0x6b, 0xa6,
	0xfc, 0x07, 0x49, 0x0c, 0x7e, 0x2b, 0x56, 0x83, 0xa8, 0xeb, 0x2e, 0xdc, 0x16, 0x0b, 0xe5, 0x39,
	0x35, 0x89, 0x65, 0xe4, 0x5b, 0xc4, 0xca, 0x77, 0xe6, 0x3d, 0x38, 0xda, 0x00, 0xd1, 0xa9, 0x3e,
	0x41, 0x0a, 0x3e, 0x86, 0x3b, 0xd7, 0xc0, 0x7c, 0xd9, 0xd6, 0xf1, 0x7d, 0xd0, 0x36, 0x63, 0x6c,
	0x88, 0x1a, 0xf8, 0x08, 0x0e, 0xae, 0xa1, 0xae, 0x8b, 0xd4, 0x8d, 0xa9, 0xb8, 0x2e, 0x1b, 0xa2,
	0xe6, 0xc6, 0x54, 0xe4, 0xfa, 0xdc, 0xc2, 0x0f, 0xe0, 0xee, 0x27, 0x40, 0x36, 0x44, 0xad, 0x8d,
	0xbe, 0x2e, 0x1d, 0xdb, 0x06, 0x41, 0xed, 0xc1, 0xd7, 0xb0, 0x93, 0x37, 0x83, 0xe4, 0x9b, 0xe2,
	0xe3, 0xdc, 0xc9, 0x5b, 0xb9, 0x59, 0x0d, 0xf2, 0x02, 0xd5, 0x06, 0xdf, 0x65, 0x03, 0x7c, 0xef,
	0x27, 0x29, 0x8f, 0x25, 0x2b, 0x90, 0x5c, 0xc7, 0x2f, 0xcc, 0x99, 0x47, 0x98, 0xee, 0x38, 0xa8,
	0x86, 0x0f, 0x60, 0xaf, 0xa2, 0x7d, 0xf9, 0x2d, 0x52, 0x06, 0x7f, 0x2b, 0x72, 0x05, 0x55, 0xae,
	0xd1, 0x1d, 0x67, 0x72, 0x22, 0xbb, 0xca, 0x66, 0x44, 0xa7, 0xe3, 0x97, 0xa8, 0x86, 0x35, 0x38,
	0x2c, 0xa1, 0x94, 0x8c, 0xed, 0xe9, 0x94, 0x58, 0x06, 0x52, 0x8a, 0x62, 0x72, 0xc4, 0xb4, 0x3c,
	0x42, 0x67, 0x64, 0xec, 0x99, 0xb6, 0x85, 0xea, 0x18, 0xc3, 0x6e, 0x09, 0x9c, 0x8c, 0x66, 0xa8,
	0x51, 0x64, 0x98, 0xeb, 0xf2, 0x09, 0xa9, 0x78, 0x1f, 0x76, 0x4a, 0x5a, 0xd7, 0x45, 0x4d, 0x7c,
	0x1b, 0xf6, 0x4b, 0xaa, 0xa2, 0xb9, 0x55, 0xb5, 0xec, 0x5b, 0xab, 0xf8, 0xfe, 0xca, 0xea, 0x6a,
	0x3a, 0xed, 0xc1, 0x9f, 0x25, 0xba, 0x57, 0x8a, 0xa6, 0x64, 0xa2, 0x67, 0x36, 0xd5, 0x2f, 0x7a,
	0x35, 0xfe, 0x2a, 0xea, 0xba, 0x48, 0x29, 0x26, 0x5c, 0x85, 0x64, 0x8e, 0xf5, 0x82, 0x8b, 0x55,
	0x38, 0xaf, 0xff, 0x11, 0x74, 0x37, 0x60, 0xa6, 0xc5, 0xa6, 0x27, 0x6c, 0x6c, 0x5b, 0x9e, 0x3e,
	0xf6, 0x90, 0x5a, 0xfe, 0xa9, 0xab, 0x56, 0x0e, 0x21, 0xb4, 0xb0, 0x6b, 0x0e, 0xde, 0xc0, 0xbe,
	0x13, 0xfb, 0x17, 0xf3, 0x94, 0xdb, 0x51, 0x51, 0xd6, 0x17, 0xf0, 0xbf, 0x9c, 0x32, 0x36, 0x1d,
	0x99, 0x86, 0x9c, 0x22, 0x9b, 0x12, 0x36, 0x3a, 0x61, 0x8e, 0x6e, 0x3a, 0xba, 0x89, 0x6a, 0x6b,
	0x92, 0xe6, 0x46, 0x92, 0x5e, 0xba, 0x61, 0xb0, 0x29, 0x41, 0xca, 0xc0, 0x85, 0xbd, 0x62, 0x41,
	0xd9, 0x8e, 0x08, 0xfb, 0x10, 0x8e, 0x85, 0xc7, 0x68, 0xa2, 0x8f, 0x7f, 0x9c, 0x98, 0x33, 0x8f,
	0xd9, 0x4e, 0x9e, 0x97, 0x6e, 0x18, 0xa8, 0xf6, 0x19, 0xdc, 0x20, 0x13, 0xa4, 0xfc, 0x1b, 0x00,
	0x00, 0xff, 0xff, 0x63, 0x59, 0xb3, 0x2c, 0x86, 0x0a, 0x00, 0x00,
}
