[log]
log_type=zap
log_level=debug
with_caller=true
max_age=8
# true 使用时间分隔日志 false 按照以前文件大小分隔日志
use_new_rule=true
# 1-60分钟 使用时间分隔日志的单位
minute=30

[service]
address=5997
address_prot=2
address_2=5999
address_prot_2=8
address_3=5998
address_prot_3=4
need_fc_special_svr_id=true


[CgkCfg]
redis=127.0.0.1:6379


[mysql]
address=127.0.0.1:3306
db_user="root"
pwd="mysql"
db_name="maze" # 本地使用的数据库名字