// Code generated by protoc-gen-go.
// source: paipai_world/common/UserBaseInfoCli.proto
// DO NOT EDIT!

/*
Package UserBaseInfoCli is a generated protocol buffer package.

It is generated from these files:
	paipai_world/common/UserBaseInfoCli.proto

It has these top-level messages:
	UserBaseInfo
	UserBaseInfoRQ
	UserBaseInfoRS
	UserVipLevel
	SimpleUserInfo
	UserDisplayAttrInfo
	UserFamilyDisplayInfoRQ
	UserFamilyDisplayInfoRS
	UserCacheInfoRQ
	UserCacheInfoRS
	UserFamilyMemberInfoRQ
	UserFamilyMemberInfoRS
*/
package UserBaseInfoCli

import proto "gitlab.ifreetalk.com/plate/extra/protobuf/proto"
import fmt "fmt"
import math "math"
import MessageType "gitlab.ifreetalk.com/plate/protodef/MessageType"
import Pendant "gitlab.ifreetalk.com/plate/protodef/Pendant"
import BaseStruct "gitlab.ifreetalk.com/plate/protodef/BaseStruct"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type UserBaseInfo struct {
	UserId            *uint64                  `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Nickname          *string                  `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Sex               *int32                   `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`
	IconToken         *int32                   `protobuf:"varint,4,opt,name=icon_token,json=iconToken" json:"icon_token,omitempty"`
	VipLevel          *uint32                  `protobuf:"varint,5,opt,name=vip_level,json=vipLevel" json:"vip_level,omitempty"`
	Shengwang         *uint64                  `protobuf:"varint,6,opt,name=shengwang" json:"shengwang,omitempty"`
	AdvanceCount      *uint32                  `protobuf:"varint,7,opt,name=advance_count,json=advanceCount" json:"advance_count,omitempty"`
	ExploerLevel      *uint32                  `protobuf:"varint,8,opt,name=exploer_level,json=exploerLevel" json:"exploer_level,omitempty"`
	ExploreInfluence  *uint64                  `protobuf:"varint,9,opt,name=explore_influence,json=exploreInfluence" json:"explore_influence,omitempty"`
	LandArea          *uint64                  `protobuf:"varint,10,opt,name=landArea" json:"landArea,omitempty"`
	Population        *uint64                  `protobuf:"varint,11,opt,name=population" json:"population,omitempty"`
	Prosperity        *uint64                  `protobuf:"varint,12,opt,name=prosperity" json:"prosperity,omitempty"`
	HkStatus          *int32                   `protobuf:"varint,13,opt,name=hk_status,json=hkStatus" json:"hk_status,omitempty"`
	FamilyId          *int32                   `protobuf:"varint,14,opt,name=family_id,json=familyId" json:"family_id,omitempty"`
	FamilyName        *string                  `protobuf:"bytes,15,opt,name=family_name,json=familyName" json:"family_name,omitempty"`
	MainlandHomeLevel *int32                   `protobuf:"varint,16,opt,name=mainland_home_level,json=mainlandHomeLevel" json:"mainland_home_level,omitempty"`
	LeagueId          *uint64                  `protobuf:"varint,17,opt,name=league_id,json=leagueId" json:"league_id,omitempty"`
	LeagueName        *string                  `protobuf:"bytes,18,opt,name=league_name,json=leagueName" json:"league_name,omitempty"`
	HomePhotoToken    *int32                   `protobuf:"varint,19,opt,name=home_photo_token,json=homePhotoToken" json:"home_photo_token,omitempty"`
	NobleLevel        *int32                   `protobuf:"varint,20,opt,name=noble_level,json=nobleLevel" json:"noble_level,omitempty"`
	AlbumToken        *int32                   `protobuf:"varint,21,opt,name=albumToken" json:"albumToken,omitempty"`
	Pendant           *Pendant.PendantInfo     `protobuf:"bytes,22,opt,name=pendant" json:"pendant,omitempty"`
	Dynamictitle      *BaseStruct.DynamicTitle `protobuf:"bytes,23,opt,name=dynamictitle" json:"dynamictitle,omitempty"`
	CityCode          *int32                   `protobuf:"varint,24,opt,name=city_code,json=cityCode" json:"city_code,omitempty"`
	PowerCount        *int32                   `protobuf:"varint,25,opt,name=power_count,json=powerCount" json:"power_count,omitempty"`
	BlackDiamond      *int32                   `protobuf:"varint,26,opt,name=black_diamond,json=blackDiamond" json:"black_diamond,omitempty"`
	YellowDiamond     *int32                   `protobuf:"varint,27,opt,name=yellow_diamond,json=yellowDiamond" json:"yellow_diamond,omitempty"`
	// optional uint64       max_ship_power	    = 28;  ///  用户船只最高战力  废弃
	MaxShipPower            *float64 `protobuf:"fixed64,29,opt,name=max_ship_power,json=maxShipPower" json:"max_ship_power,omitempty"`
	LeagueMapId             *int32   `protobuf:"varint,30,opt,name=league_map_id,json=leagueMapId" json:"league_map_id,omitempty"`
	MapName                 *string  `protobuf:"bytes,31,opt,name=map_name,json=mapName" json:"map_name,omitempty"`
	LeagueSimpleName        *string  `protobuf:"bytes,32,opt,name=league_simple_name,json=leagueSimpleName" json:"league_simple_name,omitempty"`
	MergeName               *string  `protobuf:"bytes,33,opt,name=merge_name,json=mergeName" json:"merge_name,omitempty"`
	MonthCard               *int64   `protobuf:"varint,34,opt,name=month_card,json=monthCard" json:"month_card,omitempty"`
	BreedUser               *bool    `protobuf:"varint,35,opt,name=breed_user,json=breedUser" json:"breed_user,omitempty"`
	LeagueIndex             *int32   `protobuf:"varint,37,opt,name=league_index,json=leagueIndex" json:"league_index,omitempty"`
	DollLevel               *int32   `protobuf:"varint,38,opt,name=doll_level,json=dollLevel" json:"doll_level,omitempty"`
	ForceValue              *uint64  `protobuf:"varint,39,opt,name=force_value,json=forceValue" json:"force_value,omitempty"`
	XiuId                   *uint64  `protobuf:"varint,40,opt,name=xiu_id,json=xiuId" json:"xiu_id,omitempty"`
	WeaponId                *uint64  `protobuf:"varint,41,opt,name=weapon_id,json=weaponId" json:"weapon_id,omitempty"`
	DollDukeId              *int32   `protobuf:"varint,42,opt,name=doll_duke_id,json=dollDukeId" json:"doll_duke_id,omitempty"`
	WeaponModelId           *int32   `protobuf:"varint,43,opt,name=weapon_model_id,json=weaponModelId" json:"weapon_model_id,omitempty"`
	ShowQuality             *int32   `protobuf:"varint,44,opt,name=show_quality,json=showQuality" json:"show_quality,omitempty"`
	WeaponResId             *uint64  `protobuf:"varint,45,opt,name=weapon_resId,json=weaponResId" json:"weapon_resId,omitempty"`
	MagicweaponStrengthenLv *int32   `protobuf:"varint,46,opt,name=magicweapon_strengthen_lv,json=magicweaponStrengthenLv" json:"magicweapon_strengthen_lv,omitempty"`
	MagicweaponStageLv      *int32   `protobuf:"varint,47,opt,name=magicweapon_stage_lv,json=magicweaponStageLv" json:"magicweapon_stage_lv,omitempty"`
	EnchantQuality          *int32   `protobuf:"varint,48,opt,name=enchant_quality,json=enchantQuality" json:"enchant_quality,omitempty"`
	XXX_unrecognized        []byte   `json:"-"`
}

func (m *UserBaseInfo) Reset()                    { *m = UserBaseInfo{} }
func (m *UserBaseInfo) String() string            { return proto.CompactTextString(m) }
func (*UserBaseInfo) ProtoMessage()               {}
func (*UserBaseInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *UserBaseInfo) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserBaseInfo) GetNickname() string {
	if m != nil && m.Nickname != nil {
		return *m.Nickname
	}
	return ""
}

func (m *UserBaseInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *UserBaseInfo) GetIconToken() int32 {
	if m != nil && m.IconToken != nil {
		return *m.IconToken
	}
	return 0
}

func (m *UserBaseInfo) GetVipLevel() uint32 {
	if m != nil && m.VipLevel != nil {
		return *m.VipLevel
	}
	return 0
}

func (m *UserBaseInfo) GetShengwang() uint64 {
	if m != nil && m.Shengwang != nil {
		return *m.Shengwang
	}
	return 0
}

func (m *UserBaseInfo) GetAdvanceCount() uint32 {
	if m != nil && m.AdvanceCount != nil {
		return *m.AdvanceCount
	}
	return 0
}

func (m *UserBaseInfo) GetExploerLevel() uint32 {
	if m != nil && m.ExploerLevel != nil {
		return *m.ExploerLevel
	}
	return 0
}

func (m *UserBaseInfo) GetExploreInfluence() uint64 {
	if m != nil && m.ExploreInfluence != nil {
		return *m.ExploreInfluence
	}
	return 0
}

func (m *UserBaseInfo) GetLandArea() uint64 {
	if m != nil && m.LandArea != nil {
		return *m.LandArea
	}
	return 0
}

func (m *UserBaseInfo) GetPopulation() uint64 {
	if m != nil && m.Population != nil {
		return *m.Population
	}
	return 0
}

func (m *UserBaseInfo) GetProsperity() uint64 {
	if m != nil && m.Prosperity != nil {
		return *m.Prosperity
	}
	return 0
}

func (m *UserBaseInfo) GetHkStatus() int32 {
	if m != nil && m.HkStatus != nil {
		return *m.HkStatus
	}
	return 0
}

func (m *UserBaseInfo) GetFamilyId() int32 {
	if m != nil && m.FamilyId != nil {
		return *m.FamilyId
	}
	return 0
}

func (m *UserBaseInfo) GetFamilyName() string {
	if m != nil && m.FamilyName != nil {
		return *m.FamilyName
	}
	return ""
}

func (m *UserBaseInfo) GetMainlandHomeLevel() int32 {
	if m != nil && m.MainlandHomeLevel != nil {
		return *m.MainlandHomeLevel
	}
	return 0
}

func (m *UserBaseInfo) GetLeagueId() uint64 {
	if m != nil && m.LeagueId != nil {
		return *m.LeagueId
	}
	return 0
}

func (m *UserBaseInfo) GetLeagueName() string {
	if m != nil && m.LeagueName != nil {
		return *m.LeagueName
	}
	return ""
}

func (m *UserBaseInfo) GetHomePhotoToken() int32 {
	if m != nil && m.HomePhotoToken != nil {
		return *m.HomePhotoToken
	}
	return 0
}

func (m *UserBaseInfo) GetNobleLevel() int32 {
	if m != nil && m.NobleLevel != nil {
		return *m.NobleLevel
	}
	return 0
}

func (m *UserBaseInfo) GetAlbumToken() int32 {
	if m != nil && m.AlbumToken != nil {
		return *m.AlbumToken
	}
	return 0
}

func (m *UserBaseInfo) GetPendant() *Pendant.PendantInfo {
	if m != nil {
		return m.Pendant
	}
	return nil
}

func (m *UserBaseInfo) GetDynamictitle() *BaseStruct.DynamicTitle {
	if m != nil {
		return m.Dynamictitle
	}
	return nil
}

func (m *UserBaseInfo) GetCityCode() int32 {
	if m != nil && m.CityCode != nil {
		return *m.CityCode
	}
	return 0
}

func (m *UserBaseInfo) GetPowerCount() int32 {
	if m != nil && m.PowerCount != nil {
		return *m.PowerCount
	}
	return 0
}

func (m *UserBaseInfo) GetBlackDiamond() int32 {
	if m != nil && m.BlackDiamond != nil {
		return *m.BlackDiamond
	}
	return 0
}

func (m *UserBaseInfo) GetYellowDiamond() int32 {
	if m != nil && m.YellowDiamond != nil {
		return *m.YellowDiamond
	}
	return 0
}

func (m *UserBaseInfo) GetMaxShipPower() float64 {
	if m != nil && m.MaxShipPower != nil {
		return *m.MaxShipPower
	}
	return 0
}

func (m *UserBaseInfo) GetLeagueMapId() int32 {
	if m != nil && m.LeagueMapId != nil {
		return *m.LeagueMapId
	}
	return 0
}

func (m *UserBaseInfo) GetMapName() string {
	if m != nil && m.MapName != nil {
		return *m.MapName
	}
	return ""
}

func (m *UserBaseInfo) GetLeagueSimpleName() string {
	if m != nil && m.LeagueSimpleName != nil {
		return *m.LeagueSimpleName
	}
	return ""
}

func (m *UserBaseInfo) GetMergeName() string {
	if m != nil && m.MergeName != nil {
		return *m.MergeName
	}
	return ""
}

func (m *UserBaseInfo) GetMonthCard() int64 {
	if m != nil && m.MonthCard != nil {
		return *m.MonthCard
	}
	return 0
}

func (m *UserBaseInfo) GetBreedUser() bool {
	if m != nil && m.BreedUser != nil {
		return *m.BreedUser
	}
	return false
}

func (m *UserBaseInfo) GetLeagueIndex() int32 {
	if m != nil && m.LeagueIndex != nil {
		return *m.LeagueIndex
	}
	return 0
}

func (m *UserBaseInfo) GetDollLevel() int32 {
	if m != nil && m.DollLevel != nil {
		return *m.DollLevel
	}
	return 0
}

func (m *UserBaseInfo) GetForceValue() uint64 {
	if m != nil && m.ForceValue != nil {
		return *m.ForceValue
	}
	return 0
}

func (m *UserBaseInfo) GetXiuId() uint64 {
	if m != nil && m.XiuId != nil {
		return *m.XiuId
	}
	return 0
}

func (m *UserBaseInfo) GetWeaponId() uint64 {
	if m != nil && m.WeaponId != nil {
		return *m.WeaponId
	}
	return 0
}

func (m *UserBaseInfo) GetDollDukeId() int32 {
	if m != nil && m.DollDukeId != nil {
		return *m.DollDukeId
	}
	return 0
}

func (m *UserBaseInfo) GetWeaponModelId() int32 {
	if m != nil && m.WeaponModelId != nil {
		return *m.WeaponModelId
	}
	return 0
}

func (m *UserBaseInfo) GetShowQuality() int32 {
	if m != nil && m.ShowQuality != nil {
		return *m.ShowQuality
	}
	return 0
}

func (m *UserBaseInfo) GetWeaponResId() uint64 {
	if m != nil && m.WeaponResId != nil {
		return *m.WeaponResId
	}
	return 0
}

func (m *UserBaseInfo) GetMagicweaponStrengthenLv() int32 {
	if m != nil && m.MagicweaponStrengthenLv != nil {
		return *m.MagicweaponStrengthenLv
	}
	return 0
}

func (m *UserBaseInfo) GetMagicweaponStageLv() int32 {
	if m != nil && m.MagicweaponStageLv != nil {
		return *m.MagicweaponStageLv
	}
	return 0
}

func (m *UserBaseInfo) GetEnchantQuality() int32 {
	if m != nil && m.EnchantQuality != nil {
		return *m.EnchantQuality
	}
	return 0
}

// ## 0
// 10425	UN_TCP_PACK_CLI_PAI_WORLD_USER_BASE_INFO_RQ	派派世界查询用户基本信息请求
type UserBaseInfoRQ struct {
	UserIdList       []uint64 `protobuf:"varint,1,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserBaseInfoRQ) Reset()                    { *m = UserBaseInfoRQ{} }
func (m *UserBaseInfoRQ) String() string            { return proto.CompactTextString(m) }
func (*UserBaseInfoRQ) ProtoMessage()               {}
func (*UserBaseInfoRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *UserBaseInfoRQ) GetUserIdList() []uint64 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

// ## 1
// 10426	UN_TCP_PACK_CLI_PAI_WORLD_USER_BASE_INFO_RS	派派世界查询用户基本信息响应
type UserBaseInfoRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserInfoList     []*UserBaseInfo        `protobuf:"bytes,2,rep,name=user_info_list,json=userInfoList" json:"user_info_list,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *UserBaseInfoRS) Reset()                    { *m = UserBaseInfoRS{} }
func (m *UserBaseInfoRS) String() string            { return proto.CompactTextString(m) }
func (*UserBaseInfoRS) ProtoMessage()               {}
func (*UserBaseInfoRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *UserBaseInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *UserBaseInfoRS) GetUserInfoList() []*UserBaseInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

type UserVipLevel struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserId           *uint64                `protobuf:"varint,2,req,name=user_id,json=userId" json:"user_id,omitempty"`
	VipType          *uint32                `protobuf:"varint,3,opt,name=vip_type,json=vipType" json:"vip_type,omitempty"`
	CreateTime       *uint32                `protobuf:"varint,4,opt,name=create_time,json=createTime" json:"create_time,omitempty"`
	VipEndTime       *uint32                `protobuf:"varint,5,opt,name=vip_end_time,json=vipEndTime" json:"vip_end_time,omitempty"`
	Reserved         *uint64                `protobuf:"varint,6,opt,name=reserved" json:"reserved,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *UserVipLevel) Reset()                    { *m = UserVipLevel{} }
func (m *UserVipLevel) String() string            { return proto.CompactTextString(m) }
func (*UserVipLevel) ProtoMessage()               {}
func (*UserVipLevel) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *UserVipLevel) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *UserVipLevel) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserVipLevel) GetVipType() uint32 {
	if m != nil && m.VipType != nil {
		return *m.VipType
	}
	return 0
}

func (m *UserVipLevel) GetCreateTime() uint32 {
	if m != nil && m.CreateTime != nil {
		return *m.CreateTime
	}
	return 0
}

func (m *UserVipLevel) GetVipEndTime() uint32 {
	if m != nil && m.VipEndTime != nil {
		return *m.VipEndTime
	}
	return 0
}

func (m *UserVipLevel) GetReserved() uint64 {
	if m != nil && m.Reserved != nil {
		return *m.Reserved
	}
	return 0
}

// 用户
type SimpleUserInfo struct {
	Sex              *int32 `protobuf:"varint,1,opt,name=sex" json:"sex,omitempty"`
	Nickname         []byte `protobuf:"bytes,2,opt,name=nickname" json:"nickname,omitempty"`
	Birthday         *int32 `protobuf:"varint,3,opt,name=birthday" json:"birthday,omitempty"`
	Itoken           *int32 `protobuf:"varint,4,opt,name=itoken" json:"itoken,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *SimpleUserInfo) Reset()                    { *m = SimpleUserInfo{} }
func (m *SimpleUserInfo) String() string            { return proto.CompactTextString(m) }
func (*SimpleUserInfo) ProtoMessage()               {}
func (*SimpleUserInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *SimpleUserInfo) GetSex() int32 {
	if m != nil && m.Sex != nil {
		return *m.Sex
	}
	return 0
}

func (m *SimpleUserInfo) GetNickname() []byte {
	if m != nil {
		return m.Nickname
	}
	return nil
}

func (m *SimpleUserInfo) GetBirthday() int32 {
	if m != nil && m.Birthday != nil {
		return *m.Birthday
	}
	return 0
}

func (m *SimpleUserInfo) GetItoken() int32 {
	if m != nil && m.Itoken != nil {
		return *m.Itoken
	}
	return 0
}

type UserDisplayAttrInfo struct {
	UserId           *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	WealthLevel      *int32  `protobuf:"varint,2,opt,name=wealth_level,json=wealthLevel" json:"wealth_level,omitempty"`
	NobleLevel       *int32  `protobuf:"varint,3,opt,name=noble_level,json=nobleLevel" json:"noble_level,omitempty"`
	MonthCard        *uint32 `protobuf:"varint,4,opt,name=month_card,json=monthCard" json:"month_card,omitempty"`
	BlackDiamond     *int32  `protobuf:"varint,5,opt,name=black_diamond,json=blackDiamond" json:"black_diamond,omitempty"`
	YellowDiamond    *int32  `protobuf:"varint,6,opt,name=yellow_diamond,json=yellowDiamond" json:"yellow_diamond,omitempty"`
	RedDiamond       *uint32 `protobuf:"varint,7,opt,name=red_diamond,json=redDiamond" json:"red_diamond,omitempty"`
	DukeId           *int32  `protobuf:"varint,8,opt,name=duke_id,json=dukeId" json:"duke_id,omitempty"`
	OfficialDukeId   *int32  `protobuf:"varint,9,opt,name=official_duke_id,json=officialDukeId" json:"official_duke_id,omitempty"`
	RenouDuke        *int32  `protobuf:"varint,10,opt,name=renou_duke,json=renouDuke" json:"renou_duke,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *UserDisplayAttrInfo) Reset()                    { *m = UserDisplayAttrInfo{} }
func (m *UserDisplayAttrInfo) String() string            { return proto.CompactTextString(m) }
func (*UserDisplayAttrInfo) ProtoMessage()               {}
func (*UserDisplayAttrInfo) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *UserDisplayAttrInfo) GetUserId() uint64 {
	if m != nil && m.UserId != nil {
		return *m.UserId
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetWealthLevel() int32 {
	if m != nil && m.WealthLevel != nil {
		return *m.WealthLevel
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetNobleLevel() int32 {
	if m != nil && m.NobleLevel != nil {
		return *m.NobleLevel
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetMonthCard() uint32 {
	if m != nil && m.MonthCard != nil {
		return *m.MonthCard
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetBlackDiamond() int32 {
	if m != nil && m.BlackDiamond != nil {
		return *m.BlackDiamond
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetYellowDiamond() int32 {
	if m != nil && m.YellowDiamond != nil {
		return *m.YellowDiamond
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetRedDiamond() uint32 {
	if m != nil && m.RedDiamond != nil {
		return *m.RedDiamond
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetDukeId() int32 {
	if m != nil && m.DukeId != nil {
		return *m.DukeId
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetOfficialDukeId() int32 {
	if m != nil && m.OfficialDukeId != nil {
		return *m.OfficialDukeId
	}
	return 0
}

func (m *UserDisplayAttrInfo) GetRenouDuke() int32 {
	if m != nil && m.RenouDuke != nil {
		return *m.RenouDuke
	}
	return 0
}

// ##13605
// 用户家族页面展示信息查询请求 UN_TCP_PACK_CLI_USER_FAMILY_DISPLAY_INFO_RQ
type UserFamilyDisplayInfoRQ struct {
	UserIdList       []uint64 `protobuf:"varint,1,rep,name=user_id_list,json=userIdList" json:"user_id_list,omitempty"`
	Protocol         *uint32  `protobuf:"varint,2,opt,name=protocol" json:"protocol,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserFamilyDisplayInfoRQ) Reset()                    { *m = UserFamilyDisplayInfoRQ{} }
func (m *UserFamilyDisplayInfoRQ) String() string            { return proto.CompactTextString(m) }
func (*UserFamilyDisplayInfoRQ) ProtoMessage()               {}
func (*UserFamilyDisplayInfoRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *UserFamilyDisplayInfoRQ) GetUserIdList() []uint64 {
	if m != nil {
		return m.UserIdList
	}
	return nil
}

func (m *UserFamilyDisplayInfoRQ) GetProtocol() uint32 {
	if m != nil && m.Protocol != nil {
		return *m.Protocol
	}
	return 0
}

// ##13606
// 用户家族页面展示信息查询响应 UN_TCP_PACK_CLI_USER_FAMILY_DISPLAY_INFO_RS
type UserFamilyDisplayInfoRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserInfoList     []*UserDisplayAttrInfo `protobuf:"bytes,2,rep,name=user_info_list,json=userInfoList" json:"user_info_list,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *UserFamilyDisplayInfoRS) Reset()                    { *m = UserFamilyDisplayInfoRS{} }
func (m *UserFamilyDisplayInfoRS) String() string            { return proto.CompactTextString(m) }
func (*UserFamilyDisplayInfoRS) ProtoMessage()               {}
func (*UserFamilyDisplayInfoRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *UserFamilyDisplayInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *UserFamilyDisplayInfoRS) GetUserInfoList() []*UserDisplayAttrInfo {
	if m != nil {
		return m.UserInfoList
	}
	return nil
}

// ## 3619
// 用户简版基本信息查询请求 UN_TCP_PACK_CLI_USER_SIMPLE_BASE_INFO_RQ
type UserCacheInfoRQ struct {
	UidList          []uint64 `protobuf:"varint,1,rep,name=uid_list,json=uidList" json:"uid_list,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *UserCacheInfoRQ) Reset()                    { *m = UserCacheInfoRQ{} }
func (m *UserCacheInfoRQ) String() string            { return proto.CompactTextString(m) }
func (*UserCacheInfoRQ) ProtoMessage()               {}
func (*UserCacheInfoRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *UserCacheInfoRQ) GetUidList() []uint64 {
	if m != nil {
		return m.UidList
	}
	return nil
}

// ## 3620
// 用户简版基本信息查询响应 UN_TCP_PACK_CLI_USER_SIMPLE_BASE_INFO_RS
type UserCacheInfoRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UinfoList        []*UserBaseInfo        `protobuf:"bytes,2,rep,name=uinfo_list,json=uinfoList" json:"uinfo_list,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *UserCacheInfoRS) Reset()                    { *m = UserCacheInfoRS{} }
func (m *UserCacheInfoRS) String() string            { return proto.CompactTextString(m) }
func (*UserCacheInfoRS) ProtoMessage()               {}
func (*UserCacheInfoRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *UserCacheInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *UserCacheInfoRS) GetUinfoList() []*UserBaseInfo {
	if m != nil {
		return m.UinfoList
	}
	return nil
}

// ## 3770
// 用户简版家族成员基本信息查询请求 UN_TCP_PACK_CLI_FAMILY_MEMBERS_INFO_RQ
type UserFamilyMemberInfoRQ struct {
	FamilyId         *int32 `protobuf:"varint,1,opt,name=family_id,json=familyId" json:"family_id,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *UserFamilyMemberInfoRQ) Reset()                    { *m = UserFamilyMemberInfoRQ{} }
func (m *UserFamilyMemberInfoRQ) String() string            { return proto.CompactTextString(m) }
func (*UserFamilyMemberInfoRQ) ProtoMessage()               {}
func (*UserFamilyMemberInfoRQ) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *UserFamilyMemberInfoRQ) GetFamilyId() int32 {
	if m != nil && m.FamilyId != nil {
		return *m.FamilyId
	}
	return 0
}

// ## 3771
// 用户简版家族成员基本信息查询响应 UN_TCP_PACK_CLI_FAMILY_MEMBERS_INFO_RS
type UserFamilyMemberInfoRS struct {
	ErrInfo          *MessageType.ErrorInfo `protobuf:"bytes,1,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UinfoList        []*UserBaseInfo        `protobuf:"bytes,2,rep,name=uinfo_list,json=uinfoList" json:"uinfo_list,omitempty"`
	XXX_unrecognized []byte                 `json:"-"`
}

func (m *UserFamilyMemberInfoRS) Reset()                    { *m = UserFamilyMemberInfoRS{} }
func (m *UserFamilyMemberInfoRS) String() string            { return proto.CompactTextString(m) }
func (*UserFamilyMemberInfoRS) ProtoMessage()               {}
func (*UserFamilyMemberInfoRS) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *UserFamilyMemberInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if m != nil {
		return m.ErrInfo
	}
	return nil
}

func (m *UserFamilyMemberInfoRS) GetUinfoList() []*UserBaseInfo {
	if m != nil {
		return m.UinfoList
	}
	return nil
}

func init() {
	proto.RegisterType((*UserBaseInfo)(nil), "UserBaseInfoCli.UserBaseInfo")
	proto.RegisterType((*UserBaseInfoRQ)(nil), "UserBaseInfoCli.UserBaseInfoRQ")
	proto.RegisterType((*UserBaseInfoRS)(nil), "UserBaseInfoCli.UserBaseInfoRS")
	proto.RegisterType((*UserVipLevel)(nil), "UserBaseInfoCli.UserVipLevel")
	proto.RegisterType((*SimpleUserInfo)(nil), "UserBaseInfoCli.SimpleUserInfo")
	proto.RegisterType((*UserDisplayAttrInfo)(nil), "UserBaseInfoCli.UserDisplayAttrInfo")
	proto.RegisterType((*UserFamilyDisplayInfoRQ)(nil), "UserBaseInfoCli.UserFamilyDisplayInfoRQ")
	proto.RegisterType((*UserFamilyDisplayInfoRS)(nil), "UserBaseInfoCli.UserFamilyDisplayInfoRS")
	proto.RegisterType((*UserCacheInfoRQ)(nil), "UserBaseInfoCli.UserCacheInfoRQ")
	proto.RegisterType((*UserCacheInfoRS)(nil), "UserBaseInfoCli.UserCacheInfoRS")
	proto.RegisterType((*UserFamilyMemberInfoRQ)(nil), "UserBaseInfoCli.UserFamilyMemberInfoRQ")
	proto.RegisterType((*UserFamilyMemberInfoRS)(nil), "UserBaseInfoCli.UserFamilyMemberInfoRS")
}

func init() { proto.RegisterFile("paipai_world/common/UserBaseInfoCli.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 1375 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0xcd, 0x72, 0xdb, 0xb6,
	0x16, 0x1e, 0xda, 0xb1, 0x2d, 0x1d, 0x49, 0xfe, 0x61, 0x12, 0x9b, 0x76, 0xae, 0x63, 0x45, 0xf9,
	0x53, 0x6e, 0x72, 0x95, 0x5c, 0xcf, 0x74, 0xd3, 0xc9, 0x26, 0xb5, 0xd3, 0xa9, 0x3a, 0x76, 0x27,
	0xa1, 0x9d, 0x74, 0xc9, 0x81, 0x09, 0x58, 0xc4, 0x98, 0x04, 0x58, 0x90, 0x94, 0xad, 0x6d, 0x57,
	0xed, 0x1b, 0xf4, 0xc1, 0xba, 0xec, 0xa2, 0x8f, 0xd2, 0x39, 0x07, 0x90, 0x2c, 0x29, 0x49, 0x27,
	0xcd, 0xa2, 0x2b, 0x09, 0xdf, 0xf9, 0x80, 0x03, 0x9c, 0xbf, 0x8f, 0xf0, 0x24, 0x67, 0x32, 0x67,
	0x32, 0xba, 0xd4, 0x26, 0xe5, 0xcf, 0x63, 0x9d, 0x65, 0x5a, 0x3d, 0x7f, 0x57, 0x08, 0xf3, 0x0d,
	0x2b, 0x44, 0x5f, 0x9d, 0xeb, 0x83, 0x54, 0xf6, 0x72, 0xa3, 0x4b, 0xed, 0xaf, 0xcd, 0xc1, 0x3b,
	0x1b, 0xc7, 0xa2, 0x28, 0xd8, 0x40, 0x9c, 0x8e, 0x72, 0x61, 0x39, 0x3b, 0xad, 0x37, 0x42, 0x71,
	0xa6, 0x4a, 0xb7, 0x5c, 0x47, 0xfa, 0x49, 0x69, 0xaa, 0xd8, 0x21, 0x9d, 0x3f, 0x9a, 0xd0, 0x9c,
	0x3e, 0xc7, 0xdf, 0x82, 0x95, 0xaa, 0x10, 0x26, 0x92, 0x3c, 0xf0, 0xda, 0x5e, 0xf7, 0x46, 0xb8,
	0x8c, 0xcb, 0x3e, 0xf7, 0x77, 0xa0, 0xa6, 0x64, 0x7c, 0xa1, 0x58, 0x26, 0x82, 0x85, 0xb6, 0xd7,
	0xad, 0x87, 0x93, 0xb5, 0xbf, 0x0e, 0x8b, 0x85, 0xb8, 0x0a, 0x16, 0xdb, 0x5e, 0x77, 0x29, 0xc4,
	0xbf, 0xfe, 0x2e, 0x80, 0x8c, 0xb5, 0x8a, 0x4a, 0x7d, 0x21, 0x54, 0x70, 0x83, 0x0c, 0x75, 0x44,
	0x4e, 0x11, 0xf0, 0xef, 0x40, 0x7d, 0x28, 0xf3, 0x28, 0x15, 0x43, 0x91, 0x06, 0x4b, 0x6d, 0xaf,
	0xdb, 0x0a, 0x6b, 0x43, 0x99, 0x1f, 0xe1, 0xda, 0xff, 0x0f, 0xd4, 0x8b, 0x44, 0xa8, 0xc1, 0x25,
	0x53, 0x83, 0x60, 0x99, 0x2e, 0x71, 0x0d, 0xf8, 0xf7, 0xa1, 0xc5, 0xf8, 0x90, 0xa9, 0x58, 0x44,
	0xb1, 0xae, 0x54, 0x19, 0xac, 0xd0, 0xf6, 0xa6, 0x03, 0x0f, 0x10, 0x43, 0x92, 0xb8, 0xca, 0x53,
	0x2d, 0x8c, 0xf3, 0x51, 0xb3, 0x24, 0x07, 0x5a, 0x3f, 0x4f, 0x61, 0x83, 0xd6, 0x46, 0x44, 0x52,
	0x9d, 0xa7, 0x95, 0x50, 0xb1, 0x08, 0xea, 0xe4, 0x6f, 0xdd, 0x19, 0xfa, 0x63, 0x1c, 0x9f, 0x9f,
	0x32, 0xc5, 0x5f, 0x19, 0xc1, 0x02, 0x20, 0xce, 0x64, 0xed, 0xdf, 0x05, 0xc8, 0x75, 0x5e, 0xa5,
	0xac, 0x94, 0x5a, 0x05, 0x0d, 0xb2, 0x4e, 0x21, 0x64, 0x37, 0xba, 0xc8, 0x85, 0x91, 0xe5, 0x28,
	0x68, 0x3a, 0xfb, 0x04, 0xc1, 0x68, 0x24, 0x17, 0x51, 0x51, 0xb2, 0xb2, 0x2a, 0x82, 0x16, 0xc5,
	0xaa, 0x96, 0x5c, 0x9c, 0xd0, 0x1a, 0x8d, 0xe7, 0x2c, 0x93, 0xe9, 0x08, 0x53, 0xb2, 0x6a, 0x8d,
	0x16, 0xe8, 0x73, 0x7f, 0x0f, 0x1a, 0xce, 0x48, 0x79, 0x59, 0xa3, 0xbc, 0x80, 0x85, 0x7e, 0xc0,
	0xcc, 0xf4, 0xe0, 0x66, 0xc6, 0xa4, 0xc2, 0xab, 0x46, 0x89, 0xce, 0x84, 0x0b, 0xc7, 0x3a, 0x9d,
	0xb3, 0x31, 0x36, 0x7d, 0xa7, 0x33, 0x61, 0x63, 0x72, 0x07, 0xea, 0xa9, 0x60, 0x83, 0x4a, 0xa0,
	0xb7, 0x0d, 0xf7, 0x4e, 0x02, 0xac, 0x37, 0x67, 0x24, 0x6f, 0xbe, 0xf5, 0x66, 0x21, 0xf2, 0xd6,
	0x85, 0x75, 0x72, 0x92, 0x27, 0xba, 0xd4, 0x2e, 0xf7, 0x37, 0xc9, 0xd5, 0x2a, 0xe2, 0x6f, 0x10,
	0xb6, 0x05, 0xb0, 0x07, 0x0d, 0xa5, 0xcf, 0xd2, 0xf1, 0x7d, 0x6e, 0x11, 0x09, 0x08, 0xb2, 0x17,
	0xb9, 0x0b, 0xc0, 0xd2, 0xb3, 0x2a, 0x23, 0x7a, 0x70, 0xdb, 0xda, 0xaf, 0x11, 0xbf, 0x07, 0x2b,
	0xb9, 0xad, 0xed, 0x60, 0xb3, 0xed, 0x75, 0x1b, 0xfb, 0xb7, 0x7a, 0xe3, 0x5a, 0x77, 0xbf, 0x58,
	0xce, 0xe1, 0x98, 0xe4, 0xbf, 0x84, 0x26, 0x1f, 0x29, 0x96, 0xc9, 0xb8, 0x94, 0x65, 0x2a, 0x82,
	0x2d, 0xda, 0x14, 0xf4, 0xa6, 0x3a, 0xe2, 0xd0, 0xda, 0x4f, 0xd1, 0x1e, 0xce, 0xb0, 0x31, 0x2c,
	0xb1, 0x2c, 0x47, 0x51, 0xac, 0xb9, 0x08, 0x02, 0x9b, 0x04, 0x04, 0x0e, 0x34, 0x17, 0xf8, 0x96,
	0x5c, 0x5f, 0x0a, 0xe3, 0xea, 0x71, 0xdb, 0xde, 0x95, 0xa0, 0x49, 0x35, 0x9e, 0xa5, 0x2c, 0xbe,
	0x88, 0xb8, 0x64, 0x99, 0x56, 0x3c, 0xd8, 0x21, 0x4a, 0x93, 0xc0, 0x43, 0x8b, 0xf9, 0x0f, 0x61,
	0x75, 0x24, 0xd2, 0x54, 0x5f, 0x4e, 0x58, 0x77, 0x88, 0xd5, 0xb2, 0xe8, 0x98, 0xf6, 0x00, 0x56,
	0x33, 0x76, 0x15, 0x15, 0x89, 0xcc, 0x23, 0x72, 0x11, 0xec, 0xb6, 0xbd, 0xae, 0x17, 0x36, 0x33,
	0x76, 0x75, 0x92, 0xc8, 0xfc, 0x0d, 0x62, 0x7e, 0x07, 0x5a, 0x2e, 0x53, 0x19, 0xcb, 0x31, 0x95,
	0x77, 0xe9, 0x2c, 0x97, 0xbe, 0x63, 0x96, 0xf7, 0xb9, 0xbf, 0x0d, 0x35, 0x34, 0x52, 0x2a, 0xf7,
	0x28, 0x95, 0x2b, 0x19, 0xcb, 0x29, 0x8f, 0xcf, 0xc0, 0x77, 0xdb, 0x0b, 0x99, 0xe5, 0xa9, 0xcb,
	0x77, 0x9b, 0x48, 0xeb, 0xd6, 0x72, 0x42, 0x06, 0x62, 0xef, 0x02, 0x64, 0xc2, 0x0c, 0x1c, 0xeb,
	0x1e, 0xb1, 0xea, 0x84, 0x4c, 0xcc, 0x5a, 0x95, 0x49, 0x14, 0x33, 0xc3, 0x83, 0x4e, 0xdb, 0xeb,
	0x2e, 0x86, 0x75, 0x42, 0x0e, 0x98, 0xe1, 0x68, 0x3e, 0x33, 0x42, 0xf0, 0x08, 0xe7, 0x4c, 0x70,
	0xbf, 0xed, 0x75, 0x6b, 0x61, 0x9d, 0x10, 0x9c, 0x4b, 0xfe, 0x3d, 0x68, 0x8e, 0x0b, 0x52, 0x71,
	0x71, 0x15, 0x3c, 0x9c, 0x7e, 0x48, 0x1f, 0x21, 0x3c, 0x81, 0xeb, 0x34, 0x75, 0xa5, 0xf4, 0xc8,
	0xce, 0x1a, 0x44, 0x6c, 0x25, 0x61, 0x8f, 0x68, 0x13, 0x8b, 0x68, 0xc8, 0xd2, 0x4a, 0x04, 0x8f,
	0x6d, 0xfb, 0x11, 0xf4, 0x1e, 0x11, 0xff, 0x36, 0x2c, 0x5f, 0xc9, 0x0a, 0xa3, 0xd4, 0x25, 0xdb,
	0xd2, 0x95, 0xac, 0xfa, 0x1c, 0x73, 0x7e, 0x29, 0x58, 0xae, 0x15, 0x5a, 0x9e, 0xd8, 0x56, 0xb0,
	0x40, 0x9f, 0xfb, 0x6d, 0x68, 0x92, 0x4f, 0x5e, 0x5d, 0x50, 0xab, 0xfc, 0xd7, 0x26, 0x1d, 0xb1,
	0xc3, 0xea, 0x02, 0x9b, 0xe5, 0x11, 0xac, 0xb9, 0xed, 0x99, 0xe6, 0x22, 0x45, 0xd2, 0x53, 0x9b,
	0x50, 0x0b, 0x1f, 0x23, 0xda, 0xe7, 0xf8, 0xc0, 0x22, 0xd1, 0x97, 0xd1, 0x4f, 0x15, 0x4b, 0x71,
	0x3c, 0x3c, 0xb3, 0x0f, 0x44, 0xec, 0xad, 0x85, 0x90, 0xe2, 0x8e, 0x32, 0xa2, 0xe8, 0xf3, 0xe0,
	0x7f, 0x74, 0x99, 0x86, 0xc5, 0x42, 0x84, 0xfc, 0xaf, 0x61, 0x3b, 0x63, 0x03, 0x19, 0x3b, 0x5e,
	0x51, 0x1a, 0xa1, 0x06, 0x65, 0x22, 0x54, 0x94, 0x0e, 0x83, 0x1e, 0x1d, 0xb9, 0x35, 0x45, 0x38,
	0x99, 0xd8, 0x8f, 0x86, 0xfe, 0x0b, 0xb8, 0x35, 0xbb, 0x97, 0x0d, 0x04, 0x6e, 0x7b, 0x4e, 0xdb,
	0xfc, 0x99, 0x6d, 0x6c, 0x20, 0x8e, 0x86, 0xfe, 0x63, 0x58, 0x13, 0x2a, 0x4e, 0x98, 0x2a, 0x27,
	0xd7, 0x7e, 0x61, 0xdb, 0xdc, 0xc1, 0xee, 0xe6, 0x9d, 0x7d, 0x58, 0x9d, 0x56, 0x97, 0xf0, 0x2d,
	0x06, 0xce, 0xe9, 0x4b, 0x94, 0xca, 0xa2, 0x0c, 0xbc, 0xf6, 0x22, 0xa6, 0xc3, 0x8a, 0xcc, 0x91,
	0x2c, 0xca, 0xce, 0x2f, 0xde, 0xdc, 0xa6, 0x13, 0xff, 0xff, 0x50, 0x13, 0xc6, 0xe0, 0x94, 0xd6,
	0xa4, 0x4a, 0x8d, 0xfd, 0xcd, 0xde, 0xb4, 0xd8, 0xbd, 0x36, 0x46, 0x1b, 0xdb, 0xef, 0xc2, 0xd0,
	0x1f, 0xff, 0x00, 0x56, 0xad, 0x1f, 0x75, 0xae, 0xad, 0xa7, 0x85, 0xf6, 0x62, 0xb7, 0xb1, 0xbf,
	0xdb, 0x9b, 0x57, 0xd3, 0x19, 0x5f, 0x74, 0x39, 0xfc, 0x47, 0x57, 0xf9, 0xdd, 0xb3, 0xea, 0xf8,
	0x7e, 0x2c, 0x4d, 0x5f, 0x70, 0x91, 0x29, 0x41, 0x5d, 0x68, 0x2f, 0x4c, 0x09, 0xea, 0x36, 0xa0,
	0xe4, 0x45, 0xe5, 0x28, 0x17, 0xa4, 0x9c, 0xad, 0x70, 0x65, 0x28, 0x73, 0x3c, 0x06, 0x4b, 0x36,
	0x36, 0x82, 0x95, 0x22, 0x2a, 0x65, 0x26, 0x48, 0x3e, 0x5b, 0x21, 0x58, 0xe8, 0x54, 0x66, 0x02,
	0xa3, 0x88, 0x7b, 0x85, 0xe2, 0x96, 0x61, 0x25, 0x14, 0x86, 0x32, 0x7f, 0xad, 0x38, 0x31, 0x76,
	0xa0, 0x66, 0x44, 0x21, 0xcc, 0x50, 0x70, 0xa7, 0xa1, 0x93, 0x75, 0xc7, 0xc0, 0xaa, 0x6d, 0xdf,
	0x77, 0xee, 0xb1, 0x63, 0x01, 0xf7, 0xae, 0x05, 0x7c, 0x5e, 0xee, 0x9b, 0x53, 0x72, 0xbf, 0x03,
	0xb5, 0x33, 0x69, 0xca, 0x84, 0xb3, 0x91, 0xd3, 0xfc, 0xc9, 0xda, 0xdf, 0x84, 0x65, 0x39, 0x2d,
	0xfa, 0x6e, 0xd5, 0xf9, 0x73, 0x01, 0x6e, 0xa2, 0xbb, 0x43, 0x59, 0xe4, 0x29, 0x1b, 0xbd, 0x2a,
	0x4b, 0xf3, 0xf7, 0xdf, 0x1b, 0xb6, 0xe8, 0xd3, 0x32, 0x71, 0x7d, 0xbd, 0x60, 0xfb, 0xc2, 0x62,
	0x93, 0xce, 0x9e, 0x16, 0x91, 0xc5, 0x0f, 0x44, 0x64, 0x76, 0xf4, 0xd8, 0x30, 0x4e, 0x8d, 0x9e,
	0x0f, 0xe6, 0xf2, 0xd2, 0x67, 0xcd, 0xe5, 0xe5, 0x8f, 0xcd, 0xe5, 0x3d, 0x68, 0x18, 0xc1, 0x27,
	0x1c, 0xfb, 0x51, 0x02, 0x46, 0xf0, 0x31, 0x61, 0x0b, 0x56, 0xc6, 0xc3, 0xa2, 0x66, 0x23, 0xc3,
	0xed, 0xa0, 0xe8, 0xc2, 0xba, 0x3e, 0x3f, 0x97, 0xb1, 0x64, 0xd7, 0xe3, 0xa4, 0x6e, 0xbb, 0x69,
	0x8c, 0xbb, 0x91, 0xb2, 0x0b, 0x60, 0x84, 0xd2, 0x15, 0xd1, 0xe8, 0x2b, 0x64, 0x29, 0xac, 0x13,
	0x82, 0x84, 0xce, 0x8f, 0xb0, 0x85, 0x11, 0xfe, 0x96, 0xd4, 0xdf, 0xc5, 0xf9, 0x73, 0xbb, 0x0e,
	0x73, 0x4a, 0x5f, 0x84, 0xb1, 0xb6, 0xa1, 0x6e, 0x85, 0x93, 0x75, 0xe7, 0x37, 0xef, 0x53, 0x27,
	0x7f, 0x51, 0x6b, 0x7e, 0xff, 0x89, 0xd6, 0x7c, 0xf0, 0xd1, 0xd6, 0x9c, 0x2b, 0x98, 0xb9, 0x0e,
	0x7d, 0x06, 0xf4, 0x19, 0x7c, 0xc0, 0xe2, 0x64, 0x3c, 0x61, 0xb6, 0xa1, 0x56, 0xcd, 0xbe, 0x73,
	0xa5, 0x92, 0x76, 0xb4, 0xfc, 0xec, 0xcd, 0xd3, 0xbf, 0xe8, 0x01, 0x2f, 0x01, 0xaa, 0x7f, 0x38,
	0x57, 0xea, 0xb4, 0x81, 0x2e, 0xf1, 0x15, 0x6c, 0x5e, 0x07, 0xf3, 0x58, 0x64, 0x67, 0xf6, 0x39,
	0xe1, 0xdb, 0xd9, 0x4f, 0x3d, 0x6f, 0xf6, 0x53, 0xaf, 0xf3, 0xab, 0xf7, 0x89, 0x7d, 0xff, 0xfe,
	0x13, 0xfe, 0x0a, 0x00, 0x00, 0xff, 0xff, 0x8c, 0x41, 0xd8, 0x5d, 0xa6, 0x0c, 0x00, 0x00,
}
