// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/UserInfo.proto

package UserInfo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	Common "maze_game_server/pb/common/Common"
	MessageType "maze_game_server/pb/common/MessageType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId    *uint64 `protobuf:"varint,1,opt,name=user_id,json=userId" json:"user_id,omitempty"`          // 用户id
	NickName  *string `protobuf:"bytes,2,opt,name=nick_name,json=nickName" json:"nick_name,omitempty"`     // 用户昵称
	Sex       *int32  `protobuf:"varint,3,opt,name=sex" json:"sex,omitempty"`                              // 用户性别 0默认,1男, 2女
	IconToken *int32  `protobuf:"varint,4,opt,name=icon_token,json=iconToken" json:"icon_token,omitempty"` // 头像Id
}

func (x *UserInfo) Reset() {
	*x = UserInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserInfo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserInfo) ProtoMessage() {}

func (x *UserInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserInfo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserInfo.ProtoReflect.Descriptor instead.
func (*UserInfo) Descriptor() ([]byte, []int) {
	return file_common_UserInfo_proto_rawDescGZIP(), []int{0}
}

func (x *UserInfo) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *UserInfo) GetNickName() string {
	if x != nil && x.NickName != nil {
		return *x.NickName
	}
	return ""
}

func (x *UserInfo) GetSex() int32 {
	if x != nil && x.Sex != nil {
		return *x.Sex
	}
	return 0
}

func (x *UserInfo) GetIconToken() int32 {
	if x != nil && x.IconToken != nil {
		return *x.IconToken
	}
	return 0
}

//## 10481 UN_TCP_PACK_CLI_QUERY_USER_INFO_RQ
// 查询用户资料请求包
type QueryUserInfoRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	UserId []uint64             `protobuf:"varint,2,rep,name=user_id,json=userId" json:"user_id,omitempty"` // 查询用户列表
}

func (x *QueryUserInfoRQ) Reset() {
	*x = QueryUserInfoRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserInfo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoRQ) ProtoMessage() {}

func (x *QueryUserInfoRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserInfo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoRQ.ProtoReflect.Descriptor instead.
func (*QueryUserInfoRQ) Descriptor() ([]byte, []int) {
	return file_common_UserInfo_proto_rawDescGZIP(), []int{1}
}

func (x *QueryUserInfoRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *QueryUserInfoRQ) GetUserId() []uint64 {
	if x != nil {
		return x.UserId
	}
	return nil
}

//## 10482 UN_TCP_PACK_CLI_QUERY_USER_INFO_RS
// 查询用户资料应答包
type QueryUserInfoRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo  *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserInfo []*UserInfo            `protobuf:"bytes,3,rep,name=user_info,json=userInfo" json:"user_info,omitempty"`
}

func (x *QueryUserInfoRS) Reset() {
	*x = QueryUserInfoRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserInfo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *QueryUserInfoRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryUserInfoRS) ProtoMessage() {}

func (x *QueryUserInfoRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserInfo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryUserInfoRS.ProtoReflect.Descriptor instead.
func (*QueryUserInfoRS) Descriptor() ([]byte, []int) {
	return file_common_UserInfo_proto_rawDescGZIP(), []int{2}
}

func (x *QueryUserInfoRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *QueryUserInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *QueryUserInfoRS) GetUserInfo() []*UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

//## 10483 UN_TCP_PACK_CLI_ALTER_USER_INFO_RQ
// 修改用户资料请求包
type AlterUserInfoRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header    *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	AlterInfo *UserInfo            `protobuf:"bytes,2,opt,name=alter_info,json=alterInfo" json:"alter_info,omitempty"` // 待修改的用户信息,服务端全量覆盖
}

func (x *AlterUserInfoRQ) Reset() {
	*x = AlterUserInfoRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserInfo_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterUserInfoRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterUserInfoRQ) ProtoMessage() {}

func (x *AlterUserInfoRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserInfo_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterUserInfoRQ.ProtoReflect.Descriptor instead.
func (*AlterUserInfoRQ) Descriptor() ([]byte, []int) {
	return file_common_UserInfo_proto_rawDescGZIP(), []int{3}
}

func (x *AlterUserInfoRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AlterUserInfoRQ) GetAlterInfo() *UserInfo {
	if x != nil {
		return x.AlterInfo
	}
	return nil
}

//## 10484 UN_TCP_PACK_CLI_ALTER_USER_INFO_RS
// 修改用户资料应答包 注释
type AlterUserInfoRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header   *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo  *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	UserInfo *UserInfo              `protobuf:"bytes,3,opt,name=user_info,json=userInfo" json:"user_info,omitempty"`
}

func (x *AlterUserInfoRS) Reset() {
	*x = AlterUserInfoRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_UserInfo_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AlterUserInfoRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlterUserInfoRS) ProtoMessage() {}

func (x *AlterUserInfoRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_UserInfo_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlterUserInfoRS.ProtoReflect.Descriptor instead.
func (*AlterUserInfoRS) Descriptor() ([]byte, []int) {
	return file_common_UserInfo_proto_rawDescGZIP(), []int{4}
}

func (x *AlterUserInfoRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *AlterUserInfoRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *AlterUserInfoRS) GetUserInfo() *UserInfo {
	if x != nil {
		return x.UserInfo
	}
	return nil
}

var File_common_UserInfo_proto protoreflect.FileDescriptor

var file_common_UserInfo_proto_rawDesc = []byte{
	0x0a, 0x15, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x1a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x22, 0x71, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x17, 0x0a, 0x07,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x75,
	0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x69, 0x63, 0x6b, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x69, 0x63, 0x6b, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x73, 0x65, 0x78, 0x12, 0x1d, 0x0a, 0x0a, 0x69, 0x63, 0x6f, 0x6e, 0x5f, 0x74, 0x6f, 0x6b,
	0x65, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x09, 0x69, 0x63, 0x6f, 0x6e, 0x54, 0x6f,
	0x6b, 0x65, 0x6e, 0x22, 0x58, 0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0xa3, 0x01,
	0x0a, 0x0f, 0x51, 0x75, 0x65, 0x72, 0x79, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52,
	0x53, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65,
	0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12,
	0x31, 0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18,
	0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f,
	0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x22, 0x72, 0x0a, 0x0f, 0x41, 0x6c, 0x74, 0x65, 0x72, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x51, 0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e,
	0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65,
	0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x0a, 0x61, 0x6c, 0x74, 0x65, 0x72, 0x5f, 0x69, 0x6e,
	0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x12, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x09, 0x61, 0x6c,
	0x74, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0xa3, 0x01, 0x0a, 0x0f, 0x41, 0x6c, 0x74, 0x65,
	0x72, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x53, 0x12, 0x2c, 0x0a, 0x06, 0x68,
	0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61, 0x64, 0x65,
	0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x2f, 0x0a, 0x09,
	0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x12, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x33, 0x5a,
	0x23, 0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x55, 0x73, 0x65, 0x72,
	0x49, 0x6e, 0x66, 0x6f, 0xaa, 0x02, 0x0b, 0x50, 0x62, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x49, 0x6e,
	0x66, 0x6f,
}

var (
	file_common_UserInfo_proto_rawDescOnce sync.Once
	file_common_UserInfo_proto_rawDescData = file_common_UserInfo_proto_rawDesc
)

func file_common_UserInfo_proto_rawDescGZIP() []byte {
	file_common_UserInfo_proto_rawDescOnce.Do(func() {
		file_common_UserInfo_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_UserInfo_proto_rawDescData)
	})
	return file_common_UserInfo_proto_rawDescData
}

var file_common_UserInfo_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_common_UserInfo_proto_goTypes = []interface{}{
	(*UserInfo)(nil),              // 0: UserInfo.UserInfo
	(*QueryUserInfoRQ)(nil),       // 1: UserInfo.QueryUserInfoRQ
	(*QueryUserInfoRS)(nil),       // 2: UserInfo.QueryUserInfoRS
	(*AlterUserInfoRQ)(nil),       // 3: UserInfo.AlterUserInfoRQ
	(*AlterUserInfoRS)(nil),       // 4: UserInfo.AlterUserInfoRS
	(*Common.PacketHeader)(nil),   // 5: Common.PacketHeader
	(*MessageType.ErrorInfo)(nil), // 6: MessageType.ErrorInfo
}
var file_common_UserInfo_proto_depIdxs = []int32{
	5, // 0: UserInfo.QueryUserInfoRQ.header:type_name -> Common.PacketHeader
	5, // 1: UserInfo.QueryUserInfoRS.header:type_name -> Common.PacketHeader
	6, // 2: UserInfo.QueryUserInfoRS.err_info:type_name -> MessageType.ErrorInfo
	0, // 3: UserInfo.QueryUserInfoRS.user_info:type_name -> UserInfo.UserInfo
	5, // 4: UserInfo.AlterUserInfoRQ.header:type_name -> Common.PacketHeader
	0, // 5: UserInfo.AlterUserInfoRQ.alter_info:type_name -> UserInfo.UserInfo
	5, // 6: UserInfo.AlterUserInfoRS.header:type_name -> Common.PacketHeader
	6, // 7: UserInfo.AlterUserInfoRS.err_info:type_name -> MessageType.ErrorInfo
	0, // 8: UserInfo.AlterUserInfoRS.user_info:type_name -> UserInfo.UserInfo
	9, // [9:9] is the sub-list for method output_type
	9, // [9:9] is the sub-list for method input_type
	9, // [9:9] is the sub-list for extension type_name
	9, // [9:9] is the sub-list for extension extendee
	0, // [0:9] is the sub-list for field type_name
}

func init() { file_common_UserInfo_proto_init() }
func file_common_UserInfo_proto_init() {
	if File_common_UserInfo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_UserInfo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_UserInfo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_UserInfo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*QueryUserInfoRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_UserInfo_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterUserInfoRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_UserInfo_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AlterUserInfoRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_UserInfo_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_UserInfo_proto_goTypes,
		DependencyIndexes: file_common_UserInfo_proto_depIdxs,
		MessageInfos:      file_common_UserInfo_proto_msgTypes,
	}.Build()
	File_common_UserInfo_proto = out.File
	file_common_UserInfo_proto_rawDesc = nil
	file_common_UserInfo_proto_goTypes = nil
	file_common_UserInfo_proto_depIdxs = nil
}
