// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/Costume.proto

package Costume

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	Common "maze_game_server/pb/common/Common"
	MessageType "maze_game_server/pb/common/MessageType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 装扮
type CostumeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Pos     *int32 `protobuf:"varint,1,opt,name=Pos" json:"Pos,omitempty"`         // 部位
	ModelId *int32 `protobuf:"varint,2,opt,name=ModelId" json:"ModelId,omitempty"` // 模型id
}

func (x *CostumeInfo) Reset() {
	*x = CostumeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Costume_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CostumeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CostumeInfo) ProtoMessage() {}

func (x *CostumeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_Costume_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CostumeInfo.ProtoReflect.Descriptor instead.
func (*CostumeInfo) Descriptor() ([]byte, []int) {
	return file_common_Costume_proto_rawDescGZIP(), []int{0}
}

func (x *CostumeInfo) GetPos() int32 {
	if x != nil && x.Pos != nil {
		return *x.Pos
	}
	return 0
}

func (x *CostumeInfo) GetModelId() int32 {
	if x != nil && x.ModelId != nil {
		return *x.ModelId
	}
	return 0
}

//## 10613 UN_TCP_PACK_CLI_GET_USER_COSTUME_RQ
// 获取用户装扮请求包
type GetUserCostumeRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header *Common.PacketHeader `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
}

func (x *GetUserCostumeRQ) Reset() {
	*x = GetUserCostumeRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Costume_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCostumeRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCostumeRQ) ProtoMessage() {}

func (x *GetUserCostumeRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_Costume_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCostumeRQ.ProtoReflect.Descriptor instead.
func (*GetUserCostumeRQ) Descriptor() ([]byte, []int) {
	return file_common_Costume_proto_rawDescGZIP(), []int{1}
}

func (x *GetUserCostumeRQ) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

//## 10614 UN_TCP_PACK_CLI_GET_USER_COSTUME_RS
// 获取用户装扮响应包
type GetUserCostumeRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Header      *Common.PacketHeader   `protobuf:"bytes,1,opt,name=header" json:"header,omitempty"`
	ErrInfo     *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"`
	CostumeList []*CostumeInfo         `protobuf:"bytes,3,rep,name=costume_list,json=costumeList" json:"costume_list,omitempty"` // 装扮列表
}

func (x *GetUserCostumeRS) Reset() {
	*x = GetUserCostumeRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Costume_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserCostumeRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserCostumeRS) ProtoMessage() {}

func (x *GetUserCostumeRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_Costume_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserCostumeRS.ProtoReflect.Descriptor instead.
func (*GetUserCostumeRS) Descriptor() ([]byte, []int) {
	return file_common_Costume_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserCostumeRS) GetHeader() *Common.PacketHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *GetUserCostumeRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

func (x *GetUserCostumeRS) GetCostumeList() []*CostumeInfo {
	if x != nil {
		return x.CostumeList
	}
	return nil
}

//## 10615 UN_TCP_PACK_CLI_CHANGE_COSTUME_ID
// 推送换装
type ChangeCostumeID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Costume []*CostumeInfo `protobuf:"bytes,1,rep,name=Costume" json:"Costume,omitempty"` // 装扮列表
}

func (x *ChangeCostumeID) Reset() {
	*x = ChangeCostumeID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_Costume_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ChangeCostumeID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeCostumeID) ProtoMessage() {}

func (x *ChangeCostumeID) ProtoReflect() protoreflect.Message {
	mi := &file_common_Costume_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeCostumeID.ProtoReflect.Descriptor instead.
func (*ChangeCostumeID) Descriptor() ([]byte, []int) {
	return file_common_Costume_proto_rawDescGZIP(), []int{3}
}

func (x *ChangeCostumeID) GetCostume() []*CostumeInfo {
	if x != nil {
		return x.Costume
	}
	return nil
}

var File_common_Costume_proto protoreflect.FileDescriptor

var file_common_Costume_proto_rawDesc = []byte{
	0x0a, 0x14, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x07, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x1a,
	0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54,
	0x79, 0x70, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39,
	0x0a, 0x0b, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x10, 0x0a,
	0x03, 0x50, 0x6f, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x50, 0x6f, 0x73, 0x12,
	0x18, 0x0a, 0x07, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x07, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x22, 0x40, 0x0a, 0x10, 0x47, 0x65, 0x74,
	0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x52, 0x51, 0x12, 0x2c, 0x0a,
	0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e,
	0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74, 0x48, 0x65, 0x61,
	0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x22, 0xac, 0x01, 0x0a, 0x10,
	0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x52, 0x53,
	0x12, 0x2c, 0x0a, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x14, 0x2e, 0x43, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x50, 0x61, 0x63, 0x6b, 0x65, 0x74,
	0x48, 0x65, 0x61, 0x64, 0x65, 0x72, 0x52, 0x06, 0x68, 0x65, 0x61, 0x64, 0x65, 0x72, 0x12, 0x31,
	0x0a, 0x08, 0x65, 0x72, 0x72, 0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x16, 0x2e, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45,
	0x72, 0x72, 0x6f, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66,
	0x6f, 0x12, 0x37, 0x0a, 0x0c, 0x63, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x5f, 0x6c, 0x69, 0x73,
	0x74, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d,
	0x65, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0b, 0x63,
	0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x41, 0x0a, 0x0f, 0x43, 0x68,
	0x61, 0x6e, 0x67, 0x65, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x49, 0x44, 0x12, 0x2e, 0x0a,
	0x07, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65,
	0x49, 0x6e, 0x66, 0x6f, 0x52, 0x07, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65, 0x42, 0x31, 0x5a,
	0x22, 0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65,
	0x72, 0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x43, 0x6f, 0x73, 0x74,
	0x75, 0x6d, 0x65, 0xaa, 0x02, 0x0a, 0x50, 0x62, 0x2e, 0x43, 0x6f, 0x73, 0x74, 0x75, 0x6d, 0x65,
}

var (
	file_common_Costume_proto_rawDescOnce sync.Once
	file_common_Costume_proto_rawDescData = file_common_Costume_proto_rawDesc
)

func file_common_Costume_proto_rawDescGZIP() []byte {
	file_common_Costume_proto_rawDescOnce.Do(func() {
		file_common_Costume_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_Costume_proto_rawDescData)
	})
	return file_common_Costume_proto_rawDescData
}

var file_common_Costume_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_common_Costume_proto_goTypes = []interface{}{
	(*CostumeInfo)(nil),           // 0: Costume.CostumeInfo
	(*GetUserCostumeRQ)(nil),      // 1: Costume.GetUserCostumeRQ
	(*GetUserCostumeRS)(nil),      // 2: Costume.GetUserCostumeRS
	(*ChangeCostumeID)(nil),       // 3: Costume.ChangeCostumeID
	(*Common.PacketHeader)(nil),   // 4: Common.PacketHeader
	(*MessageType.ErrorInfo)(nil), // 5: MessageType.ErrorInfo
}
var file_common_Costume_proto_depIdxs = []int32{
	4, // 0: Costume.GetUserCostumeRQ.header:type_name -> Common.PacketHeader
	4, // 1: Costume.GetUserCostumeRS.header:type_name -> Common.PacketHeader
	5, // 2: Costume.GetUserCostumeRS.err_info:type_name -> MessageType.ErrorInfo
	0, // 3: Costume.GetUserCostumeRS.costume_list:type_name -> Costume.CostumeInfo
	0, // 4: Costume.ChangeCostumeID.Costume:type_name -> Costume.CostumeInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_common_Costume_proto_init() }
func file_common_Costume_proto_init() {
	if File_common_Costume_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_Costume_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CostumeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Costume_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCostumeRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Costume_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserCostumeRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_Costume_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ChangeCostumeID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_Costume_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_Costume_proto_goTypes,
		DependencyIndexes: file_common_Costume_proto_depIdxs,
		MessageInfos:      file_common_Costume_proto_msgTypes,
	}.Build()
	File_common_Costume_proto = out.File
	file_common_Costume_proto_rawDesc = nil
	file_common_Costume_proto_goTypes = nil
	file_common_Costume_proto_depIdxs = nil
}
