package naming

import (
	"context"
	"fmt"
	"strings"

	"gitlab.ifreetalk.com/maze-plate/freetk/pkg/discovery"
	//"github.com/cloudwego/kitex/pkg/rpcinfo"
	"github.com/polarismesh/polaris-go/api"
	"github.com/polarismesh/polaris-go/pkg/log"
	"github.com/polarismesh/polaris-go/pkg/model"
)

const (
	DefaultWeight = 10
)

// Resolver is extension interface of Kitex discovery.Resolver.
type Resolver interface {
	discovery.Resolver
	Watcher(ctx context.Context, desc string) (discovery.Change, error)
}

// polarisResolver is a resolver using polaris.
type polarisResolver struct {
	provider api.ProviderAPI
	consumer api.ConsumerAPI
	o        ClientOptions
}

// NewPolarisResolver creates a polaris based resolver.
func NewPolarisResolver(o ClientOptions, configFile ...string) (Resolver, error) {
	sdkCtx, err := GetPolarisConfig(configFile...)
	if err != nil {
		return nil, err
	}

	newInstance := &polarisResolver{
		consumer: api.NewConsumerAPIByContext(sdkCtx),
		provider: api.NewProviderAPIByContext(sdkCtx),
		o:        o,
	}

	return newInstance, nil
}

// Target implements the Resolver interface.
func (pr *polarisResolver) Target(ctx context.Context, target discovery.EndpointInfo) (description string) {
	// serviceName identification is generated by namespace and serviceName to identify serviceName
	var serviceIdentification strings.Builder

	dstNamespace, ok := target.Tag(DstNameSpaceTagKey)
	if ok {
		serviceIdentification.WriteString(dstNamespace)
	} else {
		serviceIdentification.WriteString(DefaultPolarisNamespace)
	}
	serviceIdentification.WriteString(":")
	serviceIdentification.WriteString(target.ServiceName())

	return serviceIdentification.String()
}

// Watcher return registered service changes.
func (pr *polarisResolver) Watcher(ctx context.Context, desc string) (discovery.Change, error) {
	var (
		eps    []discovery.Instance
		add    []discovery.Instance
		update []discovery.Instance
		remove []discovery.Instance
	)
	namespace, serviceName := SplitDescription(desc)
	key := model.ServiceKey{
		Namespace: namespace,
		Service:   serviceName,
	}
	watchReq := api.WatchServiceRequest{}
	watchReq.Key = key
	watchRsp, err := pr.consumer.WatchService(&watchReq)
	if nil != err {
		log.GetBaseLogger().Fatalf("fail to WatchService, err is %v", err)
	}
	instances := watchRsp.GetAllInstancesResp.Instances

	if nil != instances {
		for _, instance := range instances {
			log.GetBaseLogger().Infof("instance getOneInstance is %s:%d", instance.GetHost(), instance.GetPort())
			eps = append(eps, ChangePolarisInstanceToKitex(instance, pr.o))
		}
	}

	result := discovery.Result{
		Cacheable: true,
		CacheKey:  desc,
		Instances: eps,
	}
	Change := discovery.Change{}

	select {
	case <-ctx.Done():
		log.GetBaseLogger().Infof("[Polaris resolver] Watch has been finished")
		return Change, nil
	case event := <-watchRsp.EventChannel:
		eType := event.GetSubScribeEventType()
		if eType == api.EventInstance {
			insEvent := event.(*model.InstanceEvent)
			if insEvent.AddEvent != nil {
				for _, instance := range insEvent.AddEvent.Instances {
					add = append(add, ChangePolarisInstanceToKitex(instance, pr.o))
				}
			}
			if insEvent.UpdateEvent != nil {
				for i := range insEvent.UpdateEvent.UpdateList {
					update = append(update, ChangePolarisInstanceToKitex(insEvent.UpdateEvent.UpdateList[i].After, pr.o))
				}
			}
			if insEvent.DeleteEvent != nil {
				for _, instance := range insEvent.DeleteEvent.Instances {
					remove = append(remove, ChangePolarisInstanceToKitex(instance, pr.o))
				}
			}
			Change = discovery.Change{
				Result:  result,
				Added:   add,
				Updated: update,
				Removed: remove,
			}
		}
		return Change, nil
	}
}

// Resolve implements the Resolver interface.
func (pr *polarisResolver) Resolve(ctx context.Context, desc string) (discovery.Result, error) {
	var eps []discovery.Instance
	retryCount := 3
	namespace, serviceName := SplitDescription(desc)
	getInstances := &api.GetInstancesRequest{}
	getInstances.Namespace = namespace
	getInstances.Service = serviceName
	getInstances.RetryCount = &retryCount
	// getInstances.Metadata = pr.o.DstMetadata
	InstanceResp, err := pr.consumer.GetInstances(getInstances)
	if nil != err {
		log.GetBaseLogger().Fatalf("fail to getOneInstance, err is %v", err)
	}

	instances := InstanceResp.GetInstances()
	if nil != instances {
		for _, instance := range instances {
			log.GetBaseLogger().Infof("instance getOneInstance is %s:%d Metadata=%v", instance.GetHost(), instance.GetPort(), instance.GetMetadata())
			if pr.isFilterInstances(instance.GetMetadata()) {
				continue
			}
			log.GetBaseLogger().Infof("instance getOneInstance is %s:%d", instance.GetHost(), instance.GetPort())
			eps = append(eps, ChangePolarisInstanceToKitex(instance, pr.o))
		}
	}

	if len(eps) == 0 {
		return discovery.Result{}, fmt.Errorf("no instance remains for %s", desc)
	}

	return discovery.Result{
		Cacheable: true,
		CacheKey:  desc,
		Instances: eps,
	}, nil
}

// Diff implements the Resolver interface.
func (pr *polarisResolver) Diff(cacheKey string, prev, next discovery.Result) (discovery.Change, bool) {
	return discovery.DefaultDiff(cacheKey, prev, next)
}

// Name implements the Resolver interface.
func (pr *polarisResolver) Name() string {
	return "Polaris"
}

// isMatchMetadata check if the metadata is matched.
func isMatchMetadata(v string, v2 string) bool {
	vList := strings.Split(v2, ",")
	for _, vvv := range vList {
		if vvv == v {
			return true
		}
	}
	return false
}

// isFilterInstances check if the instance is filtered by metadata.
func (pr *polarisResolver) isFilterInstances(metadata map[string]string) bool {
	for k, v := range pr.o.DstMetadata {
		if vv, ok := metadata[k]; ok {
			if !isMatchMetadata(v, vv) {
				return true
			}
		} else {
			return true
		}
	}
	return false
}
