//请求属性变化包

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.12.4
// source: common/LogonPropertyTrigger.proto

package LogonPropertyTrigger

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	MessageType "maze_game_server/pb/common/MessageType"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

//## 1
type LogonPropertyTriggerRQ struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId *uint64 `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"` /// 用户ID
}

func (x *LogonPropertyTriggerRQ) Reset() {
	*x = LogonPropertyTriggerRQ{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_LogonPropertyTrigger_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogonPropertyTriggerRQ) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogonPropertyTriggerRQ) ProtoMessage() {}

func (x *LogonPropertyTriggerRQ) ProtoReflect() protoreflect.Message {
	mi := &file_common_LogonPropertyTrigger_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogonPropertyTriggerRQ.ProtoReflect.Descriptor instead.
func (*LogonPropertyTriggerRQ) Descriptor() ([]byte, []int) {
	return file_common_LogonPropertyTrigger_proto_rawDescGZIP(), []int{0}
}

func (x *LogonPropertyTriggerRQ) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

//## 2
type LogonPropertyTriggerRS struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId  *uint64                `protobuf:"varint,1,req,name=user_id,json=userId" json:"user_id,omitempty"`   /// 用户ID
	ErrInfo *MessageType.ErrorInfo `protobuf:"bytes,2,opt,name=err_info,json=errInfo" json:"err_info,omitempty"` /// 错误消息
}

func (x *LogonPropertyTriggerRS) Reset() {
	*x = LogonPropertyTriggerRS{}
	if protoimpl.UnsafeEnabled {
		mi := &file_common_LogonPropertyTrigger_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *LogonPropertyTriggerRS) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogonPropertyTriggerRS) ProtoMessage() {}

func (x *LogonPropertyTriggerRS) ProtoReflect() protoreflect.Message {
	mi := &file_common_LogonPropertyTrigger_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogonPropertyTriggerRS.ProtoReflect.Descriptor instead.
func (*LogonPropertyTriggerRS) Descriptor() ([]byte, []int) {
	return file_common_LogonPropertyTrigger_proto_rawDescGZIP(), []int{1}
}

func (x *LogonPropertyTriggerRS) GetUserId() uint64 {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return 0
}

func (x *LogonPropertyTriggerRS) GetErrInfo() *MessageType.ErrorInfo {
	if x != nil {
		return x.ErrInfo
	}
	return nil
}

var File_common_LogonPropertyTrigger_proto protoreflect.FileDescriptor

var file_common_LogonPropertyTrigger_proto_rawDesc = []byte{
	0x0a, 0x21, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4c, 0x6f, 0x67, 0x6f, 0x6e, 0x50, 0x72,
	0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x14, 0x4c, 0x6f, 0x67, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x1a, 0x18, 0x63, 0x6f, 0x6d, 0x6d, 0x6f,
	0x6e, 0x2f, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x31, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x70,
	0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x51, 0x12, 0x17, 0x0a,
	0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28, 0x04, 0x52, 0x06,
	0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x64, 0x0a, 0x16, 0x4c, 0x6f, 0x67, 0x6f, 0x6e, 0x50,
	0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0x52, 0x53,
	0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x02, 0x28,
	0x04, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x31, 0x0a, 0x08, 0x65, 0x72, 0x72,
	0x5f, 0x69, 0x6e, 0x66, 0x6f, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x4d, 0x65,
	0x73, 0x73, 0x61, 0x67, 0x65, 0x54, 0x79, 0x70, 0x65, 0x2e, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x49,
	0x6e, 0x66, 0x6f, 0x52, 0x07, 0x65, 0x72, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x4b, 0x5a, 0x2f,
	0x6d, 0x61, 0x7a, 0x65, 0x5f, 0x67, 0x61, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x65, 0x72,
	0x2f, 0x70, 0x62, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x4c, 0x6f, 0x67, 0x6f, 0x6e,
	0x50, 0x72, 0x6f, 0x70, 0x65, 0x72, 0x74, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72, 0xaa,
	0x02, 0x17, 0x50, 0x62, 0x2e, 0x4c, 0x6f, 0x67, 0x6f, 0x6e, 0x50, 0x72, 0x6f, 0x70, 0x65, 0x72,
	0x74, 0x79, 0x54, 0x72, 0x69, 0x67, 0x67, 0x65, 0x72,
}

var (
	file_common_LogonPropertyTrigger_proto_rawDescOnce sync.Once
	file_common_LogonPropertyTrigger_proto_rawDescData = file_common_LogonPropertyTrigger_proto_rawDesc
)

func file_common_LogonPropertyTrigger_proto_rawDescGZIP() []byte {
	file_common_LogonPropertyTrigger_proto_rawDescOnce.Do(func() {
		file_common_LogonPropertyTrigger_proto_rawDescData = protoimpl.X.CompressGZIP(file_common_LogonPropertyTrigger_proto_rawDescData)
	})
	return file_common_LogonPropertyTrigger_proto_rawDescData
}

var file_common_LogonPropertyTrigger_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_LogonPropertyTrigger_proto_goTypes = []interface{}{
	(*LogonPropertyTriggerRQ)(nil), // 0: LogonPropertyTrigger.LogonPropertyTriggerRQ
	(*LogonPropertyTriggerRS)(nil), // 1: LogonPropertyTrigger.LogonPropertyTriggerRS
	(*MessageType.ErrorInfo)(nil),  // 2: MessageType.ErrorInfo
}
var file_common_LogonPropertyTrigger_proto_depIdxs = []int32{
	2, // 0: LogonPropertyTrigger.LogonPropertyTriggerRS.err_info:type_name -> MessageType.ErrorInfo
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_common_LogonPropertyTrigger_proto_init() }
func file_common_LogonPropertyTrigger_proto_init() {
	if File_common_LogonPropertyTrigger_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_common_LogonPropertyTrigger_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogonPropertyTriggerRQ); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_common_LogonPropertyTrigger_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*LogonPropertyTriggerRS); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_common_LogonPropertyTrigger_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_LogonPropertyTrigger_proto_goTypes,
		DependencyIndexes: file_common_LogonPropertyTrigger_proto_depIdxs,
		MessageInfos:      file_common_LogonPropertyTrigger_proto_msgTypes,
	}.Build()
	File_common_LogonPropertyTrigger_proto = out.File
	file_common_LogonPropertyTrigger_proto_rawDesc = nil
	file_common_LogonPropertyTrigger_proto_goTypes = nil
	file_common_LogonPropertyTrigger_proto_depIdxs = nil
}
